###########################################################################
#
#  NETFPGA10G www.netfpga.org
#
#  Module:
#       tools/scripts/Makefile
#
#  Description:
#       Prepare environment for in-place execution of python scripts.
#
#

link:
	./link-py-interpreter.sh


clean:
	rm -f ./python-nf
	rm -f *.pyc


.PHONY: link clean