// ==============================================================
// RTL generated by AutoPilot - High-Level Synthesis System (C, C++, SystemC)
// Version: 2010.07.ft
// Copyright (C) :2006-2010 AutoESL Design Technologies, Inc.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module header_removal (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        packet_in_data_dout,
        packet_in_data_empty_n,
        packet_in_data_read,
        packet_out_data_aux_din,
        packet_out_data_aux_full_n,
        packet_out_data_aux_write,
        packet_out_data_din,
        packet_out_data_full_n,
        packet_out_data_write
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
input  [63:0] packet_in_data_dout;
input   packet_in_data_empty_n;
output   packet_in_data_read;
output  [63:0] packet_out_data_aux_din;
input   packet_out_data_aux_full_n;
output   packet_out_data_aux_write;
output  [63:0] packet_out_data_din;
input   packet_out_data_full_n;
output   packet_out_data_write;

reg ap_done;
reg ap_idle;
reg packet_in_data_read;
reg[63:0] packet_out_data_aux_din;
reg packet_out_data_aux_write;
reg packet_out_data_write;
reg   [3:0] ap_CS_fsm;
reg   [0:0] offset_flag_2_load_reg_970;
wire   [0:0] tmp_fu_274_p2;
wire   [0:0] tmp1_fu_286_p2;
wire   [0:0] icmp_fu_302_p2;
reg    ap_sig_bdd_54;
reg   [31:0] indvar_next_reg_979;
wire   [0:0] tmp5_fu_308_p2;
reg   [0:0] tmp5_reg_991;
wire   [15:0] Result1_fu_314_p4;
reg   [15:0] Result1_reg_997;
reg   [0:0] sel_tmp1_reg_1002;
reg   [31:0] tmp2_reg_1015;
reg   [10:0] indvar_next1_reg_1023;
reg   [31:0] tmp10_reg_1071;
wire   [0:0] tmp3_fu_438_p2;
reg   [0:0] tmp9_reg_1081;
wire   [31:0] input_count_2_cast_fu_494_p1;
reg   [31:0] input_count_2_cast_reg_1085;
reg   [10:0] indvar_next2_reg_1095;
wire   [0:0] tmp12_fu_499_p2;
reg   [0:0] offset_flag_5_load_reg_1112;
wire   [0:0] icmp1_fu_516_p2;
wire   [0:0] tmp13_fu_613_p2;
wire   [0:0] bothcond_fu_632_p2;
wire   [0:0] tmp27_fu_641_p2;
reg    ap_sig_bdd_128;
wire   [0:0] tmp15_fu_522_p2;
reg   [0:0] tmp15_reg_1117;
wire   [0:0] sel_tmp3_fu_568_p2;
reg   [0:0] sel_tmp3_reg_1124;
reg   [3:0] sel_tmp32_v_reg_1130;
reg   [0:0] tmp16_reg_1135;
reg   [31:0] loop_count2_2_load_reg_1145;
wire   [15:0] extension_header_length_0_in_in_fu_666_p3;
reg   [15:0] extension_header_length_0_in_in_reg_1156;
reg   [0:0] extension_header_length_cast_reg_1161;
reg   [31:0] loop_count_reg_1166;
reg   [0:0] offset_flag_3_reg_1173;
reg   [0:0] tmp20_reg_1178;
reg   [0:0] p_cond_reg_1184;
reg   [29:0] p_neg_t_reg_1189;
reg   [28:0] p_cast2_reg_1194;
reg   [0:0] sel_tmp8_reg_1199;
reg   [31:0] loop_count1_3_reg_1205;
wire   [63:0] packet_out_data_tmp_q0;
reg   [63:0] packet_out_data_tmp_load_reg_1210;
reg    ap_sig_bdd_177;
reg   [9:0] packet_out_data_tmp2_address0;
reg    packet_out_data_tmp2_ce0;
reg    packet_out_data_tmp2_we0;
wire   [63:0] packet_out_data_tmp2_d0;
wire   [63:0] packet_out_data_tmp2_q0;
reg   [9:0] packet_out_data_tmp_address0;
reg    packet_out_data_tmp_ce0;
reg    packet_out_data_tmp_we0;
wire   [63:0] packet_out_data_tmp_d0;
reg   [31:0] input_count_reg_197;
reg   [10:0] input_count_1_reg_210;
reg   [10:0] input_count_2_reg_223;
wire   [31:0] input_count_1_cast_fu_433_p1;
reg   [0:0] offset_flag_2_fu_88;
reg   [31:0] output_count1_1_fu_92;
wire   [31:0] tmp11_cast_fu_354_p1;
reg   [31:0] packet_size_2_fu_96;
reg   [31:0] output_count1_3_fu_108;
wire   [31:0] tmp19_cast_fu_939_p1;
reg   [0:0] offset_flag_5_fu_112;
reg   [31:0] cc_2_fu_116;
wire   [31:0] cc_fu_717_p3;
reg   [31:0] xbit_2_fu_120;
reg   [31:0] loop_count1_2_fu_124;
reg   [31:0] loop_count2_2_fu_128;
reg   [31:0] loop_count3_2_fu_132;
wire   [31:0] tmp_fu_274_p1;
wire   [30:0] tr_fu_292_p4;
wire   [30:0] icmp_fu_302_p1;
wire   [31:0] tmp5_fu_308_p1;
wire   [2:0] Result12_zext_cast_fu_324_p1;
wire   [2:0] tmp6_fu_328_p1;
wire   [0:0] tmp6_fu_328_p2;
wire   [10:0] output_count1_1_cast_fu_344_p1;
wire   [10:0] tmp4_fu_348_p2;
wire   [15:0] tmp7_fu_377_p2;
wire   [13:0] p_cast1_fu_386_p1;
wire   [13:0] tmp8_fu_390_p2;
wire   [0:0] sel_tmp_fu_400_p2;
wire   [31:0] tmp22_cast_fu_396_p1;
wire   [31:0] empty_5_fu_382_p1;
wire   [31:0] sel_tmp2_fu_409_p3;
wire   [11:0] input_count_1_cast8_cast_fu_484_p1;
wire   [11:0] tmp9_fu_488_p1;
wire   [10:0] tr1_fu_510_p2;
wire   [10:0] icmp1_fu_516_p1;
wire   [10:0] tmp15_fu_522_p1;
wire   [1:0] Result5_fu_538_p4;
wire   [1:0] Result4_fu_558_p4;
wire   [1:0] sel_tmp28_v_fu_574_p3;
wire   [31:0] sel_tmp5_fu_582_p1;
wire   [3:0] Result3_fu_528_p4;
wire   [3:0] Result6_fu_548_p4;
wire   [10:0] tmp16_fu_602_p1;
wire   [31:0] tmp14_fu_618_p1;
wire   [0:0] tmp24_fu_627_p2;
wire   [0:0] tmp14_fu_618_p2;
wire   [15:0] Result2_fu_646_p4;
wire   [15:0] Result_fu_656_p4;
wire   [31:0] tmp23_fu_678_p2;
wire   [31:0] sel_tmp4_fu_700_p3;
wire   [31:0] sel_tmp6_fu_714_p1;
wire   [0:0] sel_tmp36_demorgan_fu_724_p2;
wire   [0:0] sel_tmp7_fu_728_p2;
wire   [31:0] tmp17_fu_739_p1;
wire   [31:0] tmp19_fu_745_p2;
wire   [2:0] tmp48_cast_fu_751_p1;
wire   [2:0] tmp20_fu_755_p1;
wire   [31:0] p_neg_fu_769_p2;
wire   [28:0] empty_6_fu_775_p4;
wire   [29:0] p_lshr_cast_fu_785_p1;
wire   [0:0] tmp17_fu_739_p2;
wire   [29:0] p_lshr_f_cast_fu_815_p1;
wire   [29:0] tmp21_fu_818_p3;
wire   [31:0] tmp22_fu_835_p1;
wire   [31:0] tmp22_fu_835_p2;
wire   [31:0] loop_count1_3_v_cast_cast_fu_828_p3;
wire   [0:0] offset_flag_6_demorgan_fu_846_p2;
wire   [0:0] offset_flag_6_fu_850_p2;
wire   [0:0] sel_tmp10_fu_856_p2;
wire   [31:0] tmp18_fu_871_p2;
wire   [31:0] sel_tmp9_fu_876_p3;
wire   [15:0] empty_7_fu_893_p2;
wire   [31:0] p_cast_fu_898_p1;
wire   [31:0] tmp25_fu_902_p2;
wire   [31:0] tmp26_fu_907_p2;
wire   [10:0] output_count1_3_cast_fu_929_p1;
wire   [10:0] tmp11_fu_933_p2;
reg   [3:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st0_fsm_0 = 4'b0000;
parameter    ap_ST_st1_fsm_1 = 4'b0001;
parameter    ap_ST_st2_fsm_2 = 4'b0010;
parameter    ap_ST_st3_fsm_3 = 4'b0011;
parameter    ap_ST_st4_fsm_4 = 4'b0100;
parameter    ap_ST_st5_fsm_5 = 4'b0101;
parameter    ap_ST_st6_fsm_6 = 4'b0110;
parameter    ap_ST_st7_fsm_7 = 4'b0111;
parameter    ap_ST_st8_fsm_8 = 4'b1000;
parameter    ap_ST_st9_fsm_9 = 4'b1001;
parameter    ap_ST_st10_fsm_10 = 4'b1010;
parameter    ap_ST_st11_fsm_11 = 4'b1011;
parameter    ap_ST_st12_fsm_12 = 4'b1100;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_3F = 32'b00000000000000000000000000111111;
parameter    ap_const_lv32_64 = 32'b00000000000000000000000001100100;
parameter    ap_const_lv32_1 = 32'b00000000000000000000000000000001;
parameter    ap_const_lv32_BD = 32'b00000000000000000000000010111101;
parameter    ap_const_lv32_1F = 32'b00000000000000000000000000011111;
parameter    ap_const_lv31_0 = 31'b0000000000000000000000000000000;
parameter    ap_const_lv32_10 = 32'b00000000000000000000000000010000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv11_1 = 11'b00000000001;
parameter    ap_const_lv32_FFFFFFFE = 32'b11111111111111111111111111111110;
parameter    ap_const_lv16_3 = 16'b0000000000000011;
parameter    ap_const_lv14_1 = 14'b00000000000001;
parameter    ap_const_lv32_FFFFFFFD = 32'b11111111111111111111111111111101;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv32_24 = 32'b00000000000000000000000000100100;
parameter    ap_const_lv32_27 = 32'b00000000000000000000000000100111;
parameter    ap_const_lv32_23 = 32'b00000000000000000000000000100011;
parameter    ap_const_lv32_4 = 32'b00000000000000000000000000000100;
parameter    ap_const_lv32_7 = 32'b00000000000000000000000000000111;
parameter    ap_const_lv32_3 = 32'b00000000000000000000000000000011;
parameter    ap_const_lv32_30 = 32'b00000000000000000000000000110000;
parameter    ap_const_lv32_2 = 32'b00000000000000000000000000000010;
parameter    ap_const_lv6_1D = 6'b011101;
parameter    ap_const_lv30_0 = 30'b000000000000000000000000000000;
parameter    ap_const_lv32_1D = 32'b00000000000000000000000000011101;
parameter    ap_const_lv16_1 = 16'b0000000000000001;
parameter    ap_true = 1'b1;


header_removal_packet_out_data_tmp2 #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
packet_out_data_tmp2_U(
    .clk( ap_clk ),
    .address0( packet_out_data_tmp2_address0 ),
    .ce0( packet_out_data_tmp2_ce0 ),
    .we0( packet_out_data_tmp2_we0 ),
    .d0( packet_out_data_tmp2_d0 ),
    .q0( packet_out_data_tmp2_q0 )
);

header_removal_packet_out_data_tmp #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
packet_out_data_tmp_U(
    .clk( ap_clk ),
    .address0( packet_out_data_tmp_address0 ),
    .ce0( packet_out_data_tmp_ce0 ),
    .we0( packet_out_data_tmp_we0 ),
    .d0( packet_out_data_tmp_d0 ),
    .q0( packet_out_data_tmp_q0 )
);



/// ap_CS_fsm assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (tmp_fu_274_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp1_fu_286_p2) & (ap_const_lv1_0 == icmp_fu_302_p2) & ~ap_sig_bdd_54)) begin
        Result1_reg_997 <= {{packet_in_data_dout[ap_const_lv32_1F : ap_const_lv32_10]}};
    end
    if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        if (tmp15_reg_1117) begin
            cc_2_fu_116 <= sel_tmp6_fu_714_p1;
        end else begin
            cc_2_fu_116 <= cc_2_fu_116;
        end

    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == tmp3_fu_438_p2))) begin
        cc_2_fu_116 <= ap_const_lv32_0;
    end
    if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & (ap_const_lv1_0 == tmp13_fu_613_p2) & ~(ap_const_lv1_0 == bothcond_fu_632_p2) & ~ap_sig_bdd_128)) begin
        if (offset_flag_5_fu_112) begin
            extension_header_length_0_in_in_reg_1156 <= Result2_fu_646_p4;
        end else begin
            extension_header_length_0_in_in_reg_1156 <= Result_fu_656_p4;
        end

    end
    if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & (ap_const_lv1_0 == tmp13_fu_613_p2) & ~(ap_const_lv1_0 == bothcond_fu_632_p2) & ~ap_sig_bdd_128)) begin
        extension_header_length_cast_reg_1161 <= extension_header_length_0_in_in_fu_666_p3[0:0];
    end
    if ((ap_ST_st4_fsm_4 == ap_CS_fsm)) begin
        indvar_next1_reg_1023 <= (input_count_1_reg_210 + ap_const_lv11_1);
    end
    if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        indvar_next2_reg_1095 <= (input_count_2_reg_223 + ap_const_lv11_1);
    end
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~ap_sig_bdd_54)) begin
        indvar_next_reg_979 <= (input_count_reg_197 + ap_const_lv32_1);
    end
    if (((ap_ST_st12_fsm_12 == ap_CS_fsm) | ((ap_ST_st11_fsm_11 == ap_CS_fsm) & (ap_const_lv1_0 == tmp9_reg_1081) & ~ap_sig_bdd_177))) begin
        input_count_1_reg_210 <= indvar_next1_reg_1023;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~ap_sig_bdd_54 & (~(tmp_fu_274_p2 == ap_const_lv1_0) | ~(ap_const_lv1_0 == tmp1_fu_286_p2)))) begin
        input_count_1_reg_210 <= ap_const_lv11_0;
    end
    if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        input_count_2_cast_reg_1085[0] <= input_count_2_cast_fu_494_p1[0];
        input_count_2_cast_reg_1085[1] <= input_count_2_cast_fu_494_p1[1];
        input_count_2_cast_reg_1085[2] <= input_count_2_cast_fu_494_p1[2];
        input_count_2_cast_reg_1085[3] <= input_count_2_cast_fu_494_p1[3];
        input_count_2_cast_reg_1085[4] <= input_count_2_cast_fu_494_p1[4];
        input_count_2_cast_reg_1085[5] <= input_count_2_cast_fu_494_p1[5];
        input_count_2_cast_reg_1085[6] <= input_count_2_cast_fu_494_p1[6];
        input_count_2_cast_reg_1085[7] <= input_count_2_cast_fu_494_p1[7];
        input_count_2_cast_reg_1085[8] <= input_count_2_cast_fu_494_p1[8];
        input_count_2_cast_reg_1085[9] <= input_count_2_cast_fu_494_p1[9];
        input_count_2_cast_reg_1085[10] <= input_count_2_cast_fu_494_p1[10];
    end
    if ((((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & (ap_const_lv1_0 == tmp13_fu_613_p2) & (ap_const_lv1_0 == bothcond_fu_632_p2) & (ap_const_lv1_0 == tmp27_fu_641_p2) & ~ap_sig_bdd_128) | ((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & (ap_const_lv1_0 == tmp13_fu_613_p2) & (ap_const_lv1_0 == bothcond_fu_632_p2) & ~(ap_const_lv1_0 == tmp27_fu_641_p2) & ~ap_sig_bdd_128) | (ap_ST_st10_fsm_10 == ap_CS_fsm) | ((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & ~(ap_const_lv1_0 == tmp13_fu_613_p2) & ~ap_sig_bdd_128) | (ap_ST_st9_fsm_9 == ap_CS_fsm))) begin
        input_count_2_reg_223 <= indvar_next2_reg_1095;
    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == tmp3_fu_438_p2))) begin
        input_count_2_reg_223 <= ap_const_lv11_0;
    end
    if ((ap_ST_st3_fsm_3 == ap_CS_fsm)) begin
        input_count_reg_197 <= indvar_next_reg_979;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (tmp_fu_274_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp1_fu_286_p2) & ~ap_sig_bdd_54 & ~(ap_const_lv1_0 == icmp_fu_302_p2))) begin
        input_count_reg_197 <= (input_count_reg_197 + ap_const_lv32_1);
    end else if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        input_count_reg_197 <= ap_const_lv32_0;
    end
    if ((ap_ST_st9_fsm_9 == ap_CS_fsm)) begin
        if (tmp16_reg_1135) begin
            loop_count1_2_fu_124 <= sel_tmp9_fu_876_p3;
        end else begin
            loop_count1_2_fu_124 <= loop_count_reg_1166;
        end

    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == tmp3_fu_438_p2))) begin
        loop_count1_2_fu_124 <= ap_const_lv32_0;
    end
    if (((tmp16_reg_1135 == ap_const_lv1_1) & (ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == sel_tmp8_reg_1199))) begin
        loop_count1_3_reg_1205 <= (tmp22_fu_835_p2 + loop_count1_3_v_cast_cast_fu_828_p3);
    end
    if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & ~(ap_const_lv1_0 == tmp13_fu_613_p2) & ~ap_sig_bdd_128)) begin
        if (tmp14_fu_618_p2) begin
            loop_count2_2_fu_128 <= tmp23_fu_678_p2;
        end else begin
            loop_count2_2_fu_128 <= loop_count2_2_fu_128;
        end

    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == tmp3_fu_438_p2))) begin
        loop_count2_2_fu_128 <= ap_const_lv32_0;
    end
    if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & ~ap_sig_bdd_128)) begin
        loop_count2_2_load_reg_1145 <= loop_count2_2_fu_128;
    end
    if ((ap_ST_st10_fsm_10 == ap_CS_fsm)) begin
        if (extension_header_length_cast_reg_1161) begin
            loop_count3_2_fu_132 <= tmp26_fu_907_p2;
        end else begin
            loop_count3_2_fu_132 <= tmp25_fu_902_p2;
        end

    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == tmp3_fu_438_p2))) begin
        loop_count3_2_fu_132 <= ap_const_lv32_0;
    end
    if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        if (tmp15_reg_1117) begin
            loop_count_reg_1166 <= sel_tmp4_fu_700_p3;
        end else begin
            loop_count_reg_1166 <= loop_count1_2_fu_124;
        end

    end
    if ((ap_ST_st3_fsm_3 == ap_CS_fsm)) begin
        offset_flag_2_fu_88 <= (sel_tmp1_reg_1002 | sel_tmp_fu_400_p2);
    end else if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        offset_flag_2_fu_88 <= ap_const_lv1_0;
    end
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~ap_sig_bdd_54)) begin
        offset_flag_2_load_reg_970 <= offset_flag_2_fu_88;
    end
    if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        offset_flag_3_reg_1173 <= (offset_flag_5_load_reg_1112 & sel_tmp7_fu_728_p2);
    end
    if ((ap_ST_st8_fsm_8 == ap_CS_fsm)) begin
        offset_flag_5_fu_112 <= (offset_flag_3_reg_1173 | sel_tmp10_fu_856_p2);
    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == tmp3_fu_438_p2))) begin
        offset_flag_5_fu_112 <= offset_flag_2_load_reg_970;
    end
    if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & (ap_const_lv1_0 == icmp1_fu_516_p2) & ~ap_sig_bdd_128)) begin
        offset_flag_5_load_reg_1112 <= offset_flag_5_fu_112;
    end
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (tmp_fu_274_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp1_fu_286_p2) & ~ap_sig_bdd_54 & ~(ap_const_lv1_0 == icmp_fu_302_p2))) begin
        output_count1_1_fu_92[0] <= tmp11_cast_fu_354_p1[0];
        output_count1_1_fu_92[1] <= tmp11_cast_fu_354_p1[1];
        output_count1_1_fu_92[2] <= tmp11_cast_fu_354_p1[2];
        output_count1_1_fu_92[3] <= tmp11_cast_fu_354_p1[3];
        output_count1_1_fu_92[4] <= tmp11_cast_fu_354_p1[4];
        output_count1_1_fu_92[5] <= tmp11_cast_fu_354_p1[5];
        output_count1_1_fu_92[6] <= tmp11_cast_fu_354_p1[6];
        output_count1_1_fu_92[7] <= tmp11_cast_fu_354_p1[7];
        output_count1_1_fu_92[8] <= tmp11_cast_fu_354_p1[8];
        output_count1_1_fu_92[9] <= tmp11_cast_fu_354_p1[9];
        output_count1_1_fu_92[10] <= tmp11_cast_fu_354_p1[10];
    end else if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        output_count1_1_fu_92[0] <= 1'b0;
        output_count1_1_fu_92[1] <= 1'b0;
        output_count1_1_fu_92[2] <= 1'b0;
        output_count1_1_fu_92[3] <= 1'b0;
        output_count1_1_fu_92[4] <= 1'b0;
        output_count1_1_fu_92[5] <= 1'b0;
        output_count1_1_fu_92[6] <= 1'b0;
        output_count1_1_fu_92[7] <= 1'b0;
        output_count1_1_fu_92[8] <= 1'b0;
        output_count1_1_fu_92[9] <= 1'b0;
        output_count1_1_fu_92[10] <= 1'b0;
    end
    if ((ap_ST_st12_fsm_12 == ap_CS_fsm)) begin
        output_count1_3_fu_108[0] <= tmp19_cast_fu_939_p1[0];
        output_count1_3_fu_108[1] <= tmp19_cast_fu_939_p1[1];
        output_count1_3_fu_108[2] <= tmp19_cast_fu_939_p1[2];
        output_count1_3_fu_108[3] <= tmp19_cast_fu_939_p1[3];
        output_count1_3_fu_108[4] <= tmp19_cast_fu_939_p1[4];
        output_count1_3_fu_108[5] <= tmp19_cast_fu_939_p1[5];
        output_count1_3_fu_108[6] <= tmp19_cast_fu_939_p1[6];
        output_count1_3_fu_108[7] <= tmp19_cast_fu_939_p1[7];
        output_count1_3_fu_108[8] <= tmp19_cast_fu_939_p1[8];
        output_count1_3_fu_108[9] <= tmp19_cast_fu_939_p1[9];
        output_count1_3_fu_108[10] <= tmp19_cast_fu_939_p1[10];
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~ap_sig_bdd_54 & (~(tmp_fu_274_p2 == ap_const_lv1_0) | ~(ap_const_lv1_0 == tmp1_fu_286_p2)))) begin
        output_count1_3_fu_108[0] <= 1'b0;
        output_count1_3_fu_108[1] <= 1'b0;
        output_count1_3_fu_108[2] <= 1'b0;
        output_count1_3_fu_108[3] <= 1'b0;
        output_count1_3_fu_108[4] <= 1'b0;
        output_count1_3_fu_108[5] <= 1'b0;
        output_count1_3_fu_108[6] <= 1'b0;
        output_count1_3_fu_108[7] <= 1'b0;
        output_count1_3_fu_108[8] <= 1'b0;
        output_count1_3_fu_108[9] <= 1'b0;
        output_count1_3_fu_108[10] <= 1'b0;
    end
    if (((ap_ST_st7_fsm_7 == ap_CS_fsm) & (tmp16_reg_1135 == ap_const_lv1_1))) begin
        p_cast2_reg_1194 <= {{cc_fu_717_p3[ap_const_lv32_1D : ap_const_lv32_1]}};
    end
    if (((ap_ST_st7_fsm_7 == ap_CS_fsm) & (tmp16_reg_1135 == ap_const_lv1_1))) begin
        p_cond_reg_1184 <= cc_fu_717_p3[ap_const_lv6_1D];
    end
    if (((ap_ST_st7_fsm_7 == ap_CS_fsm) & (tmp16_reg_1135 == ap_const_lv1_1))) begin
        p_neg_t_reg_1189 <= (ap_const_lv30_0 - p_lshr_cast_fu_785_p1);
    end
    if (((ap_ST_st11_fsm_11 == ap_CS_fsm) & ~ap_sig_bdd_177)) begin
        packet_out_data_tmp_load_reg_1210 <= packet_out_data_tmp_q0;
    end
    if ((ap_ST_st3_fsm_3 == ap_CS_fsm)) begin
        if (sel_tmp1_reg_1002) begin
            packet_size_2_fu_96 <= empty_5_fu_382_p1;
        end else begin
            packet_size_2_fu_96 <= sel_tmp2_fu_409_p3;
        end

    end else if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        packet_size_2_fu_96 <= ap_const_lv32_64;
    end
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (tmp_fu_274_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp1_fu_286_p2) & (ap_const_lv1_0 == icmp_fu_302_p2) & ~ap_sig_bdd_54)) begin
        sel_tmp1_reg_1002 <= (tmp5_fu_308_p2 & tmp6_fu_328_p2);
    end
    if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & (ap_const_lv1_0 == icmp1_fu_516_p2) & ~ap_sig_bdd_128)) begin
        if (sel_tmp3_fu_568_p2) begin
            sel_tmp32_v_reg_1130 <= Result3_fu_528_p4;
        end else begin
            sel_tmp32_v_reg_1130 <= Result6_fu_548_p4;
        end

    end
    if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & (ap_const_lv1_0 == icmp1_fu_516_p2) & ~ap_sig_bdd_128)) begin
        sel_tmp3_reg_1124 <= (tmp15_fu_522_p2 & offset_flag_5_fu_112);
    end
    if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        sel_tmp8_reg_1199 <= (tmp16_reg_1135 & tmp17_fu_739_p2);
    end
    if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == tmp3_fu_438_p2))) begin
        tmp10_reg_1071 <= (packet_size_2_fu_96 + ap_const_lv32_FFFFFFFD);
    end
    if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & (ap_const_lv1_0 == icmp1_fu_516_p2) & ~ap_sig_bdd_128)) begin
        tmp15_reg_1117 <= (input_count_2_reg_223 == tmp15_fu_522_p1? 1'b1: 1'b0);
    end
    if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & (ap_const_lv1_0 == icmp1_fu_516_p2) & ~ap_sig_bdd_128)) begin
        tmp16_reg_1135 <= (input_count_2_reg_223 == tmp16_fu_602_p1? 1'b1: 1'b0);
    end
    if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        tmp20_reg_1178 <= (tmp48_cast_fu_751_p1 == tmp20_fu_755_p1? 1'b1: 1'b0);
    end
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~ap_sig_bdd_54 & (~(tmp_fu_274_p2 == ap_const_lv1_0) | ~(ap_const_lv1_0 == tmp1_fu_286_p2)))) begin
        tmp2_reg_1015 <= (packet_size_2_fu_96 + ap_const_lv32_FFFFFFFE);
    end
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (tmp_fu_274_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp1_fu_286_p2) & (ap_const_lv1_0 == icmp_fu_302_p2) & ~ap_sig_bdd_54)) begin
        tmp5_reg_991 <= (input_count_reg_197 == tmp5_fu_308_p1? 1'b1: 1'b0);
    end
    if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp3_fu_438_p2))) begin
        tmp9_reg_1081 <= ($signed(input_count_1_cast8_cast_fu_484_p1) > $signed(tmp9_fu_488_p1)? 1'b1: 1'b0);
    end
    if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & (ap_const_lv1_0 == icmp1_fu_516_p2) & ~ap_sig_bdd_128)) begin
        if (tmp15_fu_522_p2) begin
            xbit_2_fu_120 <= sel_tmp5_fu_582_p1;
        end else begin
            xbit_2_fu_120 <= xbit_2_fu_120;
        end

    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == tmp3_fu_438_p2))) begin
        xbit_2_fu_120 <= ap_const_lv32_0;
    end
end

/// ap_NS_fsm assign process. ///
always @ (ap_start or ap_CS_fsm or tmp_fu_274_p2 or tmp1_fu_286_p2 or icmp_fu_302_p2 or ap_sig_bdd_54 or tmp3_fu_438_p2 or tmp9_reg_1081 or tmp12_fu_499_p2 or icmp1_fu_516_p2 or tmp13_fu_613_p2 or bothcond_fu_632_p2 or ap_sig_bdd_128 or ap_sig_bdd_177)
begin
    if (((ap_ST_st11_fsm_11 == ap_CS_fsm) & ~ap_sig_bdd_177 & ~(ap_const_lv1_0 == tmp9_reg_1081))) begin
        ap_NS_fsm = ap_ST_st12_fsm_12;
    end else if ((ap_ST_st8_fsm_8 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st9_fsm_9;
    end else if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st8_fsm_8;
    end else if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & (ap_const_lv1_0 == tmp13_fu_613_p2) & ~(ap_const_lv1_0 == bothcond_fu_632_p2) & ~ap_sig_bdd_128)) begin
        ap_NS_fsm = ap_ST_st10_fsm_10;
    end else if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & (ap_const_lv1_0 == icmp1_fu_516_p2) & ~ap_sig_bdd_128)) begin
        ap_NS_fsm = ap_ST_st7_fsm_7;
    end else if (((ap_ST_st5_fsm_5 == ap_CS_fsm) & (ap_const_lv1_0 == tmp12_fu_499_p2) & ~(ap_const_logic_1 == ap_start))) begin
        ap_NS_fsm = ap_ST_st0_fsm_0;
    end else if (((ap_ST_st5_fsm_5 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp12_fu_499_p2))) begin
        ap_NS_fsm = ap_ST_st6_fsm_6;
    end else if ((((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == tmp3_fu_438_p2)) | (ap_ST_st10_fsm_10 == ap_CS_fsm) | (ap_ST_st9_fsm_9 == ap_CS_fsm) | ((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~ap_sig_bdd_128 & ((~(ap_const_lv1_0 == icmp1_fu_516_p2) & ~(ap_const_lv1_0 == tmp13_fu_613_p2)) | (~(ap_const_lv1_0 == icmp1_fu_516_p2) & (ap_const_lv1_0 == bothcond_fu_632_p2)))))) begin
        ap_NS_fsm = ap_ST_st5_fsm_5;
    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp3_fu_438_p2))) begin
        ap_NS_fsm = ap_ST_st11_fsm_11;
    end else if ((((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~ap_sig_bdd_54 & (~(tmp_fu_274_p2 == ap_const_lv1_0) | ~(ap_const_lv1_0 == tmp1_fu_286_p2))) | (ap_ST_st12_fsm_12 == ap_CS_fsm) | ((ap_ST_st11_fsm_11 == ap_CS_fsm) & (ap_const_lv1_0 == tmp9_reg_1081) & ~ap_sig_bdd_177))) begin
        ap_NS_fsm = ap_ST_st4_fsm_4;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (tmp_fu_274_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp1_fu_286_p2) & (ap_const_lv1_0 == icmp_fu_302_p2) & ~ap_sig_bdd_54)) begin
        ap_NS_fsm = ap_ST_st3_fsm_3;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & (tmp_fu_274_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp1_fu_286_p2) & ~ap_sig_bdd_54 & ~(ap_const_lv1_0 == icmp_fu_302_p2)) | (ap_ST_st3_fsm_3 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st2_fsm_2;
    end else if ((((ap_ST_st0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_start)) | ((ap_ST_st5_fsm_5 == ap_CS_fsm) & (ap_const_lv1_0 == tmp12_fu_499_p2) & (ap_const_logic_1 == ap_start)))) begin
        ap_NS_fsm = ap_ST_st1_fsm_1;
    end else begin
        ap_NS_fsm = ap_CS_fsm;
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm or tmp12_fu_499_p2)
begin
    if (((ap_ST_st5_fsm_5 == ap_CS_fsm) & (ap_const_lv1_0 == tmp12_fu_499_p2))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st0_fsm_0 == ap_CS_fsm)) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// packet_in_data_read assign process. ///
always @ (ap_CS_fsm or tmp_fu_274_p2 or ap_sig_bdd_54)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (tmp_fu_274_p2 == ap_const_lv1_0) & ~ap_sig_bdd_54)) begin
        packet_in_data_read = ap_const_logic_1;
    end else begin
        packet_in_data_read = ap_const_logic_0;
    end
end

/// packet_out_data_aux_din assign process. ///
always @ (ap_CS_fsm or packet_in_data_dout or tmp_fu_274_p2 or tmp1_fu_286_p2 or icmp_fu_302_p2 or tmp9_reg_1081 or icmp1_fu_516_p2 or tmp13_fu_613_p2 or bothcond_fu_632_p2 or tmp27_fu_641_p2 or packet_out_data_tmp_q0 or packet_out_data_tmp2_q0)
begin
    if (((ap_ST_st11_fsm_11 == ap_CS_fsm) & (ap_const_lv1_0 == tmp9_reg_1081))) begin
        packet_out_data_aux_din = packet_out_data_tmp_q0;
    end else if ((((ap_ST_st6_fsm_6 == ap_CS_fsm) & (ap_const_lv1_0 == icmp1_fu_516_p2)) | ((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & (ap_const_lv1_0 == tmp13_fu_613_p2) & (ap_const_lv1_0 == bothcond_fu_632_p2) & ~(ap_const_lv1_0 == tmp27_fu_641_p2)) | ((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & (ap_const_lv1_0 == tmp13_fu_613_p2) & ~(ap_const_lv1_0 == bothcond_fu_632_p2)) | ((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & ~(ap_const_lv1_0 == tmp13_fu_613_p2)))) begin
        packet_out_data_aux_din = packet_out_data_tmp2_q0;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (tmp_fu_274_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp1_fu_286_p2) & (ap_const_lv1_0 == icmp_fu_302_p2))) begin
        packet_out_data_aux_din = packet_in_data_dout;
    end else begin
        packet_out_data_aux_din = packet_in_data_dout;
    end
end

/// packet_out_data_aux_write assign process. ///
always @ (ap_CS_fsm or tmp_fu_274_p2 or tmp1_fu_286_p2 or icmp_fu_302_p2 or ap_sig_bdd_54 or tmp9_reg_1081 or icmp1_fu_516_p2 or tmp13_fu_613_p2 or bothcond_fu_632_p2 or tmp27_fu_641_p2 or ap_sig_bdd_128 or ap_sig_bdd_177)
begin
    if ((((ap_ST_st2_fsm_2 == ap_CS_fsm) & (tmp_fu_274_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp1_fu_286_p2) & (ap_const_lv1_0 == icmp_fu_302_p2) & ~ap_sig_bdd_54) | ((ap_ST_st6_fsm_6 == ap_CS_fsm) & (ap_const_lv1_0 == icmp1_fu_516_p2) & ~ap_sig_bdd_128) | ((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & (ap_const_lv1_0 == tmp13_fu_613_p2) & ~(ap_const_lv1_0 == bothcond_fu_632_p2) & ~ap_sig_bdd_128) | ((ap_ST_st11_fsm_11 == ap_CS_fsm) & (ap_const_lv1_0 == tmp9_reg_1081) & ~ap_sig_bdd_177) | ((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & (ap_const_lv1_0 == tmp13_fu_613_p2) & (ap_const_lv1_0 == bothcond_fu_632_p2) & ~(ap_const_lv1_0 == tmp27_fu_641_p2) & ~ap_sig_bdd_128) | ((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & ~(ap_const_lv1_0 == tmp13_fu_613_p2) & ~ap_sig_bdd_128))) begin
        packet_out_data_aux_write = ap_const_logic_1;
    end else begin
        packet_out_data_aux_write = ap_const_logic_0;
    end
end

/// packet_out_data_tmp2_address0 assign process. ///
always @ (ap_CS_fsm or input_count_2_cast_fu_494_p1 or tmp12_fu_499_p2 or output_count1_3_fu_108)
begin
    if ((ap_ST_st12_fsm_12 == ap_CS_fsm)) begin
        packet_out_data_tmp2_address0 = output_count1_3_fu_108;
    end else if (((ap_ST_st5_fsm_5 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp12_fu_499_p2))) begin
        packet_out_data_tmp2_address0 = input_count_2_cast_fu_494_p1;
    end else begin
        packet_out_data_tmp2_address0 = output_count1_3_fu_108;
    end
end

/// packet_out_data_tmp2_ce0 assign process. ///
always @ (ap_CS_fsm or tmp12_fu_499_p2)
begin
    if ((((ap_ST_st5_fsm_5 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp12_fu_499_p2)) | (ap_ST_st12_fsm_12 == ap_CS_fsm))) begin
        packet_out_data_tmp2_ce0 = ap_const_logic_1;
    end else begin
        packet_out_data_tmp2_ce0 = ap_const_logic_0;
    end
end

/// packet_out_data_tmp2_we0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st12_fsm_12 == ap_CS_fsm)) begin
        packet_out_data_tmp2_we0 = ap_const_logic_1;
    end else begin
        packet_out_data_tmp2_we0 = ap_const_logic_0;
    end
end

/// packet_out_data_tmp_address0 assign process. ///
always @ (ap_CS_fsm or tmp_fu_274_p2 or tmp1_fu_286_p2 or icmp_fu_302_p2 or ap_sig_bdd_54 or tmp3_fu_438_p2 or input_count_1_cast_fu_433_p1 or output_count1_1_fu_92)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (tmp_fu_274_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp1_fu_286_p2) & ~ap_sig_bdd_54 & ~(ap_const_lv1_0 == icmp_fu_302_p2))) begin
        packet_out_data_tmp_address0 = output_count1_1_fu_92;
    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp3_fu_438_p2))) begin
        packet_out_data_tmp_address0 = input_count_1_cast_fu_433_p1;
    end else begin
        packet_out_data_tmp_address0 = output_count1_1_fu_92;
    end
end

/// packet_out_data_tmp_ce0 assign process. ///
always @ (ap_CS_fsm or tmp_fu_274_p2 or tmp1_fu_286_p2 or icmp_fu_302_p2 or ap_sig_bdd_54 or tmp3_fu_438_p2)
begin
    if ((((ap_ST_st4_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp3_fu_438_p2)) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & (tmp_fu_274_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp1_fu_286_p2) & ~ap_sig_bdd_54 & ~(ap_const_lv1_0 == icmp_fu_302_p2)))) begin
        packet_out_data_tmp_ce0 = ap_const_logic_1;
    end else begin
        packet_out_data_tmp_ce0 = ap_const_logic_0;
    end
end

/// packet_out_data_tmp_we0 assign process. ///
always @ (ap_CS_fsm or tmp_fu_274_p2 or tmp1_fu_286_p2 or icmp_fu_302_p2 or ap_sig_bdd_54)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (tmp_fu_274_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp1_fu_286_p2) & ~ap_sig_bdd_54 & ~(ap_const_lv1_0 == icmp_fu_302_p2))) begin
        packet_out_data_tmp_we0 = ap_const_logic_1;
    end else begin
        packet_out_data_tmp_we0 = ap_const_logic_0;
    end
end

/// packet_out_data_write assign process. ///
always @ (ap_CS_fsm or icmp1_fu_516_p2 or tmp13_fu_613_p2 or bothcond_fu_632_p2 or tmp27_fu_641_p2 or ap_sig_bdd_128)
begin
    if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & (ap_const_lv1_0 == tmp13_fu_613_p2) & (ap_const_lv1_0 == bothcond_fu_632_p2) & (ap_const_lv1_0 == tmp27_fu_641_p2) & ~ap_sig_bdd_128)) begin
        packet_out_data_write = ap_const_logic_1;
    end else begin
        packet_out_data_write = ap_const_logic_0;
    end
end
assign Result12_zext_cast_fu_324_p1 = Result1_fu_314_p4[2:0];
assign Result1_fu_314_p4 = {{packet_in_data_dout[ap_const_lv32_1F : ap_const_lv32_10]}};
assign Result2_fu_646_p4 = {{packet_out_data_tmp2_q0[ap_const_lv32_3F : ap_const_lv32_30]}};
assign Result3_fu_528_p4 = {{packet_out_data_tmp2_q0[ap_const_lv32_27 : ap_const_lv32_24]}};
assign Result4_fu_558_p4 = {{packet_out_data_tmp2_q0[ap_const_lv32_4 : ap_const_lv32_3]}};
assign Result5_fu_538_p4 = {{packet_out_data_tmp2_q0[ap_const_lv32_24 : ap_const_lv32_23]}};
assign Result6_fu_548_p4 = {{packet_out_data_tmp2_q0[ap_const_lv32_7 : ap_const_lv32_4]}};
assign Result_fu_656_p4 = {{packet_out_data_tmp2_q0[ap_const_lv32_1F : ap_const_lv32_10]}};

/// ap_sig_bdd_128 assign process. ///
always @ (packet_out_data_aux_full_n or packet_out_data_full_n or icmp1_fu_516_p2 or tmp13_fu_613_p2 or bothcond_fu_632_p2 or tmp27_fu_641_p2)
begin
    ap_sig_bdd_128 = (((packet_out_data_aux_full_n == ap_const_logic_0) & (ap_const_lv1_0 == icmp1_fu_516_p2)) | ((packet_out_data_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & (ap_const_lv1_0 == tmp13_fu_613_p2) & (ap_const_lv1_0 == bothcond_fu_632_p2) & (ap_const_lv1_0 == tmp27_fu_641_p2)) | ((packet_out_data_aux_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & (ap_const_lv1_0 == tmp13_fu_613_p2) & (ap_const_lv1_0 == bothcond_fu_632_p2) & ~(ap_const_lv1_0 == tmp27_fu_641_p2)) | ((packet_out_data_aux_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & (ap_const_lv1_0 == tmp13_fu_613_p2) & ~(ap_const_lv1_0 == bothcond_fu_632_p2)) | ((packet_out_data_aux_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == icmp1_fu_516_p2) & ~(ap_const_lv1_0 == tmp13_fu_613_p2)));
end

/// ap_sig_bdd_177 assign process. ///
always @ (packet_out_data_aux_full_n or tmp9_reg_1081)
begin
    ap_sig_bdd_177 = ((packet_out_data_aux_full_n == ap_const_logic_0) & (ap_const_lv1_0 == tmp9_reg_1081));
end

/// ap_sig_bdd_54 assign process. ///
always @ (packet_in_data_empty_n or packet_out_data_aux_full_n or tmp_fu_274_p2 or tmp1_fu_286_p2 or icmp_fu_302_p2)
begin
    ap_sig_bdd_54 = (((packet_in_data_empty_n == ap_const_logic_0) & (tmp_fu_274_p2 == ap_const_lv1_0)) | ((tmp_fu_274_p2 == ap_const_lv1_0) & (packet_out_data_aux_full_n == ap_const_logic_0) & (ap_const_lv1_0 == tmp1_fu_286_p2) & (ap_const_lv1_0 == icmp_fu_302_p2)));
end
assign bothcond_fu_632_p2 = (tmp24_fu_627_p2 & tmp14_fu_618_p2);
assign cc_fu_717_p3 = ((tmp15_reg_1117)? sel_tmp6_fu_714_p1: cc_2_fu_116);
assign empty_5_fu_382_p1 = {{16{1'b0}}, {tmp7_fu_377_p2}};
assign empty_6_fu_775_p4 = {{p_neg_fu_769_p2[ap_const_lv32_1F : ap_const_lv32_3]}};
assign empty_7_fu_893_p2 = extension_header_length_0_in_in_reg_1156 >> ap_const_lv16_1;
assign extension_header_length_0_in_in_fu_666_p3 = ((offset_flag_5_fu_112)? Result2_fu_646_p4: Result_fu_656_p4);
assign icmp1_fu_516_p1 = ap_const_lv11_0;
assign icmp1_fu_516_p2 = ($signed(tr1_fu_510_p2) > $signed(icmp1_fu_516_p1)? 1'b1: 1'b0);
assign icmp_fu_302_p1 = ap_const_lv31_0;
assign icmp_fu_302_p2 = ($signed(tr_fu_292_p4) > $signed(icmp_fu_302_p1)? 1'b1: 1'b0);
assign input_count_1_cast8_cast_fu_484_p1 = {{1{1'b0}}, {input_count_1_reg_210}};
assign input_count_1_cast_fu_433_p1 = {{21{1'b0}}, {input_count_1_reg_210}};
assign input_count_2_cast_fu_494_p1 = {{21{1'b0}}, {input_count_2_reg_223}};
assign loop_count1_3_v_cast_cast_fu_828_p3 = ((tmp20_reg_1178)? ap_const_lv32_2: ap_const_lv32_3);
assign offset_flag_6_demorgan_fu_846_p2 = (sel_tmp8_reg_1199 | tmp20_reg_1178);
assign offset_flag_6_fu_850_p2 = (offset_flag_6_demorgan_fu_846_p2 ^ ap_const_lv1_1);
assign output_count1_1_cast_fu_344_p1 = output_count1_1_fu_92[10:0];
assign output_count1_3_cast_fu_929_p1 = output_count1_3_fu_108[10:0];
assign p_cast1_fu_386_p1 = tmp7_fu_377_p2[13:0];
assign p_cast_fu_898_p1 = {{16{1'b0}}, {empty_7_fu_893_p2}};
assign p_lshr_cast_fu_785_p1 = {{1{1'b0}}, {empty_6_fu_775_p4}};
assign p_lshr_f_cast_fu_815_p1 = {{1{1'b0}}, {p_cast2_reg_1194}};
assign p_neg_fu_769_p2 = (ap_const_lv32_0 - tmp19_fu_745_p2);
assign packet_out_data_din = packet_out_data_tmp2_q0;
assign packet_out_data_tmp2_d0 = packet_out_data_tmp_load_reg_1210;
assign packet_out_data_tmp_d0 = packet_in_data_dout;
assign sel_tmp10_fu_856_p2 = (tmp16_reg_1135 & offset_flag_6_fu_850_p2);
assign sel_tmp28_v_fu_574_p3 = ((sel_tmp3_fu_568_p2)? Result5_fu_538_p4: Result4_fu_558_p4);
assign sel_tmp2_fu_409_p3 = ((tmp5_reg_991)? tmp22_cast_fu_396_p1: packet_size_2_fu_96);
assign sel_tmp36_demorgan_fu_724_p2 = (tmp15_reg_1117 & sel_tmp3_reg_1124);
assign sel_tmp3_fu_568_p2 = (tmp15_fu_522_p2 & offset_flag_5_fu_112);
assign sel_tmp4_fu_700_p3 = ((sel_tmp3_reg_1124)? ap_const_lv32_1: loop_count1_2_fu_124);
assign sel_tmp5_fu_582_p1 = {{30{1'b0}}, {sel_tmp28_v_fu_574_p3}};
assign sel_tmp6_fu_714_p1 = {{28{1'b0}}, {sel_tmp32_v_reg_1130}};
assign sel_tmp7_fu_728_p2 = (sel_tmp36_demorgan_fu_724_p2 ^ ap_const_lv1_1);
assign sel_tmp9_fu_876_p3 = ((sel_tmp8_reg_1199)? tmp18_fu_871_p2: loop_count1_3_reg_1205);
assign sel_tmp_fu_400_p2 = (offset_flag_2_load_reg_970 | tmp5_reg_991);
assign tmp11_cast_fu_354_p1 = {{21{1'b0}}, {tmp4_fu_348_p2}};
assign tmp11_fu_933_p2 = (output_count1_3_cast_fu_929_p1 + ap_const_lv11_1);
assign tmp12_fu_499_p2 = ($signed(tmp10_reg_1071) > $signed(input_count_2_cast_fu_494_p1)? 1'b1: 1'b0);
assign tmp13_fu_613_p2 = ($signed(input_count_2_cast_reg_1085) < $signed(loop_count1_2_fu_124)? 1'b1: 1'b0);
assign tmp14_fu_618_p1 = ap_const_lv32_1;
assign tmp14_fu_618_p2 = (xbit_2_fu_120 == tmp14_fu_618_p1? 1'b1: 1'b0);
assign tmp15_fu_522_p1 = ap_const_lv11_0;
assign tmp15_fu_522_p2 = (input_count_2_reg_223 == tmp15_fu_522_p1? 1'b1: 1'b0);
assign tmp16_fu_602_p1 = ap_const_lv11_1;
assign tmp17_fu_739_p1 = ap_const_lv32_0;
assign tmp17_fu_739_p2 = (cc_fu_717_p3 == tmp17_fu_739_p1? 1'b1: 1'b0);
assign tmp18_fu_871_p2 = (loop_count_reg_1166 + ap_const_lv32_2);
assign tmp19_cast_fu_939_p1 = {{21{1'b0}}, {tmp11_fu_933_p2}};
assign tmp19_fu_745_p2 = cc_fu_717_p3 << ap_const_lv32_2;
assign tmp1_fu_286_p2 = (input_count_reg_197 == packet_size_2_fu_96? 1'b1: 1'b0);
assign tmp20_fu_755_p1 = ap_const_lv3_0;
assign tmp21_fu_818_p3 = ((p_cond_reg_1184)? p_neg_t_reg_1189: p_lshr_f_cast_fu_815_p1);
assign tmp22_cast_fu_396_p1 = {{18{1'b0}}, {tmp8_fu_390_p2}};
assign tmp22_fu_835_p1 = {{2{tmp21_fu_818_p3[29]}}, {tmp21_fu_818_p3}};
assign tmp22_fu_835_p2 = (loop_count_reg_1166 + tmp22_fu_835_p1);
assign tmp23_fu_678_p2 = (loop_count1_2_fu_124 + ap_const_lv32_1);
assign tmp24_fu_627_p2 = ($signed(input_count_2_cast_reg_1085) < $signed(loop_count2_2_fu_128)? 1'b1: 1'b0);
assign tmp25_fu_902_p2 = (loop_count2_2_load_reg_1145 + p_cast_fu_898_p1);
assign tmp26_fu_907_p2 = (tmp25_fu_902_p2 + ap_const_lv32_1);
assign tmp27_fu_641_p2 = ($signed(input_count_2_cast_reg_1085) < $signed(loop_count3_2_fu_132)? 1'b1: 1'b0);
assign tmp3_fu_438_p2 = ($signed(tmp2_reg_1015) > $signed(input_count_1_cast_fu_433_p1)? 1'b1: 1'b0);
assign tmp48_cast_fu_751_p1 = tmp19_fu_745_p2[2:0];
assign tmp4_fu_348_p2 = (output_count1_1_cast_fu_344_p1 + ap_const_lv11_1);
assign tmp5_fu_308_p1 = ap_const_lv32_0;
assign tmp5_fu_308_p2 = (input_count_reg_197 == tmp5_fu_308_p1? 1'b1: 1'b0);
assign tmp6_fu_328_p1 = ap_const_lv3_0;
assign tmp6_fu_328_p2 = (Result12_zext_cast_fu_324_p1 == tmp6_fu_328_p1? 1'b1: 1'b0);
assign tmp7_fu_377_p2 = Result1_reg_997 >> ap_const_lv16_3;
assign tmp8_fu_390_p2 = (p_cast1_fu_386_p1 + ap_const_lv14_1);
assign tmp9_fu_488_p1 = ap_const_lv12_0;
assign tmp_fu_274_p1 = ap_const_lv32_BD;
assign tmp_fu_274_p2 = ($signed(input_count_reg_197) > $signed(tmp_fu_274_p1)? 1'b1: 1'b0);
assign tr1_fu_510_p2 = input_count_2_reg_223 >> ap_const_lv11_1;
assign tr_fu_292_p4 = {{input_count_reg_197[ap_const_lv32_1F : ap_const_lv32_1]}};
always @ (ap_clk)
begin
    input_count_2_cast_reg_1085[11] <= 1'b0;
    input_count_2_cast_reg_1085[12] <= 1'b0;
    input_count_2_cast_reg_1085[13] <= 1'b0;
    input_count_2_cast_reg_1085[14] <= 1'b0;
    input_count_2_cast_reg_1085[15] <= 1'b0;
    input_count_2_cast_reg_1085[16] <= 1'b0;
    input_count_2_cast_reg_1085[17] <= 1'b0;
    input_count_2_cast_reg_1085[18] <= 1'b0;
    input_count_2_cast_reg_1085[19] <= 1'b0;
    input_count_2_cast_reg_1085[20] <= 1'b0;
    input_count_2_cast_reg_1085[21] <= 1'b0;
    input_count_2_cast_reg_1085[22] <= 1'b0;
    input_count_2_cast_reg_1085[23] <= 1'b0;
    input_count_2_cast_reg_1085[24] <= 1'b0;
    input_count_2_cast_reg_1085[25] <= 1'b0;
    input_count_2_cast_reg_1085[26] <= 1'b0;
    input_count_2_cast_reg_1085[27] <= 1'b0;
    input_count_2_cast_reg_1085[28] <= 1'b0;
    input_count_2_cast_reg_1085[29] <= 1'b0;
    input_count_2_cast_reg_1085[30] <= 1'b0;
    input_count_2_cast_reg_1085[31] <= 1'b0;
end

always @ (ap_clk)
begin
    output_count1_1_fu_92[11] <= 1'b0;
    output_count1_1_fu_92[12] <= 1'b0;
    output_count1_1_fu_92[13] <= 1'b0;
    output_count1_1_fu_92[14] <= 1'b0;
    output_count1_1_fu_92[15] <= 1'b0;
    output_count1_1_fu_92[16] <= 1'b0;
    output_count1_1_fu_92[17] <= 1'b0;
    output_count1_1_fu_92[18] <= 1'b0;
    output_count1_1_fu_92[19] <= 1'b0;
    output_count1_1_fu_92[20] <= 1'b0;
    output_count1_1_fu_92[21] <= 1'b0;
    output_count1_1_fu_92[22] <= 1'b0;
    output_count1_1_fu_92[23] <= 1'b0;
    output_count1_1_fu_92[24] <= 1'b0;
    output_count1_1_fu_92[25] <= 1'b0;
    output_count1_1_fu_92[26] <= 1'b0;
    output_count1_1_fu_92[27] <= 1'b0;
    output_count1_1_fu_92[28] <= 1'b0;
    output_count1_1_fu_92[29] <= 1'b0;
    output_count1_1_fu_92[30] <= 1'b0;
    output_count1_1_fu_92[31] <= 1'b0;
end

always @ (ap_clk)
begin
    output_count1_3_fu_108[11] <= 1'b0;
    output_count1_3_fu_108[12] <= 1'b0;
    output_count1_3_fu_108[13] <= 1'b0;
    output_count1_3_fu_108[14] <= 1'b0;
    output_count1_3_fu_108[15] <= 1'b0;
    output_count1_3_fu_108[16] <= 1'b0;
    output_count1_3_fu_108[17] <= 1'b0;
    output_count1_3_fu_108[18] <= 1'b0;
    output_count1_3_fu_108[19] <= 1'b0;
    output_count1_3_fu_108[20] <= 1'b0;
    output_count1_3_fu_108[21] <= 1'b0;
    output_count1_3_fu_108[22] <= 1'b0;
    output_count1_3_fu_108[23] <= 1'b0;
    output_count1_3_fu_108[24] <= 1'b0;
    output_count1_3_fu_108[25] <= 1'b0;
    output_count1_3_fu_108[26] <= 1'b0;
    output_count1_3_fu_108[27] <= 1'b0;
    output_count1_3_fu_108[28] <= 1'b0;
    output_count1_3_fu_108[29] <= 1'b0;
    output_count1_3_fu_108[30] <= 1'b0;
    output_count1_3_fu_108[31] <= 1'b0;
end



endmodule //header_removal

