// ==============================================================
// File generated by AutoPilot - High-Level Synthesis System (C, C++, SystemC)
// Version: 2010.07.ft
// Copyright (C) :2006-2010 AutoESL Design Technologies, Inc.
// 
// ==============================================================

`timescale 1 ns / 1 ps
module header_removal_packet_out_data_tmp2(
    clk,
    address0,
    ce0,
    we0,
    d0,
    q0);

parameter DataWidth = 32'd64;
parameter AddressRange = 32'd1024;
parameter AddressWidth = 32'd10;
input clk;
input[AddressWidth - 1:0] address0;
input ce0;
input we0;
input[DataWidth - 1:0] d0;
output[DataWidth - 1:0] q0;



header_removal_packet_out_data_tmp2_ram header_removal_packet_out_data_tmp2_ram_U(
    .clk( clk ),
    .addr0( address0 ),
    .ce0( ce0 ),
    .d0( d0 ),
    .we0( we0 ),
    .q0( q0 ));

endmodule
