project new test.xise

project set "Device Family" "virtex5"

project set "Device" "xc5vtx240t"

project set "Package" "ff1759"

project set "Speed Grade" "-2"

project set "Synthesis Tool" "XST (VHDL/Verilog)"

project set "Simulator" "ISim (VHDL/Verilog)"

xfile add "../rtl/controller.v"
xfile add "../rtl/qdrii_chipscope.v"
xfile add "../rtl/qdrii_idelay_ctrl.v"
xfile add "../rtl/qdrii_infrastructure.v"
xfile add "../rtl/qdrii_phy_addr_io.v"
xfile add "../rtl/qdrii_phy_bw_io.v"
xfile add "../rtl/qdrii_phy_clk_io.v"
xfile add "../rtl/qdrii_phy_cq_io.v"
xfile add "../rtl/qdrii_phy_d_io.v"
xfile add "../rtl/qdrii_phy_dly_cal_sm.v"
xfile add "../rtl/qdrii_phy_en.v"
xfile add "../rtl/qdrii_phy_init_sm.v"
xfile add "../rtl/qdrii_phy_q_io.v"
xfile add "../rtl/qdrii_phy_read.v"
xfile add "../rtl/qdrii_phy_v5_q_io.v"
xfile add "../rtl/qdrii_phy_write.v"
xfile add "../rtl/qdrii_tb_top.v"
xfile add "../rtl/qdrii_test_addr_gen.v"
xfile add "../rtl/qdrii_test_cmp_data.v"
xfile add "../rtl/qdrii_test_data_gen.v"
xfile add "../rtl/qdrii_test_q_sm.v"
xfile add "../rtl/qdrii_test_wr_rd_sm.v"
xfile add "../rtl/qdrii_top.v"
xfile add "../rtl/qdrii_top_ctrl_sm.v"
xfile add "../rtl/qdrii_top_phy.v"
xfile add "../rtl/qdrii_top_rd_addr_interface.v"
xfile add "../rtl/qdrii_top_rd_interface.v"
xfile add "../rtl/qdrii_top_user_interface.v"
xfile add "../rtl/qdrii_top_wr_addr_interface.v"
xfile add "../rtl/qdrii_top_wr_data_interface.v"
xfile add "../rtl/qdrii_top_wr_interface.v"
xfile add "../rtl/qdrii_top_wrdata_bw_fifo.v"
xfile add "../rtl/qdrii_top_wrdata_fifo.v"

xfile add "controller.ucf"

project set "Optimization Goal" "Speed" -process "Synthesize - XST"
project set "Optimization Effort" "Normal" -process "Synthesize - XST"
project set "Use Synthesis Constraints File" "False" -process "Synthesize - XST"
project set "Library Search Order" "../synth/controller.lso" -process "Synthesize - XST"
project set "Keep Hierarchy" "No" -process "Synthesize - XST"
project set "Global Optimization Goal" "AllClockNets" -process "Synthesize - XST"
project set "Generate RTL Schematic" "Yes" -process "Synthesize - XST"
project set "Read Cores" "True" -process "Synthesize - XST"
project set "Write Timing Constraints" "False" -process "Synthesize - XST"
project set "Cross Clock Analysis" "False" -process "Synthesize - XST"
project set "Hierarchy Separator" "/" -process "Synthesize - XST"
project set "Bus Delimiter" "<>" -process "Synthesize - XST"
project set "Case" "Maintain" -process "Synthesize - XST"
project set "LUT-FF Pairs Utilization Ratio" "100" -process "Synthesize - XST"
project set "Verilog 2001" "True" -process "Synthesize - XST"
project set "FSM Encoding Algorithm" "Auto" -process "Synthesize - XST"
project set "FSM Style" "LUT" -process "Synthesize - XST"
project set "RAM Extraction" "True" -process "Synthesize - XST"
project set "RAM Style" "Auto" -process "Synthesize - XST"
project set "ROM Extraction" "True" -process "Synthesize - XST"
project set "ROM Style" "Auto" -process "Synthesize - XST"
project set "Mux Extraction" "Yes" -process "Synthesize - XST"
project set "Mux Style" "Auto" -process "Synthesize - XST"
project set "Decoder Extraction" "True" -process "Synthesize - XST"
project set "Priority Encoder Extraction" "Yes" -process "Synthesize - XST"
project set "Shift Register Extraction" "True" -process "Synthesize - XST"
project set "Logical Shifter Extraction" "True" -process "Synthesize - XST"
project set "XOR Collapsing" "True" -process "Synthesize - XST"
project set "Resource Sharing" "True" -process "Synthesize - XST"
project set "Use DSP Block" "Auto" -process "Synthesize - XST"
project set "Add I/O Buffers" "True" -process "Synthesize - XST"
project set "Max Fanout" "100000" -process "Synthesize - XST"
project set "Number of Clock Buffers" "32" -process "Synthesize - XST"
project set "Register Duplication" "True" -process "Synthesize - XST"
project set "Equivalent Register Removal" "True" -process "Synthesize - XST"
project set "Register Balancing" "No" -process "Synthesize - XST"
project set "Slice Packing" "True" -process "Synthesize - XST"
project set "Optimize Instantiated Primitives" "False" -process "Synthesize - XST"
project set "Pack I/O Registers into IOBs" "Auto" -process "Synthesize - XST"
project set "Use Synchronous Set" "Auto" -process "Synthesize - XST"
project set "Use Synchronous Reset" "Auto" -process "Synthesize - XST"

project set "Netlist Translation Type" "Timestamp" -process Translate

project set "Placer Effort Level" "High" -process Map
project set "Starting Placer Cost Table (1-100)" "1" -process Map
project set "Optimization Strategy (Cover Mode)" "Area" -process Map
project set "Pack I/O Registers/Latches into IOBs" "Off" -process Map

project set "Place & Route Effort Level (Overall)" "High" -process "Place & Route"

project set "Change Device Speed To" "-2" -process "Generate Post-Map Static Timing"

project set "Change Device Speed To" "-2" -process "Generate Post-Place & Route Static Timing"

project set "Enable Debugging of Serial Mode BitStream" "False" -process "Generate Programming File"
project set "Create Binary Configuration File" "False" -process "Generate Programming File"
project set "Enable Cyclic Redundancy Checking (CRC)" "True" -process "Generate Programming File"
project set "Configuration Rate" "2" -process "Generate Programming File"
project set "Configuration Clk (Configuration Pins)" "Pull Up" -process "Generate Programming File"
project set "Configuration Pin M0" "Pull Up" -process "Generate Programming File"
project set "Configuration Pin M1" "Pull Up" -process "Generate Programming File"
project set "Configuration Pin M2" "Pull Up" -process "Generate Programming File"
project set "Configuration Pin Program" "Pull Up" -process "Generate Programming File"
project set "Configuration Pin Done" "Pull Up" -process "Generate Programming File"
project set "Configuration Pin Init" "Pull Up" -process "Generate Programming File"
project set "Configuration Pin CS" "Pull Up" -process "Generate Programming File"
project set "Configuration Pin DIn" "Pull Up" -process "Generate Programming File"
project set "Configuration Pin Busy" "Pull Up" -process "Generate Programming File"
project set "Configuration Pin RdWr" "Pull Up" -process "Generate Programming File"
project set "JTAG Pin TCK" "Pull Up" -process "Generate Programming File"
project set "JTAG Pin TDI" "Pull Up" -process "Generate Programming File"
project set "JTAG Pin TDO" "Pull Up" -process "Generate Programming File"
project set "JTAG Pin TMS" "Pull Up" -process "Generate Programming File"
project set "Unused IOB Pins" "Pull Down" -process "Generate Programming File"
project set "UserID Code (8 Digit Hexadecimal)" "0xFFFFFFFF" -process "Generate Programming File"
project set "DCI Update Mode" "As Required" -process "Generate Programming File"
project set "FPGA Start-Up Clock" "CCLK" -process "Generate Programming File"
project set "Done (Output Events)" "Default (4)" -process "Generate Programming File"
project set "Enable Outputs (Output Events)" "Default (5)" -process "Generate Programming File"
project set "Release Write Enable (Output Events)" "Default (6)" -process "Generate Programming File"
project set "Wait for DLL Lock (Output Events)" "Default (NoWait)" -process "Generate Programming File"
project set "Enable Internal Done Pipe" "False" -process "Generate Programming File"
project set "Drive Done Pin High" "False" -process "Generate Programming File"
project set "Security" "Enable Readback and Reconfiguration" -process "Generate Programming File"
project set "Encrypt Bitstream" "False" -process "Generate Programming File"

project close


