// ==============================================================
// RTL generated by AutoPilot - High-Level Synthesis System (C, C++, SystemC)
// Version: 2010.b.1
// Copyright (C) :2006-2010 AutoESL Design Technologies, Inc.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module eth_switch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        packet_in_data_address0,
        packet_in_data_ce0,
        packet_in_data_q0,
        eth_header_0_read,
        eth_header_1_read,
        eth_header_2_read,
        eth_header_3_read,
        packet_out_data_address0,
        packet_out_data_ce0,
        packet_out_data_we0,
        packet_out_data_d0,
        forward_table_macid_address0,
        forward_table_macid_ce0,
        forward_table_macid_we0,
        forward_table_macid_d0,
        forward_table_macid_q0,
        forward_table_portid_address0,
        forward_table_portid_ce0,
        forward_table_portid_we0,
        forward_table_portid_d0,
        forward_table_portid_q0,
        ap_return
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output  [10:0] packet_in_data_address0;
output   packet_in_data_ce0;
input  [7:0] packet_in_data_q0;
input  [47:0] eth_header_0_read;
input  [47:0] eth_header_1_read;
input  [15:0] eth_header_2_read;
input  [7:0] eth_header_3_read;
output  [10:0] packet_out_data_address0;
output   packet_out_data_ce0;
output   packet_out_data_we0;
output  [7:0] packet_out_data_d0;
output  [1:0] forward_table_macid_address0;
output   forward_table_macid_ce0;
output   forward_table_macid_we0;
output  [47:0] forward_table_macid_d0;
input  [47:0] forward_table_macid_q0;
output  [1:0] forward_table_portid_address0;
output   forward_table_portid_ce0;
output   forward_table_portid_we0;
output  [7:0] forward_table_portid_d0;
input  [7:0] forward_table_portid_q0;
output  [7:0] ap_return;

reg ap_done;
reg ap_idle;
reg packet_in_data_ce0;
reg packet_out_data_ce0;
reg packet_out_data_we0;
reg[1:0] forward_table_macid_address0;
reg forward_table_macid_ce0;
reg forward_table_macid_we0;
reg[1:0] forward_table_portid_address0;
reg forward_table_portid_ce0;
reg forward_table_portid_we0;
reg   [3:0] ap_CS_fsm;
wire    grp_eth_learning_aging_fu_168_ap_done;
reg   [1:0] p_cast_reg_277;
reg   [2:0] indvar_next_i_reg_285;
wire   [0:0] icmp_fu_202_p2;
wire   [0:0] tmp_2_i_fu_219_p2;
reg   [10:0] tmp4_reg_308;
reg   [10:0] tmp_8_reg_316;
wire   [63:0] tmp_6_fu_257_p1;
reg   [63:0] tmp_6_reg_321;
wire   [0:0] exitcond_fu_246_p2;
reg    grp_eth_learning_aging_fu_168_ap_start;
wire    grp_eth_learning_aging_fu_168_ap_idle;
wire   [47:0] grp_eth_learning_aging_fu_168_srcmac;
wire   [7:0] grp_eth_learning_aging_fu_168_portid;
wire   [1:0] grp_eth_learning_aging_fu_168_forward_table_macid_address0;
wire    grp_eth_learning_aging_fu_168_forward_table_macid_ce0;
wire    grp_eth_learning_aging_fu_168_forward_table_macid_we0;
wire   [47:0] grp_eth_learning_aging_fu_168_forward_table_macid_d0;
wire   [47:0] grp_eth_learning_aging_fu_168_forward_table_macid_q0;
wire   [1:0] grp_eth_learning_aging_fu_168_forward_table_portid_address0;
wire    grp_eth_learning_aging_fu_168_forward_table_portid_ce0;
wire    grp_eth_learning_aging_fu_168_forward_table_portid_we0;
wire   [7:0] grp_eth_learning_aging_fu_168_forward_table_portid_d0;
wire   [7:0] grp_eth_learning_aging_fu_168_forward_table_portid_q0;
reg   [2:0] tmp_reg_133;
reg   [7:0] call_ret1_reg_144;
reg   [10:0] i_reg_156;
wire   [63:0] p_cast7_fu_214_p1;
wire   [63:0] p_lcssa2_cast_fu_224_p1;
wire   [0:0] tmp_2_fu_190_p3;
wire   [1:0] tmp_3_fu_198_p1;
wire   [0:0] tmp3_fu_232_p2;
wire   [10:0] tmp_1_fu_228_p1;
reg   [3:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st0_fsm_0 = 4'b0000;
parameter    ap_ST_st1_fsm_1 = 4'b0001;
parameter    ap_ST_st2_fsm_2 = 4'b0010;
parameter    ap_ST_st3_fsm_3 = 4'b0011;
parameter    ap_ST_st4_fsm_4 = 4'b0100;
parameter    ap_ST_st5_fsm_5 = 4'b0101;
parameter    ap_ST_st6_fsm_6 = 4'b0110;
parameter    ap_ST_st7_fsm_7 = 4'b0111;
parameter    ap_ST_st8_fsm_8 = 4'b1000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_2 = 32'b00000000000000000000000000000010;
parameter    ap_const_lv2_1 = 2'b01;
parameter    ap_const_lv3_1 = 3'b001;
parameter    ap_const_lv16_5EE = 16'b0000010111101110;
parameter    ap_const_lv11_5EE = 11'b10111101110;
parameter    ap_const_lv11_1 = 11'b00000000001;
parameter    ap_true = 1'b1;


eth_learning_aging grp_eth_learning_aging_fu_168(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_eth_learning_aging_fu_168_ap_start ),
    .ap_done( grp_eth_learning_aging_fu_168_ap_done ),
    .ap_idle( grp_eth_learning_aging_fu_168_ap_idle ),
    .srcmac( grp_eth_learning_aging_fu_168_srcmac ),
    .portid( grp_eth_learning_aging_fu_168_portid ),
    .forward_table_macid_address0( grp_eth_learning_aging_fu_168_forward_table_macid_address0 ),
    .forward_table_macid_ce0( grp_eth_learning_aging_fu_168_forward_table_macid_ce0 ),
    .forward_table_macid_we0( grp_eth_learning_aging_fu_168_forward_table_macid_we0 ),
    .forward_table_macid_d0( grp_eth_learning_aging_fu_168_forward_table_macid_d0 ),
    .forward_table_macid_q0( grp_eth_learning_aging_fu_168_forward_table_macid_q0 ),
    .forward_table_portid_address0( grp_eth_learning_aging_fu_168_forward_table_portid_address0 ),
    .forward_table_portid_ce0( grp_eth_learning_aging_fu_168_forward_table_portid_ce0 ),
    .forward_table_portid_we0( grp_eth_learning_aging_fu_168_forward_table_portid_we0 ),
    .forward_table_portid_d0( grp_eth_learning_aging_fu_168_forward_table_portid_d0 ),
    .forward_table_portid_q0( grp_eth_learning_aging_fu_168_forward_table_portid_q0 )
);



/// ap_CS_fsm assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & ~(icmp_fu_202_p2 == ap_const_lv1_0))) begin
        call_ret1_reg_144 <= ap_const_lv8_FF;
    end else if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        call_ret1_reg_144 <= forward_table_portid_q0;
    end
    if ((ap_ST_st8_fsm_8 == ap_CS_fsm)) begin
        i_reg_156 <= tmp_8_reg_316;
    end else if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        i_reg_156 <= ap_const_lv11_0;
    end
    if ((ap_ST_st3_fsm_3 == ap_CS_fsm)) begin
        indvar_next_i_reg_285 <= (tmp_reg_133 + ap_const_lv3_1);
    end
    if ((ap_ST_st3_fsm_3 == ap_CS_fsm)) begin
        p_cast_reg_277 <= tmp_reg_133[1:0];
    end
    if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        if (tmp3_fu_232_p2) begin
            tmp4_reg_308 <= tmp_1_fu_228_p1;
        end else begin
            tmp4_reg_308 <= ap_const_lv11_5EE;
        end

    end
    if (((ap_ST_st7_fsm_7 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_fu_246_p2))) begin
        tmp_6_reg_321[0] <= tmp_6_fu_257_p1[0];
        tmp_6_reg_321[1] <= tmp_6_fu_257_p1[1];
        tmp_6_reg_321[2] <= tmp_6_fu_257_p1[2];
        tmp_6_reg_321[3] <= tmp_6_fu_257_p1[3];
        tmp_6_reg_321[4] <= tmp_6_fu_257_p1[4];
        tmp_6_reg_321[5] <= tmp_6_fu_257_p1[5];
        tmp_6_reg_321[6] <= tmp_6_fu_257_p1[6];
        tmp_6_reg_321[7] <= tmp_6_fu_257_p1[7];
        tmp_6_reg_321[8] <= tmp_6_fu_257_p1[8];
        tmp_6_reg_321[9] <= tmp_6_fu_257_p1[9];
        tmp_6_reg_321[10] <= tmp_6_fu_257_p1[10];
    end
    if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        tmp_8_reg_316 <= (i_reg_156 + ap_const_lv11_1);
    end
    if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_2_i_fu_219_p2))) begin
        tmp_reg_133 <= indvar_next_i_reg_285;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_eth_learning_aging_fu_168_ap_done))) begin
        tmp_reg_133 <= ap_const_lv3_0;
    end
end

/// ap_NS_fsm assign process. ///
always @ (ap_start or ap_CS_fsm or grp_eth_learning_aging_fu_168_ap_done or icmp_fu_202_p2 or tmp_2_i_fu_219_p2 or exitcond_fu_246_p2)
begin
    if (((ap_ST_st7_fsm_7 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_246_p2) & ~(ap_const_logic_1 == ap_start))) begin
        ap_NS_fsm = ap_ST_st0_fsm_0;
    end else if (((ap_ST_st7_fsm_7 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_fu_246_p2))) begin
        ap_NS_fsm = ap_ST_st8_fsm_8;
    end else if (((ap_ST_st6_fsm_6 == ap_CS_fsm) | (ap_ST_st8_fsm_8 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st7_fsm_7;
    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_2_i_fu_219_p2))) begin
        ap_NS_fsm = ap_ST_st5_fsm_5;
    end else if (((ap_ST_st5_fsm_5 == ap_CS_fsm) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & ~(icmp_fu_202_p2 == ap_const_lv1_0)))) begin
        ap_NS_fsm = ap_ST_st6_fsm_6;
    end else if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & (icmp_fu_202_p2 == ap_const_lv1_0))) begin
        ap_NS_fsm = ap_ST_st4_fsm_4;
    end else if ((((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_eth_learning_aging_fu_168_ap_done)) | ((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_2_i_fu_219_p2)))) begin
        ap_NS_fsm = ap_ST_st3_fsm_3;
    end else if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st2_fsm_2;
    end else if ((((ap_ST_st0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_start)) | ((ap_ST_st7_fsm_7 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_246_p2) & (ap_const_logic_1 == ap_start)))) begin
        ap_NS_fsm = ap_ST_st1_fsm_1;
    end else begin
        ap_NS_fsm = ap_CS_fsm;
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm or exitcond_fu_246_p2)
begin
    if (((ap_ST_st0_fsm_0 == ap_CS_fsm) | ((ap_ST_st7_fsm_7 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_246_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st0_fsm_0 == ap_CS_fsm)) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// forward_table_macid_address0 assign process. ///
always @ (ap_CS_fsm or icmp_fu_202_p2 or grp_eth_learning_aging_fu_168_forward_table_macid_address0 or p_cast7_fu_214_p1)
begin
    if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & (icmp_fu_202_p2 == ap_const_lv1_0))) begin
        forward_table_macid_address0 = p_cast7_fu_214_p1;
    end else if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        forward_table_macid_address0 = grp_eth_learning_aging_fu_168_forward_table_macid_address0;
    end else begin
        forward_table_macid_address0 = grp_eth_learning_aging_fu_168_forward_table_macid_address0;
    end
end

/// forward_table_macid_ce0 assign process. ///
always @ (ap_CS_fsm or icmp_fu_202_p2 or grp_eth_learning_aging_fu_168_forward_table_macid_ce0)
begin
    if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & (icmp_fu_202_p2 == ap_const_lv1_0))) begin
        forward_table_macid_ce0 = ap_const_logic_1;
    end else if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        forward_table_macid_ce0 = grp_eth_learning_aging_fu_168_forward_table_macid_ce0;
    end else begin
        forward_table_macid_ce0 = ap_const_logic_0;
    end
end

/// forward_table_macid_we0 assign process. ///
always @ (ap_CS_fsm or grp_eth_learning_aging_fu_168_forward_table_macid_we0)
begin
    if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        forward_table_macid_we0 = grp_eth_learning_aging_fu_168_forward_table_macid_we0;
    end else begin
        forward_table_macid_we0 = ap_const_logic_0;
    end
end

/// forward_table_portid_address0 assign process. ///
always @ (ap_CS_fsm or tmp_2_i_fu_219_p2 or grp_eth_learning_aging_fu_168_forward_table_portid_address0 or p_lcssa2_cast_fu_224_p1)
begin
    if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_2_i_fu_219_p2))) begin
        forward_table_portid_address0 = p_lcssa2_cast_fu_224_p1;
    end else if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        forward_table_portid_address0 = grp_eth_learning_aging_fu_168_forward_table_portid_address0;
    end else begin
        forward_table_portid_address0 = grp_eth_learning_aging_fu_168_forward_table_portid_address0;
    end
end

/// forward_table_portid_ce0 assign process. ///
always @ (ap_CS_fsm or tmp_2_i_fu_219_p2 or grp_eth_learning_aging_fu_168_forward_table_portid_ce0)
begin
    if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_2_i_fu_219_p2))) begin
        forward_table_portid_ce0 = ap_const_logic_1;
    end else if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        forward_table_portid_ce0 = grp_eth_learning_aging_fu_168_forward_table_portid_ce0;
    end else begin
        forward_table_portid_ce0 = ap_const_logic_0;
    end
end

/// forward_table_portid_we0 assign process. ///
always @ (ap_CS_fsm or grp_eth_learning_aging_fu_168_forward_table_portid_we0)
begin
    if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        forward_table_portid_we0 = grp_eth_learning_aging_fu_168_forward_table_portid_we0;
    end else begin
        forward_table_portid_we0 = ap_const_logic_0;
    end
end

/// grp_eth_learning_aging_fu_168_ap_start assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        grp_eth_learning_aging_fu_168_ap_start = ap_const_logic_1;
    end else begin
        grp_eth_learning_aging_fu_168_ap_start = ap_const_logic_0;
    end
end

/// packet_in_data_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond_fu_246_p2)
begin
    if (((ap_ST_st7_fsm_7 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_fu_246_p2))) begin
        packet_in_data_ce0 = ap_const_logic_1;
    end else begin
        packet_in_data_ce0 = ap_const_logic_0;
    end
end

/// packet_out_data_ce0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st8_fsm_8 == ap_CS_fsm)) begin
        packet_out_data_ce0 = ap_const_logic_1;
    end else begin
        packet_out_data_ce0 = ap_const_logic_0;
    end
end

/// packet_out_data_we0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st8_fsm_8 == ap_CS_fsm)) begin
        packet_out_data_we0 = ap_const_logic_1;
    end else begin
        packet_out_data_we0 = ap_const_logic_0;
    end
end
assign ap_return = call_ret1_reg_144;
assign exitcond_fu_246_p2 = (i_reg_156 == tmp4_reg_308? 1'b1: 1'b0);
assign forward_table_macid_d0 = grp_eth_learning_aging_fu_168_forward_table_macid_d0;
assign forward_table_portid_d0 = grp_eth_learning_aging_fu_168_forward_table_portid_d0;
assign grp_eth_learning_aging_fu_168_forward_table_macid_q0 = forward_table_macid_q0;
assign grp_eth_learning_aging_fu_168_forward_table_portid_q0 = forward_table_portid_q0;
assign grp_eth_learning_aging_fu_168_portid = eth_header_3_read;
assign grp_eth_learning_aging_fu_168_srcmac = eth_header_0_read;
assign icmp_fu_202_p2 = (tmp_3_fu_198_p1 == ap_const_lv2_1? 1'b1: 1'b0);
assign p_cast7_fu_214_p1 = {{61{1'b0}}, {tmp_reg_133}};
assign p_lcssa2_cast_fu_224_p1 = {{62{1'b0}}, {p_cast_reg_277}};
assign packet_in_data_address0 = tmp_6_fu_257_p1;
assign packet_out_data_address0 = tmp_6_reg_321;
assign packet_out_data_d0 = packet_in_data_q0;
assign tmp3_fu_232_p2 = (eth_header_2_read < ap_const_lv16_5EE? 1'b1: 1'b0);
assign tmp_1_fu_228_p1 = eth_header_2_read[10:0];
assign tmp_2_fu_190_p3 = tmp_reg_133[ap_const_lv32_2];
assign tmp_2_i_fu_219_p2 = (forward_table_macid_q0 == eth_header_1_read? 1'b1: 1'b0);
assign tmp_3_fu_198_p1 = {{1{1'b0}}, {tmp_2_fu_190_p3}};
assign tmp_6_fu_257_p1 = {{53{1'b0}}, {i_reg_156}};
always @ (ap_clk)
begin
    tmp_6_reg_321[11] <= 1'b0;
    tmp_6_reg_321[12] <= 1'b0;
    tmp_6_reg_321[13] <= 1'b0;
    tmp_6_reg_321[14] <= 1'b0;
    tmp_6_reg_321[15] <= 1'b0;
    tmp_6_reg_321[16] <= 1'b0;
    tmp_6_reg_321[17] <= 1'b0;
    tmp_6_reg_321[18] <= 1'b0;
    tmp_6_reg_321[19] <= 1'b0;
    tmp_6_reg_321[20] <= 1'b0;
    tmp_6_reg_321[21] <= 1'b0;
    tmp_6_reg_321[22] <= 1'b0;
    tmp_6_reg_321[23] <= 1'b0;
    tmp_6_reg_321[24] <= 1'b0;
    tmp_6_reg_321[25] <= 1'b0;
    tmp_6_reg_321[26] <= 1'b0;
    tmp_6_reg_321[27] <= 1'b0;
    tmp_6_reg_321[28] <= 1'b0;
    tmp_6_reg_321[29] <= 1'b0;
    tmp_6_reg_321[30] <= 1'b0;
    tmp_6_reg_321[31] <= 1'b0;
    tmp_6_reg_321[32] <= 1'b0;
    tmp_6_reg_321[33] <= 1'b0;
    tmp_6_reg_321[34] <= 1'b0;
    tmp_6_reg_321[35] <= 1'b0;
    tmp_6_reg_321[36] <= 1'b0;
    tmp_6_reg_321[37] <= 1'b0;
    tmp_6_reg_321[38] <= 1'b0;
    tmp_6_reg_321[39] <= 1'b0;
    tmp_6_reg_321[40] <= 1'b0;
    tmp_6_reg_321[41] <= 1'b0;
    tmp_6_reg_321[42] <= 1'b0;
    tmp_6_reg_321[43] <= 1'b0;
    tmp_6_reg_321[44] <= 1'b0;
    tmp_6_reg_321[45] <= 1'b0;
    tmp_6_reg_321[46] <= 1'b0;
    tmp_6_reg_321[47] <= 1'b0;
    tmp_6_reg_321[48] <= 1'b0;
    tmp_6_reg_321[49] <= 1'b0;
    tmp_6_reg_321[50] <= 1'b0;
    tmp_6_reg_321[51] <= 1'b0;
    tmp_6_reg_321[52] <= 1'b0;
    tmp_6_reg_321[53] <= 1'b0;
    tmp_6_reg_321[54] <= 1'b0;
    tmp_6_reg_321[55] <= 1'b0;
    tmp_6_reg_321[56] <= 1'b0;
    tmp_6_reg_321[57] <= 1'b0;
    tmp_6_reg_321[58] <= 1'b0;
    tmp_6_reg_321[59] <= 1'b0;
    tmp_6_reg_321[60] <= 1'b0;
    tmp_6_reg_321[61] <= 1'b0;
    tmp_6_reg_321[62] <= 1'b0;
    tmp_6_reg_321[63] <= 1'b0;
end



endmodule //eth_switch

