// ==============================================================
// RTL generated by AutoPilot - High-Level Synthesis System (C, C++, SystemC)
// Version: 2010.b.1
// Copyright (C) :2006-2010 AutoESL Design Technologies, Inc.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module eth_learning_aging (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        srcmac,
        portid,
        forward_table_macid_address0,
        forward_table_macid_ce0,
        forward_table_macid_we0,
        forward_table_macid_d0,
        forward_table_macid_q0,
        forward_table_portid_address0,
        forward_table_portid_ce0,
        forward_table_portid_we0,
        forward_table_portid_d0,
        forward_table_portid_q0
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
input  [47:0] srcmac;
input  [7:0] portid;
output  [1:0] forward_table_macid_address0;
output   forward_table_macid_ce0;
output   forward_table_macid_we0;
output  [47:0] forward_table_macid_d0;
input  [47:0] forward_table_macid_q0;
output  [1:0] forward_table_portid_address0;
output   forward_table_portid_ce0;
output   forward_table_portid_we0;
output  [7:0] forward_table_portid_d0;
input  [7:0] forward_table_portid_q0;

reg ap_done;
reg ap_idle;
reg[1:0] forward_table_macid_address0;
reg forward_table_macid_ce0;
reg forward_table_macid_we0;
reg[1:0] forward_table_portid_address0;
reg forward_table_portid_ce0;
reg forward_table_portid_we0;
reg   [3:0] ap_CS_fsm;
reg   [0:0] start_aging;
reg   [2:0] mostaged_index;
reg   [1:0] forward_table_age_address0;
reg    forward_table_age_ce0;
reg    forward_table_age_we0;
reg   [7:0] forward_table_age_d0;
wire   [7:0] forward_table_age_q0;
reg   [1:0] p_cast1_reg_379;
wire   [63:0] p_cast_fu_234_p1;
reg   [63:0] p_cast_reg_384;
wire   [0:0] icmp_fu_251_p2;
reg   [0:0] icmp_reg_389;
reg   [2:0] indvar_next_reg_393;
wire   [0:0] tmp_2_fu_270_p2;
reg   [0:0] tmp_2_reg_403;
reg   [1:0] forward_table_age_addr_1_reg_410;
wire   [0:0] brmerge_fu_283_p2;
reg   [2:0] tmp_s_reg_415;
reg   [31:0] tmp_6_reg_420;
wire   [63:0] p_lcssa1_cast_fu_299_p1;
reg   [63:0] p_lcssa1_cast_reg_425;
reg   [1:0] forward_table_portid_addr_1_reg_430;
wire   [7:0] tmp_7_fu_303_p2;
reg   [7:0] tmp_7_reg_435;
reg   [2:0] mostaged_index_tmp_reg_440;
reg   [1:0] mostaged_reg_445;
reg   [0:0] tmp_4_reg_450;
reg   [2:0] tmp_reg_168;
wire   [2:0] mostaged_index_tmp_1_phi_fu_183_p4;
reg   [2:0] mostaged_index_tmp_1_reg_179;
wire   [0:0] start_aging_tmp_1_phi_fu_196_p4;
reg   [0:0] start_aging_tmp_1_reg_191;
reg   [1:0] mostaged_1_reg_205;
reg   [31:0] tmp_1_reg_217;
wire   [63:0] tmp_5_fu_263_p1;
wire   [63:0] tmp_10_fu_338_p1;
wire   [0:0] tmp_12_fu_239_p3;
wire   [1:0] tmp_13_fu_247_p1;
wire   [0:0] tmp_14_fu_275_p3;
wire   [7:0] tmp_8_fu_309_p1;
wire   [0:0] tmp_9_fu_313_p2;
wire   [1:0] tmp_3_fu_319_p1;
reg   [3:0] ap_NS_fsm;
wire   [63:0] forward_table_portid_addr_1_reg_4300;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st0_fsm_0 = 4'b0000;
parameter    ap_ST_st1_fsm_1 = 4'b0001;
parameter    ap_ST_st2_fsm_2 = 4'b0010;
parameter    ap_ST_st3_fsm_3 = 4'b0011;
parameter    ap_ST_st4_fsm_4 = 4'b0100;
parameter    ap_ST_st5_fsm_5 = 4'b0101;
parameter    ap_ST_st6_fsm_6 = 4'b0110;
parameter    ap_ST_st7_fsm_7 = 4'b0111;
parameter    ap_ST_st8_fsm_8 = 4'b1000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv32_2 = 32'b00000000000000000000000000000010;
parameter    ap_const_lv2_1 = 2'b01;
parameter    ap_const_lv3_1 = 3'b001;
parameter    ap_const_lv32_1 = 32'b00000000000000000000000000000001;
parameter    ap_const_lv8_1 = 8'b00000001;
parameter    ap_true = 1'b1;


eth_learning_aging_forward_table_age #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
forward_table_age_U(
    .clk( ap_clk ),
    .address0( forward_table_age_address0 ),
    .ce0( forward_table_age_ce0 ),
    .we0( forward_table_age_we0 ),
    .d0( forward_table_age_d0 ),
    .q0( forward_table_age_q0 )
);



/// ap_CS_fsm assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// mostaged_index assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_mostaged_index
    if (ap_rst == 1'b1) begin
        mostaged_index <= ap_const_lv3_0;
    end else begin
        if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
            mostaged_index <= (mostaged_index_tmp_1_reg_179 + ap_const_lv3_1);
        end else if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_2_fu_270_p2))) begin
            mostaged_index <= mostaged_index_tmp_1_reg_179;
        end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp_fu_251_p2))) begin
            mostaged_index <= mostaged_index_tmp_1_phi_fu_183_p4;
        end
    end
end

/// start_aging assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_start_aging
    if (ap_rst == 1'b1) begin
        start_aging <= ap_const_lv1_0;
    end else begin
        if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_2_fu_270_p2))) begin
            start_aging <= start_aging_tmp_1_reg_191;
        end else if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_2_fu_270_p2) & (ap_const_lv1_0 == brmerge_fu_283_p2))) begin
            start_aging <= ap_const_lv1_0;
        end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp_fu_251_p2))) begin
            start_aging <= start_aging_tmp_1_phi_fu_196_p4;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_2_fu_270_p2) & ~(ap_const_lv1_0 == brmerge_fu_283_p2))) begin
        forward_table_age_addr_1_reg_410 <= p_cast_reg_384;
    end
    if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_2_fu_270_p2))) begin
        forward_table_portid_addr_1_reg_430 <= forward_table_portid_addr_1_reg_4300;
    end
    if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        icmp_reg_389 <= (tmp_13_fu_247_p1 == ap_const_lv2_1? 1'b1: 1'b0);
    end
    if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        indvar_next_reg_393 <= (tmp_reg_168 + ap_const_lv3_1);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        mostaged_1_reg_205 <= ap_const_lv2_0;
    end else if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        mostaged_1_reg_205 <= mostaged_reg_445;
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        mostaged_index_tmp_1_reg_179 <= mostaged_index;
    end else if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        mostaged_index_tmp_1_reg_179 <= mostaged_index_tmp_reg_440;
    end
    if ((ap_ST_st4_fsm_4 == ap_CS_fsm)) begin
        if (tmp_9_fu_313_p2) begin
            mostaged_index_tmp_reg_440 <= tmp_s_reg_415;
        end else begin
            mostaged_index_tmp_reg_440 <= mostaged_index_tmp_1_reg_179;
        end

    end
    if ((ap_ST_st4_fsm_4 == ap_CS_fsm)) begin
        if (tmp_9_fu_313_p2) begin
            mostaged_reg_445 <= tmp_3_fu_319_p1;
        end else begin
            mostaged_reg_445 <= mostaged_1_reg_205;
        end

    end
    if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        p_cast1_reg_379 <= tmp_reg_168[1:0];
    end
    if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        p_cast_reg_384[0] <= p_cast_fu_234_p1[0];
        p_cast_reg_384[1] <= p_cast_fu_234_p1[1];
        p_cast_reg_384[2] <= p_cast_fu_234_p1[2];
    end
    if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_2_fu_270_p2))) begin
        p_lcssa1_cast_reg_425[0] <= p_lcssa1_cast_fu_299_p1[0];
        p_lcssa1_cast_reg_425[1] <= p_lcssa1_cast_fu_299_p1[1];
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        start_aging_tmp_1_reg_191 <= start_aging;
    end else if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        start_aging_tmp_1_reg_191 <= ap_const_lv1_1;
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_1_reg_217 <= ap_const_lv32_0;
    end else if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        tmp_1_reg_217 <= tmp_6_reg_420;
    end
    if ((ap_ST_st3_fsm_3 == ap_CS_fsm)) begin
        tmp_2_reg_403 <= (forward_table_macid_q0 == srcmac? 1'b1: 1'b0);
    end
    if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        tmp_4_reg_450 <= (forward_table_portid_q0 == portid? 1'b1: 1'b0);
    end
    if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_2_fu_270_p2) & ~(ap_const_lv1_0 == brmerge_fu_283_p2))) begin
        tmp_6_reg_420 <= (tmp_1_reg_217 + ap_const_lv32_1);
    end
    if ((ap_ST_st4_fsm_4 == ap_CS_fsm)) begin
        tmp_7_reg_435 <= (forward_table_age_q0 + ap_const_lv8_1);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_reg_168 <= ap_const_lv3_0;
    end else if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        tmp_reg_168 <= indvar_next_reg_393;
    end
    if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_2_fu_270_p2) & ~(ap_const_lv1_0 == brmerge_fu_283_p2))) begin
        tmp_s_reg_415 <= tmp_1_reg_217[2:0];
    end
end

/// ap_NS_fsm assign process. ///
always @ (ap_start or ap_CS_fsm or icmp_fu_251_p2 or tmp_2_fu_270_p2 or brmerge_fu_283_p2)
begin
    if (((ap_ST_st8_fsm_8 == ap_CS_fsm) & ~(ap_const_logic_1 == ap_start))) begin
        ap_NS_fsm = ap_ST_st0_fsm_0;
    end else if ((ap_ST_st4_fsm_4 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st5_fsm_5;
    end else if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_2_fu_270_p2) & (ap_const_lv1_0 == brmerge_fu_283_p2))) begin
        ap_NS_fsm = ap_ST_st6_fsm_6;
    end else if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_2_fu_270_p2) & ~(ap_const_lv1_0 == brmerge_fu_283_p2))) begin
        ap_NS_fsm = ap_ST_st4_fsm_4;
    end else if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_2_fu_270_p2))) begin
        ap_NS_fsm = ap_ST_st7_fsm_7;
    end else if (((ap_ST_st7_fsm_7 == ap_CS_fsm) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp_fu_251_p2)) | (ap_ST_st6_fsm_6 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st8_fsm_8;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == icmp_fu_251_p2))) begin
        ap_NS_fsm = ap_ST_st3_fsm_3;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) | (ap_ST_st5_fsm_5 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st2_fsm_2;
    end else if ((((ap_ST_st0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_start)) | ((ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_logic_1 == ap_start)))) begin
        ap_NS_fsm = ap_ST_st1_fsm_1;
    end else begin
        ap_NS_fsm = ap_CS_fsm;
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st0_fsm_0 == ap_CS_fsm) | (ap_ST_st8_fsm_8 == ap_CS_fsm))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st0_fsm_0 == ap_CS_fsm)) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// forward_table_age_address0 assign process. ///
always @ (ap_CS_fsm or p_cast_reg_384 or icmp_fu_251_p2 or icmp_reg_389 or tmp_2_fu_270_p2 or tmp_2_reg_403 or forward_table_age_addr_1_reg_410 or brmerge_fu_283_p2 or p_lcssa1_cast_reg_425 or tmp_5_fu_263_p1 or tmp_10_fu_338_p1)
begin
    if (((ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == icmp_reg_389) & ~(ap_const_lv1_0 == tmp_2_reg_403))) begin
        forward_table_age_address0 = p_lcssa1_cast_reg_425;
    end else if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        forward_table_age_address0 = tmp_10_fu_338_p1;
    end else if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        forward_table_age_address0 = forward_table_age_addr_1_reg_410;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp_fu_251_p2))) begin
        forward_table_age_address0 = tmp_5_fu_263_p1;
    end else if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_2_fu_270_p2) & ~(ap_const_lv1_0 == brmerge_fu_283_p2))) begin
        forward_table_age_address0 = p_cast_reg_384;
    end else begin
        forward_table_age_address0 = p_lcssa1_cast_reg_425;
    end
end

/// forward_table_age_ce0 assign process. ///
always @ (ap_CS_fsm or icmp_fu_251_p2 or icmp_reg_389 or tmp_2_fu_270_p2 or tmp_2_reg_403 or brmerge_fu_283_p2)
begin
    if ((((ap_ST_st3_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_2_fu_270_p2) & ~(ap_const_lv1_0 == brmerge_fu_283_p2)) | (ap_ST_st5_fsm_5 == ap_CS_fsm) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp_fu_251_p2)) | (ap_ST_st6_fsm_6 == ap_CS_fsm) | ((ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == icmp_reg_389) & ~(ap_const_lv1_0 == tmp_2_reg_403)))) begin
        forward_table_age_ce0 = ap_const_logic_1;
    end else begin
        forward_table_age_ce0 = ap_const_logic_0;
    end
end

/// forward_table_age_d0 assign process. ///
always @ (ap_CS_fsm or icmp_fu_251_p2 or icmp_reg_389 or tmp_2_reg_403 or tmp_7_reg_435)
begin
    if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        forward_table_age_d0 = tmp_7_reg_435;
    end else if ((((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp_fu_251_p2)) | (ap_ST_st6_fsm_6 == ap_CS_fsm) | ((ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == icmp_reg_389) & ~(ap_const_lv1_0 == tmp_2_reg_403)))) begin
        forward_table_age_d0 = ap_const_lv8_0;
    end else begin
        forward_table_age_d0 = ap_const_lv8_0;
    end
end

/// forward_table_age_we0 assign process. ///
always @ (ap_CS_fsm or icmp_fu_251_p2 or icmp_reg_389 or tmp_2_reg_403)
begin
    if (((ap_ST_st5_fsm_5 == ap_CS_fsm) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp_fu_251_p2)) | (ap_ST_st6_fsm_6 == ap_CS_fsm) | ((ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == icmp_reg_389) & ~(ap_const_lv1_0 == tmp_2_reg_403)))) begin
        forward_table_age_we0 = ap_const_logic_1;
    end else begin
        forward_table_age_we0 = ap_const_logic_0;
    end
end

/// forward_table_macid_address0 assign process. ///
always @ (ap_CS_fsm or p_cast_fu_234_p1 or icmp_fu_251_p2 or tmp_5_fu_263_p1 or tmp_10_fu_338_p1)
begin
    if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        forward_table_macid_address0 = tmp_10_fu_338_p1;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp_fu_251_p2))) begin
        forward_table_macid_address0 = tmp_5_fu_263_p1;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == icmp_fu_251_p2))) begin
        forward_table_macid_address0 = p_cast_fu_234_p1;
    end else begin
        forward_table_macid_address0 = tmp_10_fu_338_p1;
    end
end

/// forward_table_macid_ce0 assign process. ///
always @ (ap_CS_fsm or icmp_fu_251_p2)
begin
    if ((((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == icmp_fu_251_p2)) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp_fu_251_p2)) | (ap_ST_st6_fsm_6 == ap_CS_fsm))) begin
        forward_table_macid_ce0 = ap_const_logic_1;
    end else begin
        forward_table_macid_ce0 = ap_const_logic_0;
    end
end

/// forward_table_macid_we0 assign process. ///
always @ (ap_CS_fsm or icmp_fu_251_p2)
begin
    if ((((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp_fu_251_p2)) | (ap_ST_st6_fsm_6 == ap_CS_fsm))) begin
        forward_table_macid_we0 = ap_const_logic_1;
    end else begin
        forward_table_macid_we0 = ap_const_logic_0;
    end
end

/// forward_table_portid_address0 assign process. ///
always @ (ap_CS_fsm or icmp_fu_251_p2 or icmp_reg_389 or tmp_2_fu_270_p2 or tmp_2_reg_403 or p_lcssa1_cast_fu_299_p1 or forward_table_portid_addr_1_reg_430 or tmp_4_reg_450 or tmp_5_fu_263_p1 or tmp_10_fu_338_p1)
begin
    if (((ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == icmp_reg_389) & ~(ap_const_lv1_0 == tmp_2_reg_403) & (ap_const_lv1_0 == tmp_4_reg_450))) begin
        forward_table_portid_address0 = forward_table_portid_addr_1_reg_430;
    end else if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        forward_table_portid_address0 = tmp_10_fu_338_p1;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp_fu_251_p2))) begin
        forward_table_portid_address0 = tmp_5_fu_263_p1;
    end else if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_2_fu_270_p2))) begin
        forward_table_portid_address0 = p_lcssa1_cast_fu_299_p1;
    end else begin
        forward_table_portid_address0 = tmp_10_fu_338_p1;
    end
end

/// forward_table_portid_ce0 assign process. ///
always @ (ap_CS_fsm or icmp_fu_251_p2 or icmp_reg_389 or tmp_2_fu_270_p2 or tmp_2_reg_403 or tmp_4_reg_450)
begin
    if ((((ap_ST_st3_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_2_fu_270_p2)) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp_fu_251_p2)) | (ap_ST_st6_fsm_6 == ap_CS_fsm) | ((ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == icmp_reg_389) & ~(ap_const_lv1_0 == tmp_2_reg_403) & (ap_const_lv1_0 == tmp_4_reg_450)))) begin
        forward_table_portid_ce0 = ap_const_logic_1;
    end else begin
        forward_table_portid_ce0 = ap_const_logic_0;
    end
end

/// forward_table_portid_we0 assign process. ///
always @ (ap_CS_fsm or icmp_fu_251_p2 or icmp_reg_389 or tmp_2_reg_403 or tmp_4_reg_450)
begin
    if ((((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == icmp_fu_251_p2)) | (ap_ST_st6_fsm_6 == ap_CS_fsm) | ((ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == icmp_reg_389) & ~(ap_const_lv1_0 == tmp_2_reg_403) & (ap_const_lv1_0 == tmp_4_reg_450)))) begin
        forward_table_portid_we0 = ap_const_logic_1;
    end else begin
        forward_table_portid_we0 = ap_const_logic_0;
    end
end
assign brmerge_fu_283_p2 = (tmp_14_fu_275_p3 | start_aging_tmp_1_reg_191);
assign forward_table_macid_d0 = srcmac;
assign forward_table_portid_addr_1_reg_4300 = {{62{1'b0}}, {p_cast1_reg_379}};
assign forward_table_portid_d0 = portid;
assign icmp_fu_251_p2 = (tmp_13_fu_247_p1 == ap_const_lv2_1? 1'b1: 1'b0);
assign mostaged_index_tmp_1_phi_fu_183_p4 = mostaged_index_tmp_1_reg_179;
assign p_cast_fu_234_p1 = {{61{1'b0}}, {tmp_reg_168}};
assign p_lcssa1_cast_fu_299_p1 = {{62{1'b0}}, {p_cast1_reg_379}};
assign start_aging_tmp_1_phi_fu_196_p4 = start_aging_tmp_1_reg_191;
assign tmp_10_fu_338_p1 = {{61{1'b0}}, {mostaged_index_tmp_1_reg_179}};
assign tmp_12_fu_239_p3 = tmp_reg_168[ap_const_lv32_2];
assign tmp_13_fu_247_p1 = {{1{1'b0}}, {tmp_12_fu_239_p3}};
assign tmp_14_fu_275_p3 = mostaged_index_tmp_1_reg_179[ap_const_lv32_2];
assign tmp_2_fu_270_p2 = (forward_table_macid_q0 == srcmac? 1'b1: 1'b0);
assign tmp_3_fu_319_p1 = tmp_7_fu_303_p2[1:0];
assign tmp_5_fu_263_p1 = {{61{1'b0}}, {mostaged_index_tmp_1_reg_179}};
assign tmp_7_fu_303_p2 = (forward_table_age_q0 + ap_const_lv8_1);
assign tmp_8_fu_309_p1 = {{6{1'b0}}, {mostaged_1_reg_205}};
assign tmp_9_fu_313_p2 = (tmp_7_fu_303_p2 > tmp_8_fu_309_p1? 1'b1: 1'b0);
always @ (ap_clk)
begin
    p_cast_reg_384[3] <= 1'b0;
    p_cast_reg_384[4] <= 1'b0;
    p_cast_reg_384[5] <= 1'b0;
    p_cast_reg_384[6] <= 1'b0;
    p_cast_reg_384[7] <= 1'b0;
    p_cast_reg_384[8] <= 1'b0;
    p_cast_reg_384[9] <= 1'b0;
    p_cast_reg_384[10] <= 1'b0;
    p_cast_reg_384[11] <= 1'b0;
    p_cast_reg_384[12] <= 1'b0;
    p_cast_reg_384[13] <= 1'b0;
    p_cast_reg_384[14] <= 1'b0;
    p_cast_reg_384[15] <= 1'b0;
    p_cast_reg_384[16] <= 1'b0;
    p_cast_reg_384[17] <= 1'b0;
    p_cast_reg_384[18] <= 1'b0;
    p_cast_reg_384[19] <= 1'b0;
    p_cast_reg_384[20] <= 1'b0;
    p_cast_reg_384[21] <= 1'b0;
    p_cast_reg_384[22] <= 1'b0;
    p_cast_reg_384[23] <= 1'b0;
    p_cast_reg_384[24] <= 1'b0;
    p_cast_reg_384[25] <= 1'b0;
    p_cast_reg_384[26] <= 1'b0;
    p_cast_reg_384[27] <= 1'b0;
    p_cast_reg_384[28] <= 1'b0;
    p_cast_reg_384[29] <= 1'b0;
    p_cast_reg_384[30] <= 1'b0;
    p_cast_reg_384[31] <= 1'b0;
    p_cast_reg_384[32] <= 1'b0;
    p_cast_reg_384[33] <= 1'b0;
    p_cast_reg_384[34] <= 1'b0;
    p_cast_reg_384[35] <= 1'b0;
    p_cast_reg_384[36] <= 1'b0;
    p_cast_reg_384[37] <= 1'b0;
    p_cast_reg_384[38] <= 1'b0;
    p_cast_reg_384[39] <= 1'b0;
    p_cast_reg_384[40] <= 1'b0;
    p_cast_reg_384[41] <= 1'b0;
    p_cast_reg_384[42] <= 1'b0;
    p_cast_reg_384[43] <= 1'b0;
    p_cast_reg_384[44] <= 1'b0;
    p_cast_reg_384[45] <= 1'b0;
    p_cast_reg_384[46] <= 1'b0;
    p_cast_reg_384[47] <= 1'b0;
    p_cast_reg_384[48] <= 1'b0;
    p_cast_reg_384[49] <= 1'b0;
    p_cast_reg_384[50] <= 1'b0;
    p_cast_reg_384[51] <= 1'b0;
    p_cast_reg_384[52] <= 1'b0;
    p_cast_reg_384[53] <= 1'b0;
    p_cast_reg_384[54] <= 1'b0;
    p_cast_reg_384[55] <= 1'b0;
    p_cast_reg_384[56] <= 1'b0;
    p_cast_reg_384[57] <= 1'b0;
    p_cast_reg_384[58] <= 1'b0;
    p_cast_reg_384[59] <= 1'b0;
    p_cast_reg_384[60] <= 1'b0;
    p_cast_reg_384[61] <= 1'b0;
    p_cast_reg_384[62] <= 1'b0;
    p_cast_reg_384[63] <= 1'b0;
end

always @ (ap_clk)
begin
    p_lcssa1_cast_reg_425[2] <= 1'b0;
    p_lcssa1_cast_reg_425[3] <= 1'b0;
    p_lcssa1_cast_reg_425[4] <= 1'b0;
    p_lcssa1_cast_reg_425[5] <= 1'b0;
    p_lcssa1_cast_reg_425[6] <= 1'b0;
    p_lcssa1_cast_reg_425[7] <= 1'b0;
    p_lcssa1_cast_reg_425[8] <= 1'b0;
    p_lcssa1_cast_reg_425[9] <= 1'b0;
    p_lcssa1_cast_reg_425[10] <= 1'b0;
    p_lcssa1_cast_reg_425[11] <= 1'b0;
    p_lcssa1_cast_reg_425[12] <= 1'b0;
    p_lcssa1_cast_reg_425[13] <= 1'b0;
    p_lcssa1_cast_reg_425[14] <= 1'b0;
    p_lcssa1_cast_reg_425[15] <= 1'b0;
    p_lcssa1_cast_reg_425[16] <= 1'b0;
    p_lcssa1_cast_reg_425[17] <= 1'b0;
    p_lcssa1_cast_reg_425[18] <= 1'b0;
    p_lcssa1_cast_reg_425[19] <= 1'b0;
    p_lcssa1_cast_reg_425[20] <= 1'b0;
    p_lcssa1_cast_reg_425[21] <= 1'b0;
    p_lcssa1_cast_reg_425[22] <= 1'b0;
    p_lcssa1_cast_reg_425[23] <= 1'b0;
    p_lcssa1_cast_reg_425[24] <= 1'b0;
    p_lcssa1_cast_reg_425[25] <= 1'b0;
    p_lcssa1_cast_reg_425[26] <= 1'b0;
    p_lcssa1_cast_reg_425[27] <= 1'b0;
    p_lcssa1_cast_reg_425[28] <= 1'b0;
    p_lcssa1_cast_reg_425[29] <= 1'b0;
    p_lcssa1_cast_reg_425[30] <= 1'b0;
    p_lcssa1_cast_reg_425[31] <= 1'b0;
    p_lcssa1_cast_reg_425[32] <= 1'b0;
    p_lcssa1_cast_reg_425[33] <= 1'b0;
    p_lcssa1_cast_reg_425[34] <= 1'b0;
    p_lcssa1_cast_reg_425[35] <= 1'b0;
    p_lcssa1_cast_reg_425[36] <= 1'b0;
    p_lcssa1_cast_reg_425[37] <= 1'b0;
    p_lcssa1_cast_reg_425[38] <= 1'b0;
    p_lcssa1_cast_reg_425[39] <= 1'b0;
    p_lcssa1_cast_reg_425[40] <= 1'b0;
    p_lcssa1_cast_reg_425[41] <= 1'b0;
    p_lcssa1_cast_reg_425[42] <= 1'b0;
    p_lcssa1_cast_reg_425[43] <= 1'b0;
    p_lcssa1_cast_reg_425[44] <= 1'b0;
    p_lcssa1_cast_reg_425[45] <= 1'b0;
    p_lcssa1_cast_reg_425[46] <= 1'b0;
    p_lcssa1_cast_reg_425[47] <= 1'b0;
    p_lcssa1_cast_reg_425[48] <= 1'b0;
    p_lcssa1_cast_reg_425[49] <= 1'b0;
    p_lcssa1_cast_reg_425[50] <= 1'b0;
    p_lcssa1_cast_reg_425[51] <= 1'b0;
    p_lcssa1_cast_reg_425[52] <= 1'b0;
    p_lcssa1_cast_reg_425[53] <= 1'b0;
    p_lcssa1_cast_reg_425[54] <= 1'b0;
    p_lcssa1_cast_reg_425[55] <= 1'b0;
    p_lcssa1_cast_reg_425[56] <= 1'b0;
    p_lcssa1_cast_reg_425[57] <= 1'b0;
    p_lcssa1_cast_reg_425[58] <= 1'b0;
    p_lcssa1_cast_reg_425[59] <= 1'b0;
    p_lcssa1_cast_reg_425[60] <= 1'b0;
    p_lcssa1_cast_reg_425[61] <= 1'b0;
    p_lcssa1_cast_reg_425[62] <= 1'b0;
    p_lcssa1_cast_reg_425[63] <= 1'b0;
end



endmodule //eth_learning_aging

