// ==============================================================
// RTL generated by AutoPilot - High-Level Synthesis System (C, C++, SystemC)
// Version: 2010.b.1
// Copyright (C) :2006-2010 AutoESL Design Technologies, Inc.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module input_4port_mux (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        packet_in_data0_dout,
        packet_in_data0_empty_n,
        packet_in_data0_read,
        packet_in_data1_dout,
        packet_in_data1_empty_n,
        packet_in_data1_read,
        packet_in_data2_dout,
        packet_in_data2_empty_n,
        packet_in_data2_read,
        packet_in_data3_dout,
        packet_in_data3_empty_n,
        packet_in_data3_read,
        packet_out_data_address0,
        packet_out_data_ce0,
        packet_out_data_we0,
        packet_out_data_d0,
        ap_return
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
input  [7:0] packet_in_data0_dout;
input   packet_in_data0_empty_n;
output   packet_in_data0_read;
input  [7:0] packet_in_data1_dout;
input   packet_in_data1_empty_n;
output   packet_in_data1_read;
input  [7:0] packet_in_data2_dout;
input   packet_in_data2_empty_n;
output   packet_in_data2_read;
input  [7:0] packet_in_data3_dout;
input   packet_in_data3_empty_n;
output   packet_in_data3_read;
output  [10:0] packet_out_data_address0;
output   packet_out_data_ce0;
output   packet_out_data_we0;
output  [7:0] packet_out_data_d0;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg packet_in_data0_read;
reg packet_in_data1_read;
reg packet_in_data2_read;
reg packet_in_data3_read;
reg[10:0] packet_out_data_address0;
reg packet_out_data_ce0;
reg packet_out_data_we0;
reg[7:0] packet_out_data_d0;
reg   [1:0] ap_CS_fsm;
reg   [1:0] next_token;
reg   [0:0] tmp_3_reg_541;
reg   [0:0] tmp_6_reg_545;
reg   [0:0] tmp_9_reg_549;
reg   [0:0] tmp_s_reg_553;
wire   [0:0] tmp_fu_213_p2;
wire   [0:0] tmp_2_fu_236_p2;
reg    ap_sig_bdd_86;
reg   [10:0] i_reg_143;
wire   [63:0] tmp_14_fu_242_p1;
wire   [63:0] tmp_10_fu_311_p1;
wire   [63:0] tmp_8_fu_380_p1;
wire   [63:0] tmp_4_fu_449_p1;
reg   [15:0] packet_len_2_fu_58;
reg   [31:0] input_portid_1_fu_62;
wire   [0:0] grp_fu_166_p2;
wire   [0:0] grp_fu_172_p2;
wire   [16:0] tmp_1_cast_fu_232_p1;
wire   [16:0] i_cast2_fu_228_p1;
wire   [3:0] tmp_15_fu_247_p1;
wire   [0:0] tmp_19_cast1_fu_257_p1;
wire   [3:0] tmp_17_fu_261_p5;
wire   [3:0] tmp_19_cast_fu_251_p2;
wire   [31:0] tmp_21_cast_fu_277_p1;
wire   [31:0] tmp_20_cast_fu_273_p1;
wire   [0:0] grp_fu_178_p2;
wire   [15:0] p_6_fu_281_p5;
wire   [3:0] tmp_11_fu_316_p1;
wire   [0:0] tmp_15_cast1_fu_326_p1;
wire   [3:0] tmp_16_fu_330_p5;
wire   [3:0] tmp_15_cast_fu_320_p2;
wire   [31:0] tmp_17_cast_fu_346_p1;
wire   [31:0] tmp_16_cast_fu_342_p1;
wire   [15:0] p_4_fu_350_p5;
wire   [3:0] tmp_5_fu_385_p1;
wire   [0:0] tmp_10_cast1_fu_395_p1;
wire   [3:0] tmp_13_fu_399_p5;
wire   [3:0] tmp_10_cast_fu_389_p2;
wire   [31:0] tmp_12_cast_fu_415_p1;
wire   [31:0] tmp_11_cast_fu_411_p1;
wire   [15:0] p_2_fu_419_p5;
wire   [3:0] tmp_1_fu_454_p1;
wire   [0:0] tmp_cast5_fu_464_p1;
wire   [3:0] tmp_12_fu_468_p5;
wire   [3:0] tmp_cast_fu_458_p2;
wire   [31:0] tmp_7_cast_fu_484_p1;
wire   [31:0] tmp_5_cast_fu_480_p1;
wire   [15:0] p_0_fu_488_p5;
reg   [1:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st0_fsm_0 = 2'b00;
parameter    ap_ST_st1_fsm_1 = 2'b01;
parameter    ap_ST_st2_fsm_2 = 2'b10;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv2_1 = 2'b01;
parameter    ap_const_lv16_10 = 16'b0000000000010000;
parameter    ap_const_lv32_3 = 32'b00000000000000000000000000000011;
parameter    ap_const_lv32_2 = 32'b00000000000000000000000000000010;
parameter    ap_const_lv32_1 = 32'b00000000000000000000000000000001;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv11_C = 11'b00000001100;
parameter    ap_const_lv11_D = 11'b00000001101;
parameter    ap_const_lv11_5EE = 11'b10111101110;
parameter    ap_const_lv11_1 = 11'b00000000001;
parameter    ap_const_lv4_3 = 4'b0011;
parameter    ap_const_lv4_7 = 4'b0111;
parameter    ap_true = 1'b1;




/// ap_CS_fsm assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// next_token assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_next_token
    if (ap_rst == 1'b1) begin
        next_token <= ap_const_lv2_0;
    end else begin
        if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & ~(tmp_3_reg_541 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
            next_token <= ap_const_lv2_1;
        end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & ~(tmp_6_reg_545 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
            next_token <= ap_const_lv2_2;
        end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & ~(tmp_9_reg_549 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
            next_token <= ap_const_lv2_3;
        end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & (tmp_9_reg_549 == ap_const_lv1_0) & ~(tmp_s_reg_553 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
            next_token <= ap_const_lv2_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & (tmp_9_reg_549 == ap_const_lv1_0) & ~(tmp_s_reg_553 == ap_const_lv1_0) & ~ap_sig_bdd_86) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & (tmp_9_reg_549 == ap_const_lv1_0) & (tmp_s_reg_553 == ap_const_lv1_0) & ~ap_sig_bdd_86) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & ~(tmp_9_reg_549 == ap_const_lv1_0) & ~ap_sig_bdd_86) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & ~(tmp_6_reg_545 == ap_const_lv1_0) & ~ap_sig_bdd_86) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & ~(tmp_3_reg_541 == ap_const_lv1_0) & ~ap_sig_bdd_86))) begin
        i_reg_143 <= (i_reg_143 + ap_const_lv11_1);
    end else if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        i_reg_143 <= ap_const_lv11_0;
    end
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & ~(tmp_3_reg_541 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        input_portid_1_fu_62[0] <= 1'b0;
        input_portid_1_fu_62[1] <= 1'b0;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & ~(tmp_6_reg_545 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        input_portid_1_fu_62[0] <= 1'b1;
        input_portid_1_fu_62[1] <= 1'b0;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & ~(tmp_9_reg_549 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        input_portid_1_fu_62[0] <= 1'b0;
        input_portid_1_fu_62[1] <= 1'b1;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & (tmp_9_reg_549 == ap_const_lv1_0) & ~(tmp_s_reg_553 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        input_portid_1_fu_62[0] <= 1'b1;
        input_portid_1_fu_62[1] <= 1'b1;
    end
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & ~(tmp_3_reg_541 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        if (grp_fu_178_p2) begin
            packet_len_2_fu_58 <= p_0_fu_488_p5;
        end else begin
            packet_len_2_fu_58 <= packet_len_2_fu_58;
        end

    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & ~(tmp_6_reg_545 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        if (grp_fu_178_p2) begin
            packet_len_2_fu_58 <= p_2_fu_419_p5;
        end else begin
            packet_len_2_fu_58 <= packet_len_2_fu_58;
        end

    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & ~(tmp_9_reg_549 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        if (grp_fu_178_p2) begin
            packet_len_2_fu_58 <= p_4_fu_350_p5;
        end else begin
            packet_len_2_fu_58 <= packet_len_2_fu_58;
        end

    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & (tmp_9_reg_549 == ap_const_lv1_0) & ~(tmp_s_reg_553 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        if (grp_fu_178_p2) begin
            packet_len_2_fu_58 <= p_6_fu_281_p5;
        end else begin
            packet_len_2_fu_58 <= packet_len_2_fu_58;
        end

    end else if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        packet_len_2_fu_58 <= ap_const_lv16_10;
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_3_reg_541 <= (next_token == ap_const_lv2_0? 1'b1: 1'b0);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_6_reg_545 <= (next_token == ap_const_lv2_1? 1'b1: 1'b0);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_9_reg_549 <= (next_token == ap_const_lv2_2? 1'b1: 1'b0);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_s_reg_553 <= (next_token == ap_const_lv2_3? 1'b1: 1'b0);
    end
end

/// ap_NS_fsm assign process. ///
always @ (ap_start or ap_CS_fsm or tmp_fu_213_p2 or tmp_2_fu_236_p2 or ap_sig_bdd_86)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~ap_sig_bdd_86 & ((tmp_fu_213_p2 == ap_const_lv1_0) | ~(ap_const_lv1_0 == tmp_2_fu_236_p2)) & ~(ap_const_logic_1 == ap_start))) begin
        ap_NS_fsm = ap_ST_st0_fsm_0;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & ~ap_sig_bdd_86))) begin
        ap_NS_fsm = ap_ST_st2_fsm_2;
    end else if ((((ap_ST_st0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_start)) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~ap_sig_bdd_86 & ((tmp_fu_213_p2 == ap_const_lv1_0) | ~(ap_const_lv1_0 == tmp_2_fu_236_p2)) & (ap_const_logic_1 == ap_start)))) begin
        ap_NS_fsm = ap_ST_st1_fsm_1;
    end else begin
        ap_NS_fsm = ap_CS_fsm;
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm or tmp_fu_213_p2 or tmp_2_fu_236_p2 or ap_sig_bdd_86)
begin
    if (((ap_ST_st0_fsm_0 == ap_CS_fsm) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~ap_sig_bdd_86 & ((tmp_fu_213_p2 == ap_const_lv1_0) | ~(ap_const_lv1_0 == tmp_2_fu_236_p2))))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st0_fsm_0 == ap_CS_fsm)) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// packet_in_data0_read assign process. ///
always @ (ap_CS_fsm or tmp_3_reg_541 or tmp_fu_213_p2 or tmp_2_fu_236_p2 or ap_sig_bdd_86)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & ~(tmp_3_reg_541 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        packet_in_data0_read = ap_const_logic_1;
    end else begin
        packet_in_data0_read = ap_const_logic_0;
    end
end

/// packet_in_data1_read assign process. ///
always @ (ap_CS_fsm or tmp_3_reg_541 or tmp_6_reg_545 or tmp_fu_213_p2 or tmp_2_fu_236_p2 or ap_sig_bdd_86)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & ~(tmp_6_reg_545 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        packet_in_data1_read = ap_const_logic_1;
    end else begin
        packet_in_data1_read = ap_const_logic_0;
    end
end

/// packet_in_data2_read assign process. ///
always @ (ap_CS_fsm or tmp_3_reg_541 or tmp_6_reg_545 or tmp_9_reg_549 or tmp_fu_213_p2 or tmp_2_fu_236_p2 or ap_sig_bdd_86)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & ~(tmp_9_reg_549 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        packet_in_data2_read = ap_const_logic_1;
    end else begin
        packet_in_data2_read = ap_const_logic_0;
    end
end

/// packet_in_data3_read assign process. ///
always @ (ap_CS_fsm or tmp_3_reg_541 or tmp_6_reg_545 or tmp_9_reg_549 or tmp_s_reg_553 or tmp_fu_213_p2 or tmp_2_fu_236_p2 or ap_sig_bdd_86)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & (tmp_9_reg_549 == ap_const_lv1_0) & ~(tmp_s_reg_553 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        packet_in_data3_read = ap_const_logic_1;
    end else begin
        packet_in_data3_read = ap_const_logic_0;
    end
end

/// packet_out_data_address0 assign process. ///
always @ (ap_CS_fsm or tmp_3_reg_541 or tmp_6_reg_545 or tmp_9_reg_549 or tmp_s_reg_553 or tmp_fu_213_p2 or tmp_2_fu_236_p2 or ap_sig_bdd_86 or tmp_14_fu_242_p1 or tmp_10_fu_311_p1 or tmp_8_fu_380_p1 or tmp_4_fu_449_p1)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & ~(tmp_3_reg_541 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        packet_out_data_address0 = tmp_4_fu_449_p1;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & ~(tmp_6_reg_545 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        packet_out_data_address0 = tmp_8_fu_380_p1;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & ~(tmp_9_reg_549 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        packet_out_data_address0 = tmp_10_fu_311_p1;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & (tmp_9_reg_549 == ap_const_lv1_0) & ~(tmp_s_reg_553 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        packet_out_data_address0 = tmp_14_fu_242_p1;
    end else begin
        packet_out_data_address0 = tmp_4_fu_449_p1;
    end
end

/// packet_out_data_ce0 assign process. ///
always @ (ap_CS_fsm or tmp_3_reg_541 or tmp_6_reg_545 or tmp_9_reg_549 or tmp_s_reg_553 or tmp_fu_213_p2 or tmp_2_fu_236_p2 or ap_sig_bdd_86)
begin
    if ((((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & (tmp_9_reg_549 == ap_const_lv1_0) & ~(tmp_s_reg_553 == ap_const_lv1_0) & ~ap_sig_bdd_86) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & ~(tmp_9_reg_549 == ap_const_lv1_0) & ~ap_sig_bdd_86) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & ~(tmp_6_reg_545 == ap_const_lv1_0) & ~ap_sig_bdd_86) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & ~(tmp_3_reg_541 == ap_const_lv1_0) & ~ap_sig_bdd_86))) begin
        packet_out_data_ce0 = ap_const_logic_1;
    end else begin
        packet_out_data_ce0 = ap_const_logic_0;
    end
end

/// packet_out_data_d0 assign process. ///
always @ (ap_CS_fsm or packet_in_data0_dout or packet_in_data1_dout or packet_in_data2_dout or packet_in_data3_dout or tmp_3_reg_541 or tmp_6_reg_545 or tmp_9_reg_549 or tmp_s_reg_553 or tmp_fu_213_p2 or tmp_2_fu_236_p2 or ap_sig_bdd_86)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & ~(tmp_3_reg_541 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        packet_out_data_d0 = packet_in_data0_dout;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & ~(tmp_6_reg_545 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        packet_out_data_d0 = packet_in_data1_dout;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & ~(tmp_9_reg_549 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        packet_out_data_d0 = packet_in_data2_dout;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & (tmp_9_reg_549 == ap_const_lv1_0) & ~(tmp_s_reg_553 == ap_const_lv1_0) & ~ap_sig_bdd_86)) begin
        packet_out_data_d0 = packet_in_data3_dout;
    end else begin
        packet_out_data_d0 = packet_in_data0_dout;
    end
end

/// packet_out_data_we0 assign process. ///
always @ (ap_CS_fsm or tmp_3_reg_541 or tmp_6_reg_545 or tmp_9_reg_549 or tmp_s_reg_553 or tmp_fu_213_p2 or tmp_2_fu_236_p2 or ap_sig_bdd_86)
begin
    if ((((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & (tmp_9_reg_549 == ap_const_lv1_0) & ~(tmp_s_reg_553 == ap_const_lv1_0) & ~ap_sig_bdd_86) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & ~(tmp_9_reg_549 == ap_const_lv1_0) & ~ap_sig_bdd_86) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & ~(tmp_6_reg_545 == ap_const_lv1_0) & ~ap_sig_bdd_86) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & ~(tmp_3_reg_541 == ap_const_lv1_0) & ~ap_sig_bdd_86))) begin
        packet_out_data_we0 = ap_const_logic_1;
    end else begin
        packet_out_data_we0 = ap_const_logic_0;
    end
end
assign ap_return = input_portid_1_fu_62;

/// ap_sig_bdd_86 assign process. ///
always @ (packet_in_data0_empty_n or packet_in_data1_empty_n or packet_in_data2_empty_n or packet_in_data3_empty_n or tmp_3_reg_541 or tmp_6_reg_545 or tmp_9_reg_549 or tmp_s_reg_553 or tmp_fu_213_p2 or tmp_2_fu_236_p2)
begin
    ap_sig_bdd_86 = (((packet_in_data3_empty_n == ap_const_logic_0) & ~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & (tmp_9_reg_549 == ap_const_lv1_0) & ~(tmp_s_reg_553 == ap_const_lv1_0)) | (~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (tmp_6_reg_545 == ap_const_lv1_0) & (packet_in_data2_empty_n == ap_const_logic_0) & ~(tmp_9_reg_549 == ap_const_lv1_0)) | (~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (tmp_3_reg_541 == ap_const_lv1_0) & (packet_in_data1_empty_n == ap_const_logic_0) & ~(tmp_6_reg_545 == ap_const_lv1_0)) | (~(tmp_fu_213_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_236_p2) & (packet_in_data0_empty_n == ap_const_logic_0) & ~(tmp_3_reg_541 == ap_const_lv1_0)));
end
assign grp_fu_166_p2 = (i_reg_143 == ap_const_lv11_C? 1'b1: 1'b0);
assign grp_fu_172_p2 = (i_reg_143 == ap_const_lv11_D? 1'b1: 1'b0);
assign grp_fu_178_p2 = (grp_fu_166_p2 | grp_fu_172_p2);
assign i_cast2_fu_228_p1 = {{6{1'b0}}, {i_reg_143}};
wire [4-1:0] p_0_fu_488_p5_vHi_buf;
wire [4-1:0] p_0_fu_488_p5_vLo_buf;
wire [16-1:0] p_0_fu_488_p5_v1_buf;
wire [16-1:0] p_0_fu_488_p5_v1_buf_r;
wire [16-1:0] p_0_fu_488_p5_v1_tmp;
wire [4-1:0] p_0_fu_488_p5_v1_shift;
wire [16-1:0] p_0_fu_488_p5_mask0;
wire [16-1:0] p_0_fu_488_p5_mask1;
wire [16-1:0] p_0_fu_488_p5_mask2;

genvar ap_tvar_int_0;
generate
    for (ap_tvar_int_0 = 0; ap_tvar_int_0 < 16; ap_tvar_int_0 = ap_tvar_int_0 + 1) begin :p_0_fu_488_p5_label0
        assign p_0_fu_488_p5_v1_buf_r[ap_tvar_int_0] = p_0_fu_488_p5_v1_buf[16-1-ap_tvar_int_0];
    end
endgenerate

assign p_0_fu_488_p5_vHi_buf = (tmp_5_cast_fu_480_p1 >= tmp_7_cast_fu_484_p1)? tmp_5_cast_fu_480_p1 : tmp_7_cast_fu_484_p1;
assign p_0_fu_488_p5_vLo_buf = (tmp_5_cast_fu_480_p1 >= tmp_7_cast_fu_484_p1)? tmp_7_cast_fu_484_p1 : tmp_5_cast_fu_480_p1;
assign p_0_fu_488_p5_v1_buf = packet_in_data0_dout;
assign p_0_fu_488_p5_v1_shift = (tmp_5_cast_fu_480_p1 >= tmp_7_cast_fu_484_p1)? tmp_7_cast_fu_484_p1 : (16-1-tmp_7_cast_fu_484_p1);
assign p_0_fu_488_p5_v1_tmp = (tmp_5_cast_fu_480_p1 >= tmp_7_cast_fu_484_p1)? (p_0_fu_488_p5_v1_buf << p_0_fu_488_p5_v1_shift) : (p_0_fu_488_p5_v1_buf_r >> p_0_fu_488_p5_v1_shift);
assign p_0_fu_488_p5_mask0 = {{(16-1){1'b1}}, 1'b0} << p_0_fu_488_p5_vHi_buf;
assign p_0_fu_488_p5_mask1 = ~({(16){1'b1}} << p_0_fu_488_p5_vLo_buf);
assign p_0_fu_488_p5_mask2 = p_0_fu_488_p5_mask0 | p_0_fu_488_p5_mask1;
assign p_0_fu_488_p5 = (packet_len_2_fu_58 & p_0_fu_488_p5_mask2) | (p_0_fu_488_p5_v1_tmp & ~p_0_fu_488_p5_mask2);

wire [4-1:0] p_2_fu_419_p5_vHi_buf;
wire [4-1:0] p_2_fu_419_p5_vLo_buf;
wire [16-1:0] p_2_fu_419_p5_v1_buf;
wire [16-1:0] p_2_fu_419_p5_v1_buf_r;
wire [16-1:0] p_2_fu_419_p5_v1_tmp;
wire [4-1:0] p_2_fu_419_p5_v1_shift;
wire [16-1:0] p_2_fu_419_p5_mask0;
wire [16-1:0] p_2_fu_419_p5_mask1;
wire [16-1:0] p_2_fu_419_p5_mask2;

genvar ap_tvar_int_1;
generate
    for (ap_tvar_int_1 = 0; ap_tvar_int_1 < 16; ap_tvar_int_1 = ap_tvar_int_1 + 1) begin :p_2_fu_419_p5_label0
        assign p_2_fu_419_p5_v1_buf_r[ap_tvar_int_1] = p_2_fu_419_p5_v1_buf[16-1-ap_tvar_int_1];
    end
endgenerate

assign p_2_fu_419_p5_vHi_buf = (tmp_11_cast_fu_411_p1 >= tmp_12_cast_fu_415_p1)? tmp_11_cast_fu_411_p1 : tmp_12_cast_fu_415_p1;
assign p_2_fu_419_p5_vLo_buf = (tmp_11_cast_fu_411_p1 >= tmp_12_cast_fu_415_p1)? tmp_12_cast_fu_415_p1 : tmp_11_cast_fu_411_p1;
assign p_2_fu_419_p5_v1_buf = packet_in_data1_dout;
assign p_2_fu_419_p5_v1_shift = (tmp_11_cast_fu_411_p1 >= tmp_12_cast_fu_415_p1)? tmp_12_cast_fu_415_p1 : (16-1-tmp_12_cast_fu_415_p1);
assign p_2_fu_419_p5_v1_tmp = (tmp_11_cast_fu_411_p1 >= tmp_12_cast_fu_415_p1)? (p_2_fu_419_p5_v1_buf << p_2_fu_419_p5_v1_shift) : (p_2_fu_419_p5_v1_buf_r >> p_2_fu_419_p5_v1_shift);
assign p_2_fu_419_p5_mask0 = {{(16-1){1'b1}}, 1'b0} << p_2_fu_419_p5_vHi_buf;
assign p_2_fu_419_p5_mask1 = ~({(16){1'b1}} << p_2_fu_419_p5_vLo_buf);
assign p_2_fu_419_p5_mask2 = p_2_fu_419_p5_mask0 | p_2_fu_419_p5_mask1;
assign p_2_fu_419_p5 = (packet_len_2_fu_58 & p_2_fu_419_p5_mask2) | (p_2_fu_419_p5_v1_tmp & ~p_2_fu_419_p5_mask2);

wire [4-1:0] p_4_fu_350_p5_vHi_buf;
wire [4-1:0] p_4_fu_350_p5_vLo_buf;
wire [16-1:0] p_4_fu_350_p5_v1_buf;
wire [16-1:0] p_4_fu_350_p5_v1_buf_r;
wire [16-1:0] p_4_fu_350_p5_v1_tmp;
wire [4-1:0] p_4_fu_350_p5_v1_shift;
wire [16-1:0] p_4_fu_350_p5_mask0;
wire [16-1:0] p_4_fu_350_p5_mask1;
wire [16-1:0] p_4_fu_350_p5_mask2;

genvar ap_tvar_int_2;
generate
    for (ap_tvar_int_2 = 0; ap_tvar_int_2 < 16; ap_tvar_int_2 = ap_tvar_int_2 + 1) begin :p_4_fu_350_p5_label0
        assign p_4_fu_350_p5_v1_buf_r[ap_tvar_int_2] = p_4_fu_350_p5_v1_buf[16-1-ap_tvar_int_2];
    end
endgenerate

assign p_4_fu_350_p5_vHi_buf = (tmp_16_cast_fu_342_p1 >= tmp_17_cast_fu_346_p1)? tmp_16_cast_fu_342_p1 : tmp_17_cast_fu_346_p1;
assign p_4_fu_350_p5_vLo_buf = (tmp_16_cast_fu_342_p1 >= tmp_17_cast_fu_346_p1)? tmp_17_cast_fu_346_p1 : tmp_16_cast_fu_342_p1;
assign p_4_fu_350_p5_v1_buf = packet_in_data2_dout;
assign p_4_fu_350_p5_v1_shift = (tmp_16_cast_fu_342_p1 >= tmp_17_cast_fu_346_p1)? tmp_17_cast_fu_346_p1 : (16-1-tmp_17_cast_fu_346_p1);
assign p_4_fu_350_p5_v1_tmp = (tmp_16_cast_fu_342_p1 >= tmp_17_cast_fu_346_p1)? (p_4_fu_350_p5_v1_buf << p_4_fu_350_p5_v1_shift) : (p_4_fu_350_p5_v1_buf_r >> p_4_fu_350_p5_v1_shift);
assign p_4_fu_350_p5_mask0 = {{(16-1){1'b1}}, 1'b0} << p_4_fu_350_p5_vHi_buf;
assign p_4_fu_350_p5_mask1 = ~({(16){1'b1}} << p_4_fu_350_p5_vLo_buf);
assign p_4_fu_350_p5_mask2 = p_4_fu_350_p5_mask0 | p_4_fu_350_p5_mask1;
assign p_4_fu_350_p5 = (packet_len_2_fu_58 & p_4_fu_350_p5_mask2) | (p_4_fu_350_p5_v1_tmp & ~p_4_fu_350_p5_mask2);

wire [4-1:0] p_6_fu_281_p5_vHi_buf;
wire [4-1:0] p_6_fu_281_p5_vLo_buf;
wire [16-1:0] p_6_fu_281_p5_v1_buf;
wire [16-1:0] p_6_fu_281_p5_v1_buf_r;
wire [16-1:0] p_6_fu_281_p5_v1_tmp;
wire [4-1:0] p_6_fu_281_p5_v1_shift;
wire [16-1:0] p_6_fu_281_p5_mask0;
wire [16-1:0] p_6_fu_281_p5_mask1;
wire [16-1:0] p_6_fu_281_p5_mask2;

genvar ap_tvar_int_3;
generate
    for (ap_tvar_int_3 = 0; ap_tvar_int_3 < 16; ap_tvar_int_3 = ap_tvar_int_3 + 1) begin :p_6_fu_281_p5_label0
        assign p_6_fu_281_p5_v1_buf_r[ap_tvar_int_3] = p_6_fu_281_p5_v1_buf[16-1-ap_tvar_int_3];
    end
endgenerate

assign p_6_fu_281_p5_vHi_buf = (tmp_20_cast_fu_273_p1 >= tmp_21_cast_fu_277_p1)? tmp_20_cast_fu_273_p1 : tmp_21_cast_fu_277_p1;
assign p_6_fu_281_p5_vLo_buf = (tmp_20_cast_fu_273_p1 >= tmp_21_cast_fu_277_p1)? tmp_21_cast_fu_277_p1 : tmp_20_cast_fu_273_p1;
assign p_6_fu_281_p5_v1_buf = packet_in_data3_dout;
assign p_6_fu_281_p5_v1_shift = (tmp_20_cast_fu_273_p1 >= tmp_21_cast_fu_277_p1)? tmp_21_cast_fu_277_p1 : (16-1-tmp_21_cast_fu_277_p1);
assign p_6_fu_281_p5_v1_tmp = (tmp_20_cast_fu_273_p1 >= tmp_21_cast_fu_277_p1)? (p_6_fu_281_p5_v1_buf << p_6_fu_281_p5_v1_shift) : (p_6_fu_281_p5_v1_buf_r >> p_6_fu_281_p5_v1_shift);
assign p_6_fu_281_p5_mask0 = {{(16-1){1'b1}}, 1'b0} << p_6_fu_281_p5_vHi_buf;
assign p_6_fu_281_p5_mask1 = ~({(16){1'b1}} << p_6_fu_281_p5_vLo_buf);
assign p_6_fu_281_p5_mask2 = p_6_fu_281_p5_mask0 | p_6_fu_281_p5_mask1;
assign p_6_fu_281_p5 = (packet_len_2_fu_58 & p_6_fu_281_p5_mask2) | (p_6_fu_281_p5_v1_tmp & ~p_6_fu_281_p5_mask2);

assign tmp_10_cast1_fu_395_p1 = tmp_5_fu_385_p1[0:0];
assign tmp_10_cast_fu_389_p2 = tmp_5_fu_385_p1 << ap_const_lv4_3;
assign tmp_10_fu_311_p1 = {{53{1'b0}}, {i_reg_143}};
assign tmp_11_cast_fu_411_p1 = {{28{1'b0}}, {tmp_13_fu_399_p5}};
assign tmp_11_fu_316_p1 = i_reg_143[3:0];
assign tmp_12_cast_fu_415_p1 = {{28{1'b0}}, {tmp_10_cast_fu_389_p2}};
assign tmp_12_fu_468_p5 = {{tmp_cast5_fu_464_p1}, {ap_const_lv4_7[32'd2 : 32'd0]}};
assign tmp_13_fu_399_p5 = {{tmp_10_cast1_fu_395_p1}, {ap_const_lv4_7[32'd2 : 32'd0]}};
assign tmp_14_fu_242_p1 = {{53{1'b0}}, {i_reg_143}};
assign tmp_15_cast1_fu_326_p1 = tmp_11_fu_316_p1[0:0];
assign tmp_15_cast_fu_320_p2 = tmp_11_fu_316_p1 << ap_const_lv4_3;
assign tmp_15_fu_247_p1 = i_reg_143[3:0];
assign tmp_16_cast_fu_342_p1 = {{28{1'b0}}, {tmp_16_fu_330_p5}};
assign tmp_16_fu_330_p5 = {{tmp_15_cast1_fu_326_p1}, {ap_const_lv4_7[32'd2 : 32'd0]}};
assign tmp_17_cast_fu_346_p1 = {{28{1'b0}}, {tmp_15_cast_fu_320_p2}};
assign tmp_17_fu_261_p5 = {{tmp_19_cast1_fu_257_p1}, {ap_const_lv4_7[32'd2 : 32'd0]}};
assign tmp_19_cast1_fu_257_p1 = tmp_15_fu_247_p1[0:0];
assign tmp_19_cast_fu_251_p2 = tmp_15_fu_247_p1 << ap_const_lv4_3;
assign tmp_1_cast_fu_232_p1 = {{1{1'b0}}, {packet_len_2_fu_58}};
assign tmp_1_fu_454_p1 = i_reg_143[3:0];
assign tmp_20_cast_fu_273_p1 = {{28{1'b0}}, {tmp_17_fu_261_p5}};
assign tmp_21_cast_fu_277_p1 = {{28{1'b0}}, {tmp_19_cast_fu_251_p2}};
assign tmp_2_fu_236_p2 = (tmp_1_cast_fu_232_p1 == i_cast2_fu_228_p1? 1'b1: 1'b0);
assign tmp_4_fu_449_p1 = {{53{1'b0}}, {i_reg_143}};
assign tmp_5_cast_fu_480_p1 = {{28{1'b0}}, {tmp_12_fu_468_p5}};
assign tmp_5_fu_385_p1 = i_reg_143[3:0];
assign tmp_7_cast_fu_484_p1 = {{28{1'b0}}, {tmp_cast_fu_458_p2}};
assign tmp_8_fu_380_p1 = {{53{1'b0}}, {i_reg_143}};
assign tmp_cast5_fu_464_p1 = tmp_1_fu_454_p1[0:0];
assign tmp_cast_fu_458_p2 = tmp_1_fu_454_p1 << ap_const_lv4_3;
assign tmp_fu_213_p2 = (i_reg_143 < ap_const_lv11_5EE? 1'b1: 1'b0);
always @ (ap_clk)
begin
    input_portid_1_fu_62[2] <= 1'b0;
    input_portid_1_fu_62[3] <= 1'b0;
    input_portid_1_fu_62[4] <= 1'b0;
    input_portid_1_fu_62[5] <= 1'b0;
    input_portid_1_fu_62[6] <= 1'b0;
    input_portid_1_fu_62[7] <= 1'b0;
    input_portid_1_fu_62[8] <= 1'b0;
    input_portid_1_fu_62[9] <= 1'b0;
    input_portid_1_fu_62[10] <= 1'b0;
    input_portid_1_fu_62[11] <= 1'b0;
    input_portid_1_fu_62[12] <= 1'b0;
    input_portid_1_fu_62[13] <= 1'b0;
    input_portid_1_fu_62[14] <= 1'b0;
    input_portid_1_fu_62[15] <= 1'b0;
    input_portid_1_fu_62[16] <= 1'b0;
    input_portid_1_fu_62[17] <= 1'b0;
    input_portid_1_fu_62[18] <= 1'b0;
    input_portid_1_fu_62[19] <= 1'b0;
    input_portid_1_fu_62[20] <= 1'b0;
    input_portid_1_fu_62[21] <= 1'b0;
    input_portid_1_fu_62[22] <= 1'b0;
    input_portid_1_fu_62[23] <= 1'b0;
    input_portid_1_fu_62[24] <= 1'b0;
    input_portid_1_fu_62[25] <= 1'b0;
    input_portid_1_fu_62[26] <= 1'b0;
    input_portid_1_fu_62[27] <= 1'b0;
    input_portid_1_fu_62[28] <= 1'b0;
    input_portid_1_fu_62[29] <= 1'b0;
    input_portid_1_fu_62[30] <= 1'b0;
    input_portid_1_fu_62[31] <= 1'b0;
end



endmodule //input_4port_mux

