// ==============================================================
// RTL generated by AutoPilot - High-Level Synthesis System (C, C++, SystemC)
// Version: 2010.b.1
// Copyright (C) :2006-2010 AutoESL Design Technologies, Inc.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module layer2_switch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        packet_in_data0_dout,
        packet_in_data0_empty_n,
        packet_in_data0_read,
        packet_in_data1_dout,
        packet_in_data1_empty_n,
        packet_in_data1_read,
        packet_in_data2_dout,
        packet_in_data2_empty_n,
        packet_in_data2_read,
        packet_in_data3_dout,
        packet_in_data3_empty_n,
        packet_in_data3_read,
        packet_out_data0_din,
        packet_out_data0_full_n,
        packet_out_data0_write,
        packet_out_data1_din,
        packet_out_data1_full_n,
        packet_out_data1_write,
        packet_out_data2_din,
        packet_out_data2_full_n,
        packet_out_data2_write,
        packet_out_data3_din,
        packet_out_data3_full_n,
        packet_out_data3_write
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
input  [7:0] packet_in_data0_dout;
input   packet_in_data0_empty_n;
output   packet_in_data0_read;
input  [7:0] packet_in_data1_dout;
input   packet_in_data1_empty_n;
output   packet_in_data1_read;
input  [7:0] packet_in_data2_dout;
input   packet_in_data2_empty_n;
output   packet_in_data2_read;
input  [7:0] packet_in_data3_dout;
input   packet_in_data3_empty_n;
output   packet_in_data3_read;
output  [7:0] packet_out_data0_din;
input   packet_out_data0_full_n;
output   packet_out_data0_write;
output  [7:0] packet_out_data1_din;
input   packet_out_data1_full_n;
output   packet_out_data1_write;
output  [7:0] packet_out_data2_din;
input   packet_out_data2_full_n;
output   packet_out_data2_write;
output  [7:0] packet_out_data3_din;
input   packet_out_data3_full_n;
output   packet_out_data3_write;

reg ap_done;
reg ap_idle;
reg packet_in_data0_read;
reg packet_in_data1_read;
reg packet_in_data2_read;
reg packet_in_data3_read;
reg packet_out_data0_write;
reg packet_out_data1_write;
reg packet_out_data2_write;
reg packet_out_data3_write;
reg   [3:0] ap_CS_fsm;
wire   [1:0] forward_table_macid_address0;
reg    forward_table_macid_ce0;
reg    forward_table_macid_we0;
wire   [47:0] forward_table_macid_d0;
wire   [47:0] forward_table_macid_q0;
wire   [1:0] forward_table_portid_address0;
reg    forward_table_portid_ce0;
reg    forward_table_portid_we0;
wire   [7:0] forward_table_portid_d0;
wire   [7:0] forward_table_portid_q0;
wire   [31:0] grp_input_4port_mux_fu_84_ap_return;
reg   [31:0] input_portid_reg_132;
wire    grp_input_4port_mux_fu_84_ap_done;
reg   [47:0] eth_header_reg_138;
wire    grp_get_eth_header_fu_77_ap_done;
reg   [47:0] eth_header_1_reg_143;
reg   [15:0] eth_header_2_reg_148;
reg   [7:0] eth_header_3_reg_154;
wire   [7:0] grp_eth_switch_fu_57_ap_return;
reg   [7:0] output_portid_assign_1_reg_159;
wire    grp_eth_switch_fu_57_ap_done;
reg   [10:0] packet_out_data_tmp_address0;
reg    packet_out_data_tmp_ce0;
reg    packet_out_data_tmp_we0;
wire   [7:0] packet_out_data_tmp_d0;
wire   [7:0] packet_out_data_tmp_q0;
reg   [10:0] packet_out_data_tmp2_address0;
reg    packet_out_data_tmp2_ce0;
reg    packet_out_data_tmp2_we0;
wire   [7:0] packet_out_data_tmp2_d0;
wire   [7:0] packet_out_data_tmp2_q0;
reg   [10:0] packet_out_data_tmp3_address0;
reg    packet_out_data_tmp3_ce0;
reg    packet_out_data_tmp3_we0;
wire   [7:0] packet_out_data_tmp3_d0;
wire   [7:0] packet_out_data_tmp3_q0;
reg    grp_eth_switch_fu_57_ap_start;
wire    grp_eth_switch_fu_57_ap_idle;
wire   [10:0] grp_eth_switch_fu_57_packet_in_data_address0;
wire    grp_eth_switch_fu_57_packet_in_data_ce0;
wire   [7:0] grp_eth_switch_fu_57_packet_in_data_q0;
wire   [47:0] grp_eth_switch_fu_57_eth_header_0_read;
wire   [47:0] grp_eth_switch_fu_57_eth_header_1_read;
wire   [15:0] grp_eth_switch_fu_57_eth_header_2_read;
wire   [7:0] grp_eth_switch_fu_57_eth_header_3_read;
wire   [10:0] grp_eth_switch_fu_57_packet_out_data_address0;
wire    grp_eth_switch_fu_57_packet_out_data_ce0;
wire    grp_eth_switch_fu_57_packet_out_data_we0;
wire   [7:0] grp_eth_switch_fu_57_packet_out_data_d0;
wire   [1:0] grp_eth_switch_fu_57_forward_table_macid_address0;
wire    grp_eth_switch_fu_57_forward_table_macid_ce0;
wire    grp_eth_switch_fu_57_forward_table_macid_we0;
wire   [47:0] grp_eth_switch_fu_57_forward_table_macid_d0;
wire   [47:0] grp_eth_switch_fu_57_forward_table_macid_q0;
wire   [1:0] grp_eth_switch_fu_57_forward_table_portid_address0;
wire    grp_eth_switch_fu_57_forward_table_portid_ce0;
wire    grp_eth_switch_fu_57_forward_table_portid_we0;
wire   [7:0] grp_eth_switch_fu_57_forward_table_portid_d0;
wire   [7:0] grp_eth_switch_fu_57_forward_table_portid_q0;
reg    grp_get_eth_header_fu_77_ap_start;
wire    grp_get_eth_header_fu_77_ap_idle;
wire   [10:0] grp_get_eth_header_fu_77_packet_in_data_address0;
wire    grp_get_eth_header_fu_77_packet_in_data_ce0;
wire   [7:0] grp_get_eth_header_fu_77_packet_in_data_q0;
wire   [31:0] grp_get_eth_header_fu_77_input_portid_read;
wire   [10:0] grp_get_eth_header_fu_77_packet_out_data_address0;
wire    grp_get_eth_header_fu_77_packet_out_data_ce0;
wire    grp_get_eth_header_fu_77_packet_out_data_we0;
wire   [7:0] grp_get_eth_header_fu_77_packet_out_data_d0;
wire   [47:0] grp_get_eth_header_fu_77_ap_return_0;
wire   [47:0] grp_get_eth_header_fu_77_ap_return_1;
wire   [15:0] grp_get_eth_header_fu_77_ap_return_2;
wire   [7:0] grp_get_eth_header_fu_77_ap_return_3;
reg    grp_input_4port_mux_fu_84_ap_start;
wire    grp_input_4port_mux_fu_84_ap_idle;
wire   [7:0] grp_input_4port_mux_fu_84_packet_in_data0_dout;
wire    grp_input_4port_mux_fu_84_packet_in_data0_empty_n;
wire    grp_input_4port_mux_fu_84_packet_in_data0_read;
wire   [7:0] grp_input_4port_mux_fu_84_packet_in_data1_dout;
wire    grp_input_4port_mux_fu_84_packet_in_data1_empty_n;
wire    grp_input_4port_mux_fu_84_packet_in_data1_read;
wire   [7:0] grp_input_4port_mux_fu_84_packet_in_data2_dout;
wire    grp_input_4port_mux_fu_84_packet_in_data2_empty_n;
wire    grp_input_4port_mux_fu_84_packet_in_data2_read;
wire   [7:0] grp_input_4port_mux_fu_84_packet_in_data3_dout;
wire    grp_input_4port_mux_fu_84_packet_in_data3_empty_n;
wire    grp_input_4port_mux_fu_84_packet_in_data3_read;
wire   [10:0] grp_input_4port_mux_fu_84_packet_out_data_address0;
wire    grp_input_4port_mux_fu_84_packet_out_data_ce0;
wire    grp_input_4port_mux_fu_84_packet_out_data_we0;
wire   [7:0] grp_input_4port_mux_fu_84_packet_out_data_d0;
reg    grp_output_4port_demux_fu_100_ap_start;
wire    grp_output_4port_demux_fu_100_ap_done;
wire    grp_output_4port_demux_fu_100_ap_idle;
wire   [10:0] grp_output_4port_demux_fu_100_packet_in_data_address0;
wire    grp_output_4port_demux_fu_100_packet_in_data_ce0;
wire   [7:0] grp_output_4port_demux_fu_100_packet_in_data_q0;
wire   [31:0] grp_output_4port_demux_fu_100_input_portid_read;
wire   [7:0] grp_output_4port_demux_fu_100_output_portid_read;
wire   [15:0] grp_output_4port_demux_fu_100_packet_len;
wire   [7:0] grp_output_4port_demux_fu_100_packet_out_data0_din;
wire    grp_output_4port_demux_fu_100_packet_out_data0_full_n;
wire    grp_output_4port_demux_fu_100_packet_out_data0_write;
wire   [7:0] grp_output_4port_demux_fu_100_packet_out_data1_din;
wire    grp_output_4port_demux_fu_100_packet_out_data1_full_n;
wire    grp_output_4port_demux_fu_100_packet_out_data1_write;
wire   [7:0] grp_output_4port_demux_fu_100_packet_out_data2_din;
wire    grp_output_4port_demux_fu_100_packet_out_data2_full_n;
wire    grp_output_4port_demux_fu_100_packet_out_data2_write;
wire   [7:0] grp_output_4port_demux_fu_100_packet_out_data3_din;
wire    grp_output_4port_demux_fu_100_packet_out_data3_full_n;
wire    grp_output_4port_demux_fu_100_packet_out_data3_write;
reg   [3:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st0_fsm_0 = 4'b0000;
parameter    ap_ST_st1_fsm_1 = 4'b0001;
parameter    ap_ST_st2_fsm_2 = 4'b0010;
parameter    ap_ST_st3_fsm_3 = 4'b0011;
parameter    ap_ST_st4_fsm_4 = 4'b0100;
parameter    ap_ST_st5_fsm_5 = 4'b0101;
parameter    ap_ST_st6_fsm_6 = 4'b0110;
parameter    ap_ST_st7_fsm_7 = 4'b0111;
parameter    ap_ST_st8_fsm_8 = 4'b1000;
parameter    ap_true = 1'b1;


layer2_switch_forward_table_macid #(
    .DataWidth( 48 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
forward_table_macid_U(
    .clk( ap_clk ),
    .address0( forward_table_macid_address0 ),
    .ce0( forward_table_macid_ce0 ),
    .we0( forward_table_macid_we0 ),
    .d0( forward_table_macid_d0 ),
    .q0( forward_table_macid_q0 )
);

layer2_switch_forward_table_portid #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
forward_table_portid_U(
    .clk( ap_clk ),
    .address0( forward_table_portid_address0 ),
    .ce0( forward_table_portid_ce0 ),
    .we0( forward_table_portid_we0 ),
    .d0( forward_table_portid_d0 ),
    .q0( forward_table_portid_q0 )
);

layer2_switch_packet_out_data_tmp #(
    .DataWidth( 8 ),
    .AddressRange( 1518 ),
    .AddressWidth( 11 ))
packet_out_data_tmp_U(
    .clk( ap_clk ),
    .address0( packet_out_data_tmp_address0 ),
    .ce0( packet_out_data_tmp_ce0 ),
    .we0( packet_out_data_tmp_we0 ),
    .d0( packet_out_data_tmp_d0 ),
    .q0( packet_out_data_tmp_q0 )
);

layer2_switch_packet_out_data_tmp2 #(
    .DataWidth( 8 ),
    .AddressRange( 1518 ),
    .AddressWidth( 11 ))
packet_out_data_tmp2_U(
    .clk( ap_clk ),
    .address0( packet_out_data_tmp2_address0 ),
    .ce0( packet_out_data_tmp2_ce0 ),
    .we0( packet_out_data_tmp2_we0 ),
    .d0( packet_out_data_tmp2_d0 ),
    .q0( packet_out_data_tmp2_q0 )
);

layer2_switch_packet_out_data_tmp3 #(
    .DataWidth( 8 ),
    .AddressRange( 1518 ),
    .AddressWidth( 11 ))
packet_out_data_tmp3_U(
    .clk( ap_clk ),
    .address0( packet_out_data_tmp3_address0 ),
    .ce0( packet_out_data_tmp3_ce0 ),
    .we0( packet_out_data_tmp3_we0 ),
    .d0( packet_out_data_tmp3_d0 ),
    .q0( packet_out_data_tmp3_q0 )
);

eth_switch grp_eth_switch_fu_57(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_eth_switch_fu_57_ap_start ),
    .ap_done( grp_eth_switch_fu_57_ap_done ),
    .ap_idle( grp_eth_switch_fu_57_ap_idle ),
    .packet_in_data_address0( grp_eth_switch_fu_57_packet_in_data_address0 ),
    .packet_in_data_ce0( grp_eth_switch_fu_57_packet_in_data_ce0 ),
    .packet_in_data_q0( grp_eth_switch_fu_57_packet_in_data_q0 ),
    .eth_header_0_read( grp_eth_switch_fu_57_eth_header_0_read ),
    .eth_header_1_read( grp_eth_switch_fu_57_eth_header_1_read ),
    .eth_header_2_read( grp_eth_switch_fu_57_eth_header_2_read ),
    .eth_header_3_read( grp_eth_switch_fu_57_eth_header_3_read ),
    .packet_out_data_address0( grp_eth_switch_fu_57_packet_out_data_address0 ),
    .packet_out_data_ce0( grp_eth_switch_fu_57_packet_out_data_ce0 ),
    .packet_out_data_we0( grp_eth_switch_fu_57_packet_out_data_we0 ),
    .packet_out_data_d0( grp_eth_switch_fu_57_packet_out_data_d0 ),
    .forward_table_macid_address0( grp_eth_switch_fu_57_forward_table_macid_address0 ),
    .forward_table_macid_ce0( grp_eth_switch_fu_57_forward_table_macid_ce0 ),
    .forward_table_macid_we0( grp_eth_switch_fu_57_forward_table_macid_we0 ),
    .forward_table_macid_d0( grp_eth_switch_fu_57_forward_table_macid_d0 ),
    .forward_table_macid_q0( grp_eth_switch_fu_57_forward_table_macid_q0 ),
    .forward_table_portid_address0( grp_eth_switch_fu_57_forward_table_portid_address0 ),
    .forward_table_portid_ce0( grp_eth_switch_fu_57_forward_table_portid_ce0 ),
    .forward_table_portid_we0( grp_eth_switch_fu_57_forward_table_portid_we0 ),
    .forward_table_portid_d0( grp_eth_switch_fu_57_forward_table_portid_d0 ),
    .forward_table_portid_q0( grp_eth_switch_fu_57_forward_table_portid_q0 ),
    .ap_return( grp_eth_switch_fu_57_ap_return )
);

get_eth_header grp_get_eth_header_fu_77(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_get_eth_header_fu_77_ap_start ),
    .ap_done( grp_get_eth_header_fu_77_ap_done ),
    .ap_idle( grp_get_eth_header_fu_77_ap_idle ),
    .packet_in_data_address0( grp_get_eth_header_fu_77_packet_in_data_address0 ),
    .packet_in_data_ce0( grp_get_eth_header_fu_77_packet_in_data_ce0 ),
    .packet_in_data_q0( grp_get_eth_header_fu_77_packet_in_data_q0 ),
    .input_portid_read( grp_get_eth_header_fu_77_input_portid_read ),
    .packet_out_data_address0( grp_get_eth_header_fu_77_packet_out_data_address0 ),
    .packet_out_data_ce0( grp_get_eth_header_fu_77_packet_out_data_ce0 ),
    .packet_out_data_we0( grp_get_eth_header_fu_77_packet_out_data_we0 ),
    .packet_out_data_d0( grp_get_eth_header_fu_77_packet_out_data_d0 ),
    .ap_return_0( grp_get_eth_header_fu_77_ap_return_0 ),
    .ap_return_1( grp_get_eth_header_fu_77_ap_return_1 ),
    .ap_return_2( grp_get_eth_header_fu_77_ap_return_2 ),
    .ap_return_3( grp_get_eth_header_fu_77_ap_return_3 )
);

input_4port_mux grp_input_4port_mux_fu_84(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_input_4port_mux_fu_84_ap_start ),
    .ap_done( grp_input_4port_mux_fu_84_ap_done ),
    .ap_idle( grp_input_4port_mux_fu_84_ap_idle ),
    .packet_in_data0_dout( grp_input_4port_mux_fu_84_packet_in_data0_dout ),
    .packet_in_data0_empty_n( grp_input_4port_mux_fu_84_packet_in_data0_empty_n ),
    .packet_in_data0_read( grp_input_4port_mux_fu_84_packet_in_data0_read ),
    .packet_in_data1_dout( grp_input_4port_mux_fu_84_packet_in_data1_dout ),
    .packet_in_data1_empty_n( grp_input_4port_mux_fu_84_packet_in_data1_empty_n ),
    .packet_in_data1_read( grp_input_4port_mux_fu_84_packet_in_data1_read ),
    .packet_in_data2_dout( grp_input_4port_mux_fu_84_packet_in_data2_dout ),
    .packet_in_data2_empty_n( grp_input_4port_mux_fu_84_packet_in_data2_empty_n ),
    .packet_in_data2_read( grp_input_4port_mux_fu_84_packet_in_data2_read ),
    .packet_in_data3_dout( grp_input_4port_mux_fu_84_packet_in_data3_dout ),
    .packet_in_data3_empty_n( grp_input_4port_mux_fu_84_packet_in_data3_empty_n ),
    .packet_in_data3_read( grp_input_4port_mux_fu_84_packet_in_data3_read ),
    .packet_out_data_address0( grp_input_4port_mux_fu_84_packet_out_data_address0 ),
    .packet_out_data_ce0( grp_input_4port_mux_fu_84_packet_out_data_ce0 ),
    .packet_out_data_we0( grp_input_4port_mux_fu_84_packet_out_data_we0 ),
    .packet_out_data_d0( grp_input_4port_mux_fu_84_packet_out_data_d0 ),
    .ap_return( grp_input_4port_mux_fu_84_ap_return )
);

output_4port_demux grp_output_4port_demux_fu_100(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_output_4port_demux_fu_100_ap_start ),
    .ap_done( grp_output_4port_demux_fu_100_ap_done ),
    .ap_idle( grp_output_4port_demux_fu_100_ap_idle ),
    .packet_in_data_address0( grp_output_4port_demux_fu_100_packet_in_data_address0 ),
    .packet_in_data_ce0( grp_output_4port_demux_fu_100_packet_in_data_ce0 ),
    .packet_in_data_q0( grp_output_4port_demux_fu_100_packet_in_data_q0 ),
    .input_portid_read( grp_output_4port_demux_fu_100_input_portid_read ),
    .output_portid_read( grp_output_4port_demux_fu_100_output_portid_read ),
    .packet_len( grp_output_4port_demux_fu_100_packet_len ),
    .packet_out_data0_din( grp_output_4port_demux_fu_100_packet_out_data0_din ),
    .packet_out_data0_full_n( grp_output_4port_demux_fu_100_packet_out_data0_full_n ),
    .packet_out_data0_write( grp_output_4port_demux_fu_100_packet_out_data0_write ),
    .packet_out_data1_din( grp_output_4port_demux_fu_100_packet_out_data1_din ),
    .packet_out_data1_full_n( grp_output_4port_demux_fu_100_packet_out_data1_full_n ),
    .packet_out_data1_write( grp_output_4port_demux_fu_100_packet_out_data1_write ),
    .packet_out_data2_din( grp_output_4port_demux_fu_100_packet_out_data2_din ),
    .packet_out_data2_full_n( grp_output_4port_demux_fu_100_packet_out_data2_full_n ),
    .packet_out_data2_write( grp_output_4port_demux_fu_100_packet_out_data2_write ),
    .packet_out_data3_din( grp_output_4port_demux_fu_100_packet_out_data3_din ),
    .packet_out_data3_full_n( grp_output_4port_demux_fu_100_packet_out_data3_full_n ),
    .packet_out_data3_write( grp_output_4port_demux_fu_100_packet_out_data3_write )
);



/// ap_CS_fsm assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_get_eth_header_fu_77_ap_done))) begin
        eth_header_1_reg_143 <= grp_get_eth_header_fu_77_ap_return_1;
    end
    if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_get_eth_header_fu_77_ap_done))) begin
        eth_header_2_reg_148 <= grp_get_eth_header_fu_77_ap_return_2;
    end
    if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_get_eth_header_fu_77_ap_done))) begin
        eth_header_3_reg_154 <= grp_get_eth_header_fu_77_ap_return_3;
    end
    if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_get_eth_header_fu_77_ap_done))) begin
        eth_header_reg_138 <= grp_get_eth_header_fu_77_ap_return_0;
    end
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_input_4port_mux_fu_84_ap_done))) begin
        input_portid_reg_132 <= grp_input_4port_mux_fu_84_ap_return;
    end
    if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_eth_switch_fu_57_ap_done))) begin
        output_portid_assign_1_reg_159 <= grp_eth_switch_fu_57_ap_return;
    end
end

/// ap_NS_fsm assign process. ///
always @ (ap_start or ap_CS_fsm or grp_input_4port_mux_fu_84_ap_done or grp_get_eth_header_fu_77_ap_done or grp_eth_switch_fu_57_ap_done or grp_output_4port_demux_fu_100_ap_done)
begin
    if (((ap_ST_st8_fsm_8 == ap_CS_fsm) & ~(ap_const_logic_1 == ap_start) & ~(ap_const_logic_0 == grp_output_4port_demux_fu_100_ap_done))) begin
        ap_NS_fsm = ap_ST_st0_fsm_0;
    end else if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st8_fsm_8;
    end else if (((ap_ST_st6_fsm_6 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_eth_switch_fu_57_ap_done))) begin
        ap_NS_fsm = ap_ST_st7_fsm_7;
    end else if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st6_fsm_6;
    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_get_eth_header_fu_77_ap_done))) begin
        ap_NS_fsm = ap_ST_st5_fsm_5;
    end else if ((ap_ST_st3_fsm_3 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st4_fsm_4;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_input_4port_mux_fu_84_ap_done))) begin
        ap_NS_fsm = ap_ST_st3_fsm_3;
    end else if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st2_fsm_2;
    end else if ((((ap_ST_st0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_start)) | ((ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_logic_1 == ap_start) & ~(ap_const_logic_0 == grp_output_4port_demux_fu_100_ap_done)))) begin
        ap_NS_fsm = ap_ST_st1_fsm_1;
    end else begin
        ap_NS_fsm = ap_CS_fsm;
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm or grp_output_4port_demux_fu_100_ap_done)
begin
    if (((ap_ST_st8_fsm_8 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_output_4port_demux_fu_100_ap_done))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st0_fsm_0 == ap_CS_fsm)) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// forward_table_macid_ce0 assign process. ///
always @ (ap_CS_fsm or grp_eth_switch_fu_57_forward_table_macid_ce0)
begin
    if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        forward_table_macid_ce0 = grp_eth_switch_fu_57_forward_table_macid_ce0;
    end else begin
        forward_table_macid_ce0 = ap_const_logic_0;
    end
end

/// forward_table_macid_we0 assign process. ///
always @ (ap_CS_fsm or grp_eth_switch_fu_57_forward_table_macid_we0)
begin
    if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        forward_table_macid_we0 = grp_eth_switch_fu_57_forward_table_macid_we0;
    end else begin
        forward_table_macid_we0 = ap_const_logic_0;
    end
end

/// forward_table_portid_ce0 assign process. ///
always @ (ap_CS_fsm or grp_eth_switch_fu_57_forward_table_portid_ce0)
begin
    if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        forward_table_portid_ce0 = grp_eth_switch_fu_57_forward_table_portid_ce0;
    end else begin
        forward_table_portid_ce0 = ap_const_logic_0;
    end
end

/// forward_table_portid_we0 assign process. ///
always @ (ap_CS_fsm or grp_eth_switch_fu_57_forward_table_portid_we0)
begin
    if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        forward_table_portid_we0 = grp_eth_switch_fu_57_forward_table_portid_we0;
    end else begin
        forward_table_portid_we0 = ap_const_logic_0;
    end
end

/// grp_eth_switch_fu_57_ap_start assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        grp_eth_switch_fu_57_ap_start = ap_const_logic_1;
    end else begin
        grp_eth_switch_fu_57_ap_start = ap_const_logic_0;
    end
end

/// grp_get_eth_header_fu_77_ap_start assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st3_fsm_3 == ap_CS_fsm)) begin
        grp_get_eth_header_fu_77_ap_start = ap_const_logic_1;
    end else begin
        grp_get_eth_header_fu_77_ap_start = ap_const_logic_0;
    end
end

/// grp_input_4port_mux_fu_84_ap_start assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        grp_input_4port_mux_fu_84_ap_start = ap_const_logic_1;
    end else begin
        grp_input_4port_mux_fu_84_ap_start = ap_const_logic_0;
    end
end

/// grp_output_4port_demux_fu_100_ap_start assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        grp_output_4port_demux_fu_100_ap_start = ap_const_logic_1;
    end else begin
        grp_output_4port_demux_fu_100_ap_start = ap_const_logic_0;
    end
end

/// packet_in_data0_read assign process. ///
always @ (ap_CS_fsm or grp_input_4port_mux_fu_84_packet_in_data0_read)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) | (ap_ST_st1_fsm_1 == ap_CS_fsm))) begin
        packet_in_data0_read = grp_input_4port_mux_fu_84_packet_in_data0_read;
    end else begin
        packet_in_data0_read = ap_const_logic_0;
    end
end

/// packet_in_data1_read assign process. ///
always @ (ap_CS_fsm or grp_input_4port_mux_fu_84_packet_in_data1_read)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) | (ap_ST_st1_fsm_1 == ap_CS_fsm))) begin
        packet_in_data1_read = grp_input_4port_mux_fu_84_packet_in_data1_read;
    end else begin
        packet_in_data1_read = ap_const_logic_0;
    end
end

/// packet_in_data2_read assign process. ///
always @ (ap_CS_fsm or grp_input_4port_mux_fu_84_packet_in_data2_read)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) | (ap_ST_st1_fsm_1 == ap_CS_fsm))) begin
        packet_in_data2_read = grp_input_4port_mux_fu_84_packet_in_data2_read;
    end else begin
        packet_in_data2_read = ap_const_logic_0;
    end
end

/// packet_in_data3_read assign process. ///
always @ (ap_CS_fsm or grp_input_4port_mux_fu_84_packet_in_data3_read)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) | (ap_ST_st1_fsm_1 == ap_CS_fsm))) begin
        packet_in_data3_read = grp_input_4port_mux_fu_84_packet_in_data3_read;
    end else begin
        packet_in_data3_read = ap_const_logic_0;
    end
end

/// packet_out_data0_write assign process. ///
always @ (ap_CS_fsm or grp_output_4port_demux_fu_100_packet_out_data0_write)
begin
    if (((ap_ST_st7_fsm_7 == ap_CS_fsm) | (ap_ST_st8_fsm_8 == ap_CS_fsm))) begin
        packet_out_data0_write = grp_output_4port_demux_fu_100_packet_out_data0_write;
    end else begin
        packet_out_data0_write = ap_const_logic_0;
    end
end

/// packet_out_data1_write assign process. ///
always @ (ap_CS_fsm or grp_output_4port_demux_fu_100_packet_out_data1_write)
begin
    if (((ap_ST_st7_fsm_7 == ap_CS_fsm) | (ap_ST_st8_fsm_8 == ap_CS_fsm))) begin
        packet_out_data1_write = grp_output_4port_demux_fu_100_packet_out_data1_write;
    end else begin
        packet_out_data1_write = ap_const_logic_0;
    end
end

/// packet_out_data2_write assign process. ///
always @ (ap_CS_fsm or grp_output_4port_demux_fu_100_packet_out_data2_write)
begin
    if (((ap_ST_st7_fsm_7 == ap_CS_fsm) | (ap_ST_st8_fsm_8 == ap_CS_fsm))) begin
        packet_out_data2_write = grp_output_4port_demux_fu_100_packet_out_data2_write;
    end else begin
        packet_out_data2_write = ap_const_logic_0;
    end
end

/// packet_out_data3_write assign process. ///
always @ (ap_CS_fsm or grp_output_4port_demux_fu_100_packet_out_data3_write)
begin
    if (((ap_ST_st7_fsm_7 == ap_CS_fsm) | (ap_ST_st8_fsm_8 == ap_CS_fsm))) begin
        packet_out_data3_write = grp_output_4port_demux_fu_100_packet_out_data3_write;
    end else begin
        packet_out_data3_write = ap_const_logic_0;
    end
end

/// packet_out_data_tmp2_address0 assign process. ///
always @ (ap_CS_fsm or grp_eth_switch_fu_57_packet_in_data_address0 or grp_get_eth_header_fu_77_packet_out_data_address0)
begin
    if ((ap_ST_st4_fsm_4 == ap_CS_fsm)) begin
        packet_out_data_tmp2_address0 = grp_get_eth_header_fu_77_packet_out_data_address0;
    end else if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        packet_out_data_tmp2_address0 = grp_eth_switch_fu_57_packet_in_data_address0;
    end else begin
        packet_out_data_tmp2_address0 = grp_get_eth_header_fu_77_packet_out_data_address0;
    end
end

/// packet_out_data_tmp2_ce0 assign process. ///
always @ (ap_CS_fsm or grp_eth_switch_fu_57_packet_in_data_ce0 or grp_get_eth_header_fu_77_packet_out_data_ce0)
begin
    if ((ap_ST_st4_fsm_4 == ap_CS_fsm)) begin
        packet_out_data_tmp2_ce0 = grp_get_eth_header_fu_77_packet_out_data_ce0;
    end else if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        packet_out_data_tmp2_ce0 = grp_eth_switch_fu_57_packet_in_data_ce0;
    end else begin
        packet_out_data_tmp2_ce0 = ap_const_logic_0;
    end
end

/// packet_out_data_tmp2_we0 assign process. ///
always @ (ap_CS_fsm or grp_get_eth_header_fu_77_packet_out_data_we0)
begin
    if ((ap_ST_st4_fsm_4 == ap_CS_fsm)) begin
        packet_out_data_tmp2_we0 = grp_get_eth_header_fu_77_packet_out_data_we0;
    end else begin
        packet_out_data_tmp2_we0 = ap_const_logic_0;
    end
end

/// packet_out_data_tmp3_address0 assign process. ///
always @ (ap_CS_fsm or grp_eth_switch_fu_57_packet_out_data_address0 or grp_output_4port_demux_fu_100_packet_in_data_address0)
begin
    if ((ap_ST_st8_fsm_8 == ap_CS_fsm)) begin
        packet_out_data_tmp3_address0 = grp_output_4port_demux_fu_100_packet_in_data_address0;
    end else if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        packet_out_data_tmp3_address0 = grp_eth_switch_fu_57_packet_out_data_address0;
    end else begin
        packet_out_data_tmp3_address0 = grp_output_4port_demux_fu_100_packet_in_data_address0;
    end
end

/// packet_out_data_tmp3_ce0 assign process. ///
always @ (ap_CS_fsm or grp_eth_switch_fu_57_packet_out_data_ce0 or grp_output_4port_demux_fu_100_packet_in_data_ce0)
begin
    if ((ap_ST_st8_fsm_8 == ap_CS_fsm)) begin
        packet_out_data_tmp3_ce0 = grp_output_4port_demux_fu_100_packet_in_data_ce0;
    end else if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        packet_out_data_tmp3_ce0 = grp_eth_switch_fu_57_packet_out_data_ce0;
    end else begin
        packet_out_data_tmp3_ce0 = ap_const_logic_0;
    end
end

/// packet_out_data_tmp3_we0 assign process. ///
always @ (ap_CS_fsm or grp_eth_switch_fu_57_packet_out_data_we0)
begin
    if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        packet_out_data_tmp3_we0 = grp_eth_switch_fu_57_packet_out_data_we0;
    end else begin
        packet_out_data_tmp3_we0 = ap_const_logic_0;
    end
end

/// packet_out_data_tmp_address0 assign process. ///
always @ (ap_CS_fsm or grp_get_eth_header_fu_77_packet_in_data_address0 or grp_input_4port_mux_fu_84_packet_out_data_address0)
begin
    if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        packet_out_data_tmp_address0 = grp_input_4port_mux_fu_84_packet_out_data_address0;
    end else if ((ap_ST_st4_fsm_4 == ap_CS_fsm)) begin
        packet_out_data_tmp_address0 = grp_get_eth_header_fu_77_packet_in_data_address0;
    end else begin
        packet_out_data_tmp_address0 = grp_input_4port_mux_fu_84_packet_out_data_address0;
    end
end

/// packet_out_data_tmp_ce0 assign process. ///
always @ (ap_CS_fsm or grp_get_eth_header_fu_77_packet_in_data_ce0 or grp_input_4port_mux_fu_84_packet_out_data_ce0)
begin
    if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        packet_out_data_tmp_ce0 = grp_input_4port_mux_fu_84_packet_out_data_ce0;
    end else if ((ap_ST_st4_fsm_4 == ap_CS_fsm)) begin
        packet_out_data_tmp_ce0 = grp_get_eth_header_fu_77_packet_in_data_ce0;
    end else begin
        packet_out_data_tmp_ce0 = ap_const_logic_0;
    end
end

/// packet_out_data_tmp_we0 assign process. ///
always @ (ap_CS_fsm or grp_input_4port_mux_fu_84_packet_out_data_we0)
begin
    if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        packet_out_data_tmp_we0 = grp_input_4port_mux_fu_84_packet_out_data_we0;
    end else begin
        packet_out_data_tmp_we0 = ap_const_logic_0;
    end
end
assign forward_table_macid_address0 = grp_eth_switch_fu_57_forward_table_macid_address0;
assign forward_table_macid_d0 = grp_eth_switch_fu_57_forward_table_macid_d0;
assign forward_table_portid_address0 = grp_eth_switch_fu_57_forward_table_portid_address0;
assign forward_table_portid_d0 = grp_eth_switch_fu_57_forward_table_portid_d0;
assign grp_eth_switch_fu_57_eth_header_0_read = eth_header_reg_138;
assign grp_eth_switch_fu_57_eth_header_1_read = eth_header_1_reg_143;
assign grp_eth_switch_fu_57_eth_header_2_read = eth_header_2_reg_148;
assign grp_eth_switch_fu_57_eth_header_3_read = eth_header_3_reg_154;
assign grp_eth_switch_fu_57_forward_table_macid_q0 = forward_table_macid_q0;
assign grp_eth_switch_fu_57_forward_table_portid_q0 = forward_table_portid_q0;
assign grp_eth_switch_fu_57_packet_in_data_q0 = packet_out_data_tmp2_q0;
assign grp_get_eth_header_fu_77_input_portid_read = input_portid_reg_132;
assign grp_get_eth_header_fu_77_packet_in_data_q0 = packet_out_data_tmp_q0;
assign grp_input_4port_mux_fu_84_packet_in_data0_dout = packet_in_data0_dout;
assign grp_input_4port_mux_fu_84_packet_in_data0_empty_n = packet_in_data0_empty_n;
assign grp_input_4port_mux_fu_84_packet_in_data1_dout = packet_in_data1_dout;
assign grp_input_4port_mux_fu_84_packet_in_data1_empty_n = packet_in_data1_empty_n;
assign grp_input_4port_mux_fu_84_packet_in_data2_dout = packet_in_data2_dout;
assign grp_input_4port_mux_fu_84_packet_in_data2_empty_n = packet_in_data2_empty_n;
assign grp_input_4port_mux_fu_84_packet_in_data3_dout = packet_in_data3_dout;
assign grp_input_4port_mux_fu_84_packet_in_data3_empty_n = packet_in_data3_empty_n;
assign grp_output_4port_demux_fu_100_input_portid_read = input_portid_reg_132;
assign grp_output_4port_demux_fu_100_output_portid_read = output_portid_assign_1_reg_159;
assign grp_output_4port_demux_fu_100_packet_in_data_q0 = packet_out_data_tmp3_q0;
assign grp_output_4port_demux_fu_100_packet_len = eth_header_2_reg_148;
assign grp_output_4port_demux_fu_100_packet_out_data0_full_n = packet_out_data0_full_n;
assign grp_output_4port_demux_fu_100_packet_out_data1_full_n = packet_out_data1_full_n;
assign grp_output_4port_demux_fu_100_packet_out_data2_full_n = packet_out_data2_full_n;
assign grp_output_4port_demux_fu_100_packet_out_data3_full_n = packet_out_data3_full_n;
assign packet_out_data0_din = grp_output_4port_demux_fu_100_packet_out_data0_din;
assign packet_out_data1_din = grp_output_4port_demux_fu_100_packet_out_data1_din;
assign packet_out_data2_din = grp_output_4port_demux_fu_100_packet_out_data2_din;
assign packet_out_data3_din = grp_output_4port_demux_fu_100_packet_out_data3_din;
assign packet_out_data_tmp2_d0 = grp_get_eth_header_fu_77_packet_out_data_d0;
assign packet_out_data_tmp3_d0 = grp_eth_switch_fu_57_packet_out_data_d0;
assign packet_out_data_tmp_d0 = grp_input_4port_mux_fu_84_packet_out_data_d0;


endmodule //layer2_switch

