// ==============================================================
// RTL generated by AutoPilot - High-Level Synthesis System (C, C++, SystemC)
// Version: 2010.b.1
// Copyright (C) :2006-2010 AutoESL Design Technologies, Inc.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module output_4port_demux (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        packet_in_data_address0,
        packet_in_data_ce0,
        packet_in_data_q0,
        input_portid_read,
        output_portid_read,
        packet_len,
        packet_out_data0_din,
        packet_out_data0_full_n,
        packet_out_data0_write,
        packet_out_data1_din,
        packet_out_data1_full_n,
        packet_out_data1_write,
        packet_out_data2_din,
        packet_out_data2_full_n,
        packet_out_data2_write,
        packet_out_data3_din,
        packet_out_data3_full_n,
        packet_out_data3_write
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output  [10:0] packet_in_data_address0;
output   packet_in_data_ce0;
input  [7:0] packet_in_data_q0;
input  [31:0] input_portid_read;
input  [7:0] output_portid_read;
input  [15:0] packet_len;
output  [7:0] packet_out_data0_din;
input   packet_out_data0_full_n;
output   packet_out_data0_write;
output  [7:0] packet_out_data1_din;
input   packet_out_data1_full_n;
output   packet_out_data1_write;
output  [7:0] packet_out_data2_din;
input   packet_out_data2_full_n;
output   packet_out_data2_write;
output  [7:0] packet_out_data3_din;
input   packet_out_data3_full_n;
output   packet_out_data3_write;

reg ap_done;
reg ap_idle;
reg packet_in_data_ce0;
reg packet_out_data0_write;
reg packet_out_data1_write;
reg packet_out_data2_write;
reg packet_out_data3_write;
reg   [1:0] ap_CS_fsm;
reg   [10:0] tmp2_reg_256;
reg   [0:0] tmp_3_reg_261;
reg   [0:0] tmp_6_reg_265;
reg   [0:0] tmp_9_reg_269;
reg   [0:0] tmp_s_reg_273;
reg   [0:0] icmp_reg_277;
reg   [0:0] tmp_4_reg_281;
reg   [0:0] tmp_5_reg_285;
reg   [0:0] tmp_7_reg_289;
reg   [0:0] tmp_8_reg_293;
reg   [10:0] tmp_1_reg_300;
wire   [0:0] exitcond1_fu_240_p2;
reg   [10:0] i_reg_130;
reg    ap_sig_bdd_118;
wire   [63:0] tmp_2_fu_251_p1;
wire   [0:0] tmp1_fu_158_p2;
wire   [10:0] tmp_fu_154_p1;
wire   [5:0] tmp_10_fu_196_p4;
wire   [6:0] tmp_11_fu_206_p1;
reg   [1:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st0_fsm_0 = 2'b00;
parameter    ap_ST_st1_fsm_1 = 2'b01;
parameter    ap_ST_st2_fsm_2 = 2'b10;
parameter    ap_ST_st3_fsm_3 = 2'b11;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_7 = 32'b00000000000000000000000000000111;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv16_5EE = 16'b0000010111101110;
parameter    ap_const_lv11_5EE = 11'b10111101110;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv8_1 = 8'b00000001;
parameter    ap_const_lv8_2 = 8'b00000010;
parameter    ap_const_lv8_3 = 8'b00000011;
parameter    ap_const_lv32_2 = 32'b00000000000000000000000000000010;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv32_1 = 32'b00000000000000000000000000000001;
parameter    ap_const_lv32_3 = 32'b00000000000000000000000000000011;
parameter    ap_const_lv11_1 = 11'b00000000001;
parameter    ap_true = 1'b1;




/// ap_CS_fsm assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_ST_st3_fsm_3 == ap_CS_fsm) & (tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (tmp_9_reg_269 == ap_const_lv1_0) & (tmp_s_reg_273 == ap_const_lv1_0) & ~ap_sig_bdd_118 & ~(icmp_reg_277 == ap_const_lv1_0)) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & (tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (tmp_9_reg_269 == ap_const_lv1_0) & (tmp_s_reg_273 == ap_const_lv1_0) & (icmp_reg_277 == ap_const_lv1_0) & (tmp_8_reg_293 == ap_const_lv1_0) & ~ap_sig_bdd_118) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & (tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (tmp_9_reg_269 == ap_const_lv1_0) & (tmp_s_reg_273 == ap_const_lv1_0) & (icmp_reg_277 == ap_const_lv1_0) & ~ap_sig_bdd_118 & ~(tmp_8_reg_293 == ap_const_lv1_0)) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & (tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (tmp_9_reg_269 == ap_const_lv1_0) & ~(tmp_s_reg_273 == ap_const_lv1_0) & ~ap_sig_bdd_118) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & (tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & ~(tmp_9_reg_269 == ap_const_lv1_0) & ~ap_sig_bdd_118) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & (tmp_3_reg_261 == ap_const_lv1_0) & ~(tmp_6_reg_265 == ap_const_lv1_0) & ~ap_sig_bdd_118) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & ~(tmp_3_reg_261 == ap_const_lv1_0) & ~ap_sig_bdd_118))) begin
        i_reg_130 <= tmp_1_reg_300;
    end else if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        i_reg_130 <= ap_const_lv11_0;
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        icmp_reg_277 <= (tmp_11_fu_206_p1 == ap_const_lv7_0? 1'b1: 1'b0);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        if (tmp1_fu_158_p2) begin
            tmp2_reg_256 <= tmp_fu_154_p1;
        end else begin
            tmp2_reg_256 <= ap_const_lv11_5EE;
        end

    end
    if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        tmp_1_reg_300 <= (i_reg_130 + ap_const_lv11_1);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_3_reg_261 <= (output_portid_read == ap_const_lv8_0? 1'b1: 1'b0);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_4_reg_281 <= (input_portid_read == ap_const_lv32_0? 1'b1: 1'b0);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_5_reg_285 <= (input_portid_read == ap_const_lv32_1? 1'b1: 1'b0);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_6_reg_265 <= (output_portid_read == ap_const_lv8_1? 1'b1: 1'b0);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_7_reg_289 <= (input_portid_read == ap_const_lv32_2? 1'b1: 1'b0);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_8_reg_293 <= (input_portid_read == ap_const_lv32_3? 1'b1: 1'b0);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_9_reg_269 <= (output_portid_read == ap_const_lv8_2? 1'b1: 1'b0);
    end
    if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        tmp_s_reg_273 <= (output_portid_read == ap_const_lv8_3? 1'b1: 1'b0);
    end
end

/// ap_NS_fsm assign process. ///
always @ (ap_start or ap_CS_fsm or exitcond1_fu_240_p2 or ap_sig_bdd_118)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_logic_1 == ap_start) & ~(exitcond1_fu_240_p2 == ap_const_lv1_0))) begin
        ap_NS_fsm = ap_ST_st0_fsm_0;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (exitcond1_fu_240_p2 == ap_const_lv1_0))) begin
        ap_NS_fsm = ap_ST_st3_fsm_3;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & ~ap_sig_bdd_118))) begin
        ap_NS_fsm = ap_ST_st2_fsm_2;
    end else if ((((ap_ST_st0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_start)) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_start) & ~(exitcond1_fu_240_p2 == ap_const_lv1_0)))) begin
        ap_NS_fsm = ap_ST_st1_fsm_1;
    end else begin
        ap_NS_fsm = ap_CS_fsm;
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm or exitcond1_fu_240_p2)
begin
    if (((ap_ST_st0_fsm_0 == ap_CS_fsm) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(exitcond1_fu_240_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st0_fsm_0 == ap_CS_fsm)) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// packet_in_data_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond1_fu_240_p2)
begin
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (exitcond1_fu_240_p2 == ap_const_lv1_0))) begin
        packet_in_data_ce0 = ap_const_logic_1;
    end else begin
        packet_in_data_ce0 = ap_const_logic_0;
    end
end

/// packet_out_data0_write assign process. ///
always @ (ap_CS_fsm or tmp_3_reg_261 or tmp_6_reg_265 or tmp_9_reg_269 or tmp_s_reg_273 or icmp_reg_277 or tmp_4_reg_281 or ap_sig_bdd_118)
begin
    if ((((ap_ST_st3_fsm_3 == ap_CS_fsm) & ~(tmp_3_reg_261 == ap_const_lv1_0) & ~ap_sig_bdd_118) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & (tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (tmp_9_reg_269 == ap_const_lv1_0) & (tmp_s_reg_273 == ap_const_lv1_0) & (icmp_reg_277 == ap_const_lv1_0) & (tmp_4_reg_281 == ap_const_lv1_0) & ~ap_sig_bdd_118))) begin
        packet_out_data0_write = ap_const_logic_1;
    end else begin
        packet_out_data0_write = ap_const_logic_0;
    end
end

/// packet_out_data1_write assign process. ///
always @ (ap_CS_fsm or tmp_3_reg_261 or tmp_6_reg_265 or tmp_9_reg_269 or tmp_s_reg_273 or icmp_reg_277 or tmp_5_reg_285 or ap_sig_bdd_118)
begin
    if ((((ap_ST_st3_fsm_3 == ap_CS_fsm) & (tmp_3_reg_261 == ap_const_lv1_0) & ~(tmp_6_reg_265 == ap_const_lv1_0) & ~ap_sig_bdd_118) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & (tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (tmp_9_reg_269 == ap_const_lv1_0) & (tmp_s_reg_273 == ap_const_lv1_0) & (icmp_reg_277 == ap_const_lv1_0) & (tmp_5_reg_285 == ap_const_lv1_0) & ~ap_sig_bdd_118))) begin
        packet_out_data1_write = ap_const_logic_1;
    end else begin
        packet_out_data1_write = ap_const_logic_0;
    end
end

/// packet_out_data2_write assign process. ///
always @ (ap_CS_fsm or tmp_3_reg_261 or tmp_6_reg_265 or tmp_9_reg_269 or tmp_s_reg_273 or icmp_reg_277 or tmp_7_reg_289 or ap_sig_bdd_118)
begin
    if ((((ap_ST_st3_fsm_3 == ap_CS_fsm) & (tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & ~(tmp_9_reg_269 == ap_const_lv1_0) & ~ap_sig_bdd_118) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & (tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (tmp_9_reg_269 == ap_const_lv1_0) & (tmp_s_reg_273 == ap_const_lv1_0) & (icmp_reg_277 == ap_const_lv1_0) & (tmp_7_reg_289 == ap_const_lv1_0) & ~ap_sig_bdd_118))) begin
        packet_out_data2_write = ap_const_logic_1;
    end else begin
        packet_out_data2_write = ap_const_logic_0;
    end
end

/// packet_out_data3_write assign process. ///
always @ (ap_CS_fsm or tmp_3_reg_261 or tmp_6_reg_265 or tmp_9_reg_269 or tmp_s_reg_273 or icmp_reg_277 or tmp_8_reg_293 or ap_sig_bdd_118)
begin
    if ((((ap_ST_st3_fsm_3 == ap_CS_fsm) & (tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (tmp_9_reg_269 == ap_const_lv1_0) & (tmp_s_reg_273 == ap_const_lv1_0) & (icmp_reg_277 == ap_const_lv1_0) & (tmp_8_reg_293 == ap_const_lv1_0) & ~ap_sig_bdd_118) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & (tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (tmp_9_reg_269 == ap_const_lv1_0) & ~(tmp_s_reg_273 == ap_const_lv1_0) & ~ap_sig_bdd_118))) begin
        packet_out_data3_write = ap_const_logic_1;
    end else begin
        packet_out_data3_write = ap_const_logic_0;
    end
end

/// ap_sig_bdd_118 assign process. ///
always @ (packet_out_data0_full_n or packet_out_data1_full_n or packet_out_data2_full_n or packet_out_data3_full_n or tmp_3_reg_261 or tmp_6_reg_265 or tmp_9_reg_269 or tmp_s_reg_273 or icmp_reg_277 or tmp_4_reg_281 or tmp_5_reg_285 or tmp_7_reg_289 or tmp_8_reg_293)
begin
    ap_sig_bdd_118 = (((packet_out_data0_full_n == ap_const_logic_0) & (tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (tmp_9_reg_269 == ap_const_lv1_0) & (tmp_s_reg_273 == ap_const_lv1_0) & (icmp_reg_277 == ap_const_lv1_0) & (tmp_4_reg_281 == ap_const_lv1_0)) | ((tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (tmp_9_reg_269 == ap_const_lv1_0) & (tmp_s_reg_273 == ap_const_lv1_0) & (icmp_reg_277 == ap_const_lv1_0) & (packet_out_data1_full_n == ap_const_logic_0) & (tmp_5_reg_285 == ap_const_lv1_0)) | ((tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (tmp_9_reg_269 == ap_const_lv1_0) & (tmp_s_reg_273 == ap_const_lv1_0) & (icmp_reg_277 == ap_const_lv1_0) & (packet_out_data2_full_n == ap_const_logic_0) & (tmp_7_reg_289 == ap_const_lv1_0)) | ((tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (tmp_9_reg_269 == ap_const_lv1_0) & (tmp_s_reg_273 == ap_const_lv1_0) & (icmp_reg_277 == ap_const_lv1_0) & (packet_out_data3_full_n == ap_const_logic_0) & (tmp_8_reg_293 == ap_const_lv1_0)) | ((tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (tmp_9_reg_269 == ap_const_lv1_0) & (packet_out_data3_full_n == ap_const_logic_0) & ~(tmp_s_reg_273 == ap_const_lv1_0)) | ((tmp_3_reg_261 == ap_const_lv1_0) & (tmp_6_reg_265 == ap_const_lv1_0) & (packet_out_data2_full_n == ap_const_logic_0) & ~(tmp_9_reg_269 == ap_const_lv1_0)) | ((tmp_3_reg_261 == ap_const_lv1_0) & (packet_out_data1_full_n == ap_const_logic_0) & ~(tmp_6_reg_265 == ap_const_lv1_0)) | ((packet_out_data0_full_n == ap_const_logic_0) & ~(tmp_3_reg_261 == ap_const_lv1_0)));
end
assign exitcond1_fu_240_p2 = (i_reg_130 == tmp2_reg_256? 1'b1: 1'b0);
assign packet_in_data_address0 = tmp_2_fu_251_p1;
assign packet_out_data0_din = packet_in_data_q0;
assign packet_out_data1_din = packet_in_data_q0;
assign packet_out_data2_din = packet_in_data_q0;
assign packet_out_data3_din = packet_in_data_q0;
assign tmp1_fu_158_p2 = (packet_len < ap_const_lv16_5EE? 1'b1: 1'b0);
assign tmp_10_fu_196_p4 = {{output_portid_read[ap_const_lv32_7 : ap_const_lv32_2]}};
assign tmp_11_fu_206_p1 = {{1{1'b0}}, {tmp_10_fu_196_p4}};
assign tmp_2_fu_251_p1 = {{53{1'b0}}, {i_reg_130}};
assign tmp_fu_154_p1 = packet_len[10:0];


endmodule //output_4port_demux

