
#!/bin/sh

# Clean up the results directory
rm -rf results
mkdir results
cd results

# Copy the netlist generated by Coregen
echo 'Copying files from the netlist directory to the results directory'
cp ../../ipcore/*.ngc .
cp ../../../xps/implementation/system.ngc .
cp ../../../xps/implementation/system.bmm .
find -name 'system.bmm' | xargs perl -pi -e 's|lmb_bram/lmb_bram|microblaze_system/lmb_bram/lmb_bram|g'

#Synthesize the Verilog Wrapper Files
echo 'Synthesizing verilog sample design with XST';
cp ../top.prj .
cp ../top.scr .
xst -ifn top.scr | tee synth.txt

#  Copy the constraints files generated by Coregen
echo 'Copying files from constraints directory to results directory'
cp ../../ucf/top.ucf .

echo 'Running ngdbuild'
ngdbuild top -bm system

echo 'Running map'
map -mt 2 -ol high -pr b -detail top -o mapped.ncd

echo 'Running par'
par -w -mt 4 -ol high mapped.ncd routed.ncd mapped.pcf

echo 'Running trce'
trce -e 10 routed -o routed mapped.pcf

echo 'Running bitgen'
bitgen -w routed routed mapped.pcf

echo 'Running Data2Mem'
data2mem -bm system_bd.bmm -bt routed.bit -bd ../../../xps/TestApp_Memory_microblaze_0/executable.elf tag microblaze_0 -o b final.bit
