# #Coregen generated files/folders (Chipscope Files: ICON and VIO)
# Folders
rm -rf tmp

# Files
rm -rf icon.ngc
rm -rf icon.xco
rm -rf icon_xmdf.tcl
rm -rf icon.gise
rm -rf icon.ise
rm -rf icon.xise

# Folders
rm -rf _xmsgs

# Files
rm -rf icon_flist.txt
rm -rf icon_readme.txt

# Folders
rm -rf icon_xdb

# Files
rm -rf vio.cdc
rm -rf vio.asy
rm -rf vio.ngc
rm -rf vio.xco
rm -rf vio_xmdf.tcl
rm -rf vio.gise
rm -rf vio.ise
rm -rf vio.xise
rm -rf coregen.cgp
rm -rf coregen.cgc
rm -rf coregen.log
rm -rf vio_flist.txt
rm -rf vio_readme.txt

# Folders
rm -rf vio_xdb

# #ISE generated files/folders (temp folders)
# Folders
rm -rf "../synth/__projnav"
rm -rf "../synth/xst"
rm -rf "../synth/_ngo"

# #ISE generated files/folders (Synthesis, Translate, MAP, PAR, TRACE, BITGEN reports and corresponding files)
# Files
rm -rf controller_vhdl.prj
rm -rf controller.ngr
rm -rf controller.syr
rm -rf controller.ngc
rm -rf controller_xst.xrpt

# Folders
rm -rf xlnx_auto_0_xdb

# Files
rm -rf controller.bld
rm -rf controller.ngd
rm -rf controller_ngdbuild.xrpt
rm -rf controller_map.ngm
rm -rf controller.pcf
rm -rf controller_map.mrp
rm -rf controller_map.ncd
rm -rf controller_map.map
rm -rf controller_map.xrpt
rm -rf smartpreview.twr
rm -rf controller.ptwx
rm -rf controller.pad
rm -rf controller_pad.csv
rm -rf controller.ncd
rm -rf controller.par
rm -rf controller.unroutes
rm -rf controller.xpi
rm -rf controller_pad.txt
rm -rf controller_par.xrpt
rm -rf controller.twr
rm -rf controller.twx
rm -rf controller.drc
rm -rf ise_flow_results.txt
rm -rf controller.bgn
rm -rf controller_bitgen.xwbt
rm -rf controller.bit
rm -rf controller_summary.xml
rm -rf controller_usage.xml

# Files and folders generated by create ise
rm -rf test_xdb
rm -rf _xmsgs
rm -rf test.gise
rm -rf test.xise
rm -rf test.xise

# Files and folders generated by ISE through GUI mode
rm -rf _ngo 
rm -rf xst 
rm -rf controller.lso 
rm -rf controller.prj 
rm -rf controller.xst 
rm -rf controller.stx 
rm -rf controller_prev_built.ngd 
rm -rf test.ntrc_log 
rm -rf controller_guide.ncd 
rm -rf controller.cmd_log 
rm -rf controller_summary.html 
rm -rf controller.ut 
rm -rf par_usage_statistics.html
rm -rf usage_statistics_webtalk.html
rm -rf webtalk.log
rm -rf device_usage_statistics.html 
