###########################################################################
#
#  NETFPGA10G www.netfpga.org
#
#  Module:
#       Makefile
#
#  Description:
#	Makefile for axitools package
#

PYTHON		?= python

install:
	./setup.py install