///////////////////////////////////////////////////////////////////////////////
// (c) Copyright 2008 Xilinx, Inc. All rights reserved.
//
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
//
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES.
// 
// 
////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 7.1i
//  \   \         Application : 
//  /   /         Filename : aurora_GTX_WRAPPER.v
// /___/   /\     Timestamp : 02/08/2005 09:12:43
// \   \  /  \ 
//  \___\/\___\ 
//
////////////////////////////////////////////////////////////////////////////////
//Command: 
//Design Name: aurora_GTX_WRAPPER
//
// Module aurora_GTX_WRAPPER
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
////////////////////////////////////////////////////////////////////////////////
`timescale 1ns / 1ps
(* core_generation_info = "aurora,aurora_8b10b_v5_2,{backchannel_mode=Sidebands, c_aurora_lanes=10, c_column_used=left, c_gt_clock_1=GTXD1, c_gt_clock_2=None, c_gt_loc_1=1, c_gt_loc_10=10, c_gt_loc_11=X, c_gt_loc_12=X, c_gt_loc_13=X, c_gt_loc_14=X, c_gt_loc_15=X, c_gt_loc_16=X, c_gt_loc_17=X, c_gt_loc_18=X, c_gt_loc_19=X, c_gt_loc_2=2, c_gt_loc_20=X, c_gt_loc_21=X, c_gt_loc_22=X, c_gt_loc_23=X, c_gt_loc_24=X, c_gt_loc_25=X, c_gt_loc_26=X, c_gt_loc_27=X, c_gt_loc_28=X, c_gt_loc_29=X, c_gt_loc_3=3, c_gt_loc_30=X, c_gt_loc_31=X, c_gt_loc_32=X, c_gt_loc_33=X, c_gt_loc_34=X, c_gt_loc_35=X, c_gt_loc_36=X, c_gt_loc_37=X, c_gt_loc_38=X, c_gt_loc_39=X, c_gt_loc_4=4, c_gt_loc_40=X, c_gt_loc_41=X, c_gt_loc_42=X, c_gt_loc_43=X, c_gt_loc_44=X, c_gt_loc_45=X, c_gt_loc_46=X, c_gt_loc_47=X, c_gt_loc_48=X, c_gt_loc_5=5, c_gt_loc_6=6, c_gt_loc_7=7, c_gt_loc_8=8, c_gt_loc_9=9, c_lane_width=4, c_line_rate=6.5, c_nfc=false, c_nfc_mode=IMM, c_refclk_frequency=130.0, c_simplex=false, c_simplex_mode=TX, c_stream=true, c_ufc=false, flow_mode=None, interface_mode=Streaming, dataflow_config=Duplex}" *)
module aurora_GTX_WRAPPER #
(
    // Simulation attributes
    parameter   SIM_MODE              =   "FAST",  // Set to Fast Functional Simulation Model
    parameter   SIM_GTXRESET_SPEEDUP=   0,      // Set to 1 to speed up sim reset
    parameter   SIM_PLL_PERDIV2     =   9'h099,    // Set to the VCO Unit Interval time

    parameter  CHAN_BOND_LEVEL_0 = 0,
    parameter  CHAN_BOND_LEVEL_1 = 0,

    // Channel bond MASTER/SLAVE connection
    parameter CHAN_BOND_MODE_0 = "SLAVE",
    parameter CHAN_BOND_MODE_0_LANE1 = "SLAVE",
    parameter CHAN_BOND_MODE_0_LANE2 = "SLAVE",
    parameter CHAN_BOND_MODE_0_LANE3 = "SLAVE",
    parameter CHAN_BOND_MODE_0_LANE4 = "MASTER",
    parameter CHAN_BOND_MODE_0_LANE5 = "SLAVE",
    parameter CHAN_BOND_MODE_0_LANE6 = "SLAVE",
    parameter CHAN_BOND_MODE_0_LANE7 = "SLAVE",
    parameter CHAN_BOND_MODE_0_LANE8 = "SLAVE",
    parameter CHAN_BOND_MODE_0_LANE9 = "SLAVE",
    
    parameter CHAN_BOND_MODE_1 = "SLAVE",
    parameter CHAN_BOND_MODE_1_LANE1 = "SLAVE",
    parameter CHAN_BOND_MODE_1_LANE2 = "SLAVE",
    parameter CHAN_BOND_MODE_1_LANE3 = "SLAVE",
    parameter CHAN_BOND_MODE_1_LANE4 = "MASTER",
    parameter CHAN_BOND_MODE_1_LANE5 = "SLAVE",
    parameter CHAN_BOND_MODE_1_LANE6 = "SLAVE",
    parameter CHAN_BOND_MODE_1_LANE7 = "SLAVE",
    parameter CHAN_BOND_MODE_1_LANE8 = "SLAVE",
    parameter CHAN_BOND_MODE_1_LANE9 = "SLAVE",
    // Refclk attributes
    parameter   CLKINDC_B           =   "TRUE"
)
(

//---------------------- Loopback and Powerdown Ports ----------------------
   LOOPBACK_IN,
//--------------------- Receive Ports - 8b10b Decoder ----------------------
    RXCHARISCOMMA_OUT,
    RXCHARISCOMMA_OUT_LANE1,
    RXCHARISCOMMA_OUT_LANE2,
    RXCHARISCOMMA_OUT_LANE3,
    RXCHARISCOMMA_OUT_LANE4,
    RXCHARISCOMMA_OUT_LANE5,
    RXCHARISCOMMA_OUT_LANE6,
    RXCHARISCOMMA_OUT_LANE7,
    RXCHARISCOMMA_OUT_LANE8,
    RXCHARISCOMMA_OUT_LANE9,
    RXCHARISK_OUT,
    RXCHARISK_OUT_LANE1,
    RXCHARISK_OUT_LANE2,
    RXCHARISK_OUT_LANE3,
    RXCHARISK_OUT_LANE4,
    RXCHARISK_OUT_LANE5,
    RXCHARISK_OUT_LANE6,
    RXCHARISK_OUT_LANE7,
    RXCHARISK_OUT_LANE8,
    RXCHARISK_OUT_LANE9,
    RXDISPERR_OUT,
    RXDISPERR_OUT_LANE1,
    RXDISPERR_OUT_LANE2,
    RXDISPERR_OUT_LANE3,
    RXDISPERR_OUT_LANE4,
    RXDISPERR_OUT_LANE5,
    RXDISPERR_OUT_LANE6,
    RXDISPERR_OUT_LANE7,
    RXDISPERR_OUT_LANE8,
    RXDISPERR_OUT_LANE9,
    RXNOTINTABLE_OUT,
    RXNOTINTABLE_OUT_LANE1,
    RXNOTINTABLE_OUT_LANE2,
    RXNOTINTABLE_OUT_LANE3,
    RXNOTINTABLE_OUT_LANE4,
    RXNOTINTABLE_OUT_LANE5,
    RXNOTINTABLE_OUT_LANE6,
    RXNOTINTABLE_OUT_LANE7,
    RXNOTINTABLE_OUT_LANE8,
    RXNOTINTABLE_OUT_LANE9,
//----------------- Receive Ports - Channel Bonding Ports -----------------
    ENCHANSYNC_IN,
    ENCHANSYNC_IN_LANE1,
    ENCHANSYNC_IN_LANE2,
    ENCHANSYNC_IN_LANE3,
    ENCHANSYNC_IN_LANE4,
    ENCHANSYNC_IN_LANE5,
    ENCHANSYNC_IN_LANE6,
    ENCHANSYNC_IN_LANE7,
    ENCHANSYNC_IN_LANE8,
    ENCHANSYNC_IN_LANE9,
    CHBONDDONE_OUT,
    CHBONDDONE_OUT_LANE1,
    CHBONDDONE_OUT_LANE2,
    CHBONDDONE_OUT_LANE3,
    CHBONDDONE_OUT_LANE4,
    CHBONDDONE_OUT_LANE5,
    CHBONDDONE_OUT_LANE6,
    CHBONDDONE_OUT_LANE7,
    CHBONDDONE_OUT_LANE8,
    CHBONDDONE_OUT_LANE9,
//----------------- Receive Ports - Clock Correction Ports -----------------
    RXBUFERR_OUT,
    RXBUFERR_OUT_LANE1,
    RXBUFERR_OUT_LANE2,
    RXBUFERR_OUT_LANE3,
    RXBUFERR_OUT_LANE4,
    RXBUFERR_OUT_LANE5,
    RXBUFERR_OUT_LANE6,
    RXBUFERR_OUT_LANE7,
    RXBUFERR_OUT_LANE8,
    RXBUFERR_OUT_LANE9,
//------------- Receive Ports - Comma Detection and Alignment --------------
    RXREALIGN_OUT,
    RXREALIGN_OUT_LANE1,
    RXREALIGN_OUT_LANE2,
    RXREALIGN_OUT_LANE3,
    RXREALIGN_OUT_LANE4,
    RXREALIGN_OUT_LANE5,
    RXREALIGN_OUT_LANE6,
    RXREALIGN_OUT_LANE7,
    RXREALIGN_OUT_LANE8,
    RXREALIGN_OUT_LANE9,
    ENMCOMMAALIGN_IN,
    ENMCOMMAALIGN_IN_LANE1,
    ENMCOMMAALIGN_IN_LANE2,
    ENMCOMMAALIGN_IN_LANE3,
    ENMCOMMAALIGN_IN_LANE4,
    ENMCOMMAALIGN_IN_LANE5,
    ENMCOMMAALIGN_IN_LANE6,
    ENMCOMMAALIGN_IN_LANE7,
    ENMCOMMAALIGN_IN_LANE8,
    ENMCOMMAALIGN_IN_LANE9,
    ENPCOMMAALIGN_IN,
    ENPCOMMAALIGN_IN_LANE1,
    ENPCOMMAALIGN_IN_LANE2,
    ENPCOMMAALIGN_IN_LANE3,
    ENPCOMMAALIGN_IN_LANE4,
    ENPCOMMAALIGN_IN_LANE5,
    ENPCOMMAALIGN_IN_LANE6,
    ENPCOMMAALIGN_IN_LANE7,
    ENPCOMMAALIGN_IN_LANE8,
    ENPCOMMAALIGN_IN_LANE9,
//----------------- Receive Ports - RX Data Path interface -----------------
    RXDATA_OUT,
    RXDATA_OUT_LANE1,
    RXDATA_OUT_LANE2,
    RXDATA_OUT_LANE3,
    RXDATA_OUT_LANE4,
    RXDATA_OUT_LANE5,
    RXDATA_OUT_LANE6,
    RXDATA_OUT_LANE7,
    RXDATA_OUT_LANE8,
    RXDATA_OUT_LANE9,
    RXRECCLK1_OUT,
    RXRECCLK1_OUT_LANE1,
    RXRECCLK1_OUT_LANE2,
    RXRECCLK1_OUT_LANE3,
    RXRECCLK1_OUT_LANE4,
    RXRECCLK1_OUT_LANE5,
    RXRECCLK1_OUT_LANE6,
    RXRECCLK1_OUT_LANE7,
    RXRECCLK1_OUT_LANE8,
    RXRECCLK1_OUT_LANE9,
    RXRECCLK2_OUT,
    RXRECCLK2_OUT_LANE1,
    RXRECCLK2_OUT_LANE2,
    RXRECCLK2_OUT_LANE3,
    RXRECCLK2_OUT_LANE4,
    RXRECCLK2_OUT_LANE5,
    RXRECCLK2_OUT_LANE6,
    RXRECCLK2_OUT_LANE7,
    RXRECCLK2_OUT_LANE8,
    RXRECCLK2_OUT_LANE9,
    RXRESET_IN,
    RXRESET_IN_LANE1,
    RXRESET_IN_LANE2,
    RXRESET_IN_LANE3,
    RXRESET_IN_LANE4,
    RXRESET_IN_LANE5,
    RXRESET_IN_LANE6,
    RXRESET_IN_LANE7,
    RXRESET_IN_LANE8,
    RXRESET_IN_LANE9,
    RXUSRCLK_IN,
    RXUSRCLK2_IN,
//----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    RX1N_IN,
    RX1N_IN_LANE1,
    RX1N_IN_LANE2,
    RX1N_IN_LANE3,
    RX1N_IN_LANE4,
    RX1N_IN_LANE5,
    RX1N_IN_LANE6,
    RX1N_IN_LANE7,
    RX1N_IN_LANE8,
    RX1N_IN_LANE9,
    RX1P_IN,
    RX1P_IN_LANE1,
    RX1P_IN_LANE2,
    RX1P_IN_LANE3,
    RX1P_IN_LANE4,
    RX1P_IN_LANE5,
    RX1P_IN_LANE6,
    RX1P_IN_LANE7,
    RX1P_IN_LANE8,
    RX1P_IN_LANE9,
//--------------- Receive Ports - RX Polarity Control Ports ----------------
    RXPOLARITY_IN,
    RXPOLARITY_IN_LANE1,
    RXPOLARITY_IN_LANE2,
    RXPOLARITY_IN_LANE3,
    RXPOLARITY_IN_LANE4,
    RXPOLARITY_IN_LANE5,
    RXPOLARITY_IN_LANE6,
    RXPOLARITY_IN_LANE7,
    RXPOLARITY_IN_LANE8,
    RXPOLARITY_IN_LANE9,
//------------------- Shared Ports - Tile and PLL Ports --------------------
    REFCLK,
    GTXRESET_IN,
    PLLLKDET_OUT,
    PLLLKDET_OUT_LANE1,
    PLLLKDET_OUT_LANE2,
    PLLLKDET_OUT_LANE3,
    PLLLKDET_OUT_LANE4,
    REFCLKOUT_OUT,
    REFCLKOUT_OUT_LANE1,
    REFCLKOUT_OUT_LANE2,
    REFCLKOUT_OUT_LANE3,
    REFCLKOUT_OUT_LANE4,
//-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    TXCHARISK_IN,
    TXCHARISK_IN_LANE1,
    TXCHARISK_IN_LANE2,
    TXCHARISK_IN_LANE3,
    TXCHARISK_IN_LANE4,
    TXCHARISK_IN_LANE5,
    TXCHARISK_IN_LANE6,
    TXCHARISK_IN_LANE7,
    TXCHARISK_IN_LANE8,
    TXCHARISK_IN_LANE9,
//---------------- Transmit Ports - TX Data Path interface -----------------
    TXDATA_IN,
    TXDATA_IN_LANE1,
    TXDATA_IN_LANE2,
    TXDATA_IN_LANE3,
    TXDATA_IN_LANE4,
    TXDATA_IN_LANE5,
    TXDATA_IN_LANE6,
    TXDATA_IN_LANE7,
    TXDATA_IN_LANE8,
    TXDATA_IN_LANE9,
    TXOUTCLK1_OUT,
    TXOUTCLK1_OUT_LANE1,
    TXOUTCLK1_OUT_LANE2,
    TXOUTCLK1_OUT_LANE3,
    TXOUTCLK1_OUT_LANE4,
    TXOUTCLK1_OUT_LANE5,
    TXOUTCLK1_OUT_LANE6,
    TXOUTCLK1_OUT_LANE7,
    TXOUTCLK1_OUT_LANE8,
    TXOUTCLK1_OUT_LANE9,
    TXOUTCLK2_OUT,
    TXOUTCLK2_OUT_LANE1,
    TXOUTCLK2_OUT_LANE2,
    TXOUTCLK2_OUT_LANE3,
    TXOUTCLK2_OUT_LANE4,
    TXOUTCLK2_OUT_LANE5,
    TXOUTCLK2_OUT_LANE6,
    TXOUTCLK2_OUT_LANE7,
    TXOUTCLK2_OUT_LANE8,
    TXOUTCLK2_OUT_LANE9,
    TXRESET_IN,
    TXRESET_IN_LANE1,
    TXRESET_IN_LANE2,
    TXRESET_IN_LANE3,
    TXRESET_IN_LANE4,
    TXRESET_IN_LANE5,
    TXRESET_IN_LANE6,
    TXRESET_IN_LANE7,
    TXRESET_IN_LANE8,
    TXRESET_IN_LANE9,
    TXUSRCLK_IN,
    TXUSRCLK2_IN,
    TXBUFERR_OUT,
    TXBUFERR_OUT_LANE1,
    TXBUFERR_OUT_LANE2,
    TXBUFERR_OUT_LANE3,
    TXBUFERR_OUT_LANE4,
    TXBUFERR_OUT_LANE5,
    TXBUFERR_OUT_LANE6,
    TXBUFERR_OUT_LANE7,
    TXBUFERR_OUT_LANE8,
    TXBUFERR_OUT_LANE9,
//------------- Transmit Ports - TX Driver and OOB signalling --------------
    TX1N_OUT,
    TX1N_OUT_LANE1,
    TX1N_OUT_LANE2,
    TX1N_OUT_LANE3,
    TX1N_OUT_LANE4,
    TX1N_OUT_LANE5,
    TX1N_OUT_LANE6,
    TX1N_OUT_LANE7,
    TX1N_OUT_LANE8,
    TX1N_OUT_LANE9,
    TX1P_OUT,
    TX1P_OUT_LANE1,
    TX1P_OUT_LANE2,
    TX1P_OUT_LANE3,
    TX1P_OUT_LANE4,
    TX1P_OUT_LANE5,
    TX1P_OUT_LANE6,
    TX1P_OUT_LANE7,
    TX1P_OUT_LANE8,
    TX1P_OUT_LANE9,

 


 


 


 


 



    POWERDOWN_IN
);
//***************************** Port Declarations *****************************
//---------------------- Loopback and Powerdown Ports ----------------------
 input    [2:0]    LOOPBACK_IN;
//--------------------- Receive Ports - 8b10b Decoder ----------------------
 output   [3:0]    RXCHARISCOMMA_OUT; 
 output   [3:0]    RXCHARISK_OUT; 
 output   [3:0]    RXDISPERR_OUT;
 output   [3:0]    RXNOTINTABLE_OUT;
 output   [3:0]    RXCHARISCOMMA_OUT_LANE1; 
 output   [3:0]    RXCHARISK_OUT_LANE1; 
 output   [3:0]    RXDISPERR_OUT_LANE1;
 output   [3:0]    RXNOTINTABLE_OUT_LANE1;
 output   [3:0]    RXCHARISCOMMA_OUT_LANE2; 
 output   [3:0]    RXCHARISK_OUT_LANE2; 
 output   [3:0]    RXDISPERR_OUT_LANE2;
 output   [3:0]    RXNOTINTABLE_OUT_LANE2;
 output   [3:0]    RXCHARISCOMMA_OUT_LANE3; 
 output   [3:0]    RXCHARISK_OUT_LANE3; 
 output   [3:0]    RXDISPERR_OUT_LANE3;
 output   [3:0]    RXNOTINTABLE_OUT_LANE3;
 output   [3:0]    RXCHARISCOMMA_OUT_LANE4; 
 output   [3:0]    RXCHARISK_OUT_LANE4; 
 output   [3:0]    RXDISPERR_OUT_LANE4;
 output   [3:0]    RXNOTINTABLE_OUT_LANE4;
 output   [3:0]    RXCHARISCOMMA_OUT_LANE5; 
 output   [3:0]    RXCHARISK_OUT_LANE5; 
 output   [3:0]    RXDISPERR_OUT_LANE5;
 output   [3:0]    RXNOTINTABLE_OUT_LANE5;
 output   [3:0]    RXCHARISCOMMA_OUT_LANE6; 
 output   [3:0]    RXCHARISK_OUT_LANE6; 
 output   [3:0]    RXDISPERR_OUT_LANE6;
 output   [3:0]    RXNOTINTABLE_OUT_LANE6;
 output   [3:0]    RXCHARISCOMMA_OUT_LANE7; 
 output   [3:0]    RXCHARISK_OUT_LANE7; 
 output   [3:0]    RXDISPERR_OUT_LANE7;
 output   [3:0]    RXNOTINTABLE_OUT_LANE7;
 output   [3:0]    RXCHARISCOMMA_OUT_LANE8; 
 output   [3:0]    RXCHARISK_OUT_LANE8; 
 output   [3:0]    RXDISPERR_OUT_LANE8;
 output   [3:0]    RXNOTINTABLE_OUT_LANE8;
 output   [3:0]    RXCHARISCOMMA_OUT_LANE9; 
 output   [3:0]    RXCHARISK_OUT_LANE9; 
 output   [3:0]    RXDISPERR_OUT_LANE9;
 output   [3:0]    RXNOTINTABLE_OUT_LANE9;
//----------------- Receive Ports - Channel Bonding Ports -----------------
 
 input             ENCHANSYNC_IN; 
 output            CHBONDDONE_OUT;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT;
 input             ENMCOMMAALIGN_IN;
 input             ENPCOMMAALIGN_IN;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [31:0]   RXDATA_OUT; 
 output            RXRECCLK1_OUT;
 output            RXRECCLK2_OUT;
 input             RXRESET_IN;
  
 input             ENCHANSYNC_IN_LANE1; 
 output            CHBONDDONE_OUT_LANE1;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT_LANE1;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT_LANE1;
 input             ENMCOMMAALIGN_IN_LANE1;
 input             ENPCOMMAALIGN_IN_LANE1;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [31:0]   RXDATA_OUT_LANE1; 
 output            RXRECCLK1_OUT_LANE1;
 output            RXRECCLK2_OUT_LANE1;
 input             RXRESET_IN_LANE1;
  
 input             ENCHANSYNC_IN_LANE2; 
 output            CHBONDDONE_OUT_LANE2;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT_LANE2;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT_LANE2;
 input             ENMCOMMAALIGN_IN_LANE2;
 input             ENPCOMMAALIGN_IN_LANE2;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [31:0]   RXDATA_OUT_LANE2; 
 output            RXRECCLK1_OUT_LANE2;
 output            RXRECCLK2_OUT_LANE2;
 input             RXRESET_IN_LANE2;
  
 input             ENCHANSYNC_IN_LANE3; 
 output            CHBONDDONE_OUT_LANE3;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT_LANE3;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT_LANE3;
 input             ENMCOMMAALIGN_IN_LANE3;
 input             ENPCOMMAALIGN_IN_LANE3;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [31:0]   RXDATA_OUT_LANE3; 
 output            RXRECCLK1_OUT_LANE3;
 output            RXRECCLK2_OUT_LANE3;
 input             RXRESET_IN_LANE3;
  
 input             ENCHANSYNC_IN_LANE4; 
 output            CHBONDDONE_OUT_LANE4;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT_LANE4;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT_LANE4;
 input             ENMCOMMAALIGN_IN_LANE4;
 input             ENPCOMMAALIGN_IN_LANE4;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [31:0]   RXDATA_OUT_LANE4; 
 output            RXRECCLK1_OUT_LANE4;
 output            RXRECCLK2_OUT_LANE4;
 input             RXRESET_IN_LANE4;
  
 input             ENCHANSYNC_IN_LANE5; 
 output            CHBONDDONE_OUT_LANE5;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT_LANE5;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT_LANE5;
 input             ENMCOMMAALIGN_IN_LANE5;
 input             ENPCOMMAALIGN_IN_LANE5;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [31:0]   RXDATA_OUT_LANE5; 
 output            RXRECCLK1_OUT_LANE5;
 output            RXRECCLK2_OUT_LANE5;
 input             RXRESET_IN_LANE5;
  
 input             ENCHANSYNC_IN_LANE6; 
 output            CHBONDDONE_OUT_LANE6;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT_LANE6;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT_LANE6;
 input             ENMCOMMAALIGN_IN_LANE6;
 input             ENPCOMMAALIGN_IN_LANE6;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [31:0]   RXDATA_OUT_LANE6; 
 output            RXRECCLK1_OUT_LANE6;
 output            RXRECCLK2_OUT_LANE6;
 input             RXRESET_IN_LANE6;
  
 input             ENCHANSYNC_IN_LANE7; 
 output            CHBONDDONE_OUT_LANE7;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT_LANE7;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT_LANE7;
 input             ENMCOMMAALIGN_IN_LANE7;
 input             ENPCOMMAALIGN_IN_LANE7;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [31:0]   RXDATA_OUT_LANE7; 
 output            RXRECCLK1_OUT_LANE7;
 output            RXRECCLK2_OUT_LANE7;
 input             RXRESET_IN_LANE7;
  
 input             ENCHANSYNC_IN_LANE8; 
 output            CHBONDDONE_OUT_LANE8;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT_LANE8;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT_LANE8;
 input             ENMCOMMAALIGN_IN_LANE8;
 input             ENPCOMMAALIGN_IN_LANE8;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [31:0]   RXDATA_OUT_LANE8; 
 output            RXRECCLK1_OUT_LANE8;
 output            RXRECCLK2_OUT_LANE8;
 input             RXRESET_IN_LANE8;
  
 input             ENCHANSYNC_IN_LANE9; 
 output            CHBONDDONE_OUT_LANE9;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT_LANE9;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT_LANE9;
 input             ENMCOMMAALIGN_IN_LANE9;
 input             ENPCOMMAALIGN_IN_LANE9;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [31:0]   RXDATA_OUT_LANE9; 
 output            RXRECCLK1_OUT_LANE9;
 output            RXRECCLK2_OUT_LANE9;
 input             RXRESET_IN_LANE9;
  input             RXUSRCLK_IN;
 input             RXUSRCLK2_IN;
//----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
 
 input             RX1N_IN;  
 input             RX1P_IN;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN;
 
 input             RX1N_IN_LANE1;  
 input             RX1P_IN_LANE1;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN_LANE1;
 
 input             RX1N_IN_LANE2;  
 input             RX1P_IN_LANE2;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN_LANE2;
 
 input             RX1N_IN_LANE3;  
 input             RX1P_IN_LANE3;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN_LANE3;
 
 input             RX1N_IN_LANE4;  
 input             RX1P_IN_LANE4;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN_LANE4;
 
 input             RX1N_IN_LANE5;  
 input             RX1P_IN_LANE5;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN_LANE5;
 
 input             RX1N_IN_LANE6;  
 input             RX1P_IN_LANE6;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN_LANE6;
 
 input             RX1N_IN_LANE7;  
 input             RX1P_IN_LANE7;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN_LANE7;
 
 input             RX1N_IN_LANE8;  
 input             RX1P_IN_LANE8;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN_LANE8;
 
 input             RX1N_IN_LANE9;  
 input             RX1P_IN_LANE9;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN_LANE9;
//------------------- Shared Ports - Tile and PLL Ports --------------------
 input             REFCLK;
 input             GTXRESET_IN;
 output            PLLLKDET_OUT;
 output            PLLLKDET_OUT_LANE1;
 output            PLLLKDET_OUT_LANE2;
 output            PLLLKDET_OUT_LANE3;
 output            PLLLKDET_OUT_LANE4;
 input             POWERDOWN_IN;
 output            REFCLKOUT_OUT;
 output            REFCLKOUT_OUT_LANE1;
 output            REFCLKOUT_OUT_LANE2;
 output            REFCLKOUT_OUT_LANE3;
 output            REFCLKOUT_OUT_LANE4;
//-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
 input    [3:0]    TXCHARISK_IN; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [31:0]   TXDATA_IN; 
 output            TXOUTCLK1_OUT;
 output            TXOUTCLK2_OUT;
 input             TXRESET_IN;
 output            TXBUFERR_OUT;
 input    [3:0]    TXCHARISK_IN_LANE1; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [31:0]   TXDATA_IN_LANE1; 
 output            TXOUTCLK1_OUT_LANE1;
 output            TXOUTCLK2_OUT_LANE1;
 input             TXRESET_IN_LANE1;
 output            TXBUFERR_OUT_LANE1;
 input    [3:0]    TXCHARISK_IN_LANE2; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [31:0]   TXDATA_IN_LANE2; 
 output            TXOUTCLK1_OUT_LANE2;
 output            TXOUTCLK2_OUT_LANE2;
 input             TXRESET_IN_LANE2;
 output            TXBUFERR_OUT_LANE2;
 input    [3:0]    TXCHARISK_IN_LANE3; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [31:0]   TXDATA_IN_LANE3; 
 output            TXOUTCLK1_OUT_LANE3;
 output            TXOUTCLK2_OUT_LANE3;
 input             TXRESET_IN_LANE3;
 output            TXBUFERR_OUT_LANE3;
 input    [3:0]    TXCHARISK_IN_LANE4; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [31:0]   TXDATA_IN_LANE4; 
 output            TXOUTCLK1_OUT_LANE4;
 output            TXOUTCLK2_OUT_LANE4;
 input             TXRESET_IN_LANE4;
 output            TXBUFERR_OUT_LANE4;
 input    [3:0]    TXCHARISK_IN_LANE5; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [31:0]   TXDATA_IN_LANE5; 
 output            TXOUTCLK1_OUT_LANE5;
 output            TXOUTCLK2_OUT_LANE5;
 input             TXRESET_IN_LANE5;
 output            TXBUFERR_OUT_LANE5;
 input    [3:0]    TXCHARISK_IN_LANE6; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [31:0]   TXDATA_IN_LANE6; 
 output            TXOUTCLK1_OUT_LANE6;
 output            TXOUTCLK2_OUT_LANE6;
 input             TXRESET_IN_LANE6;
 output            TXBUFERR_OUT_LANE6;
 input    [3:0]    TXCHARISK_IN_LANE7; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [31:0]   TXDATA_IN_LANE7; 
 output            TXOUTCLK1_OUT_LANE7;
 output            TXOUTCLK2_OUT_LANE7;
 input             TXRESET_IN_LANE7;
 output            TXBUFERR_OUT_LANE7;
 input    [3:0]    TXCHARISK_IN_LANE8; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [31:0]   TXDATA_IN_LANE8; 
 output            TXOUTCLK1_OUT_LANE8;
 output            TXOUTCLK2_OUT_LANE8;
 input             TXRESET_IN_LANE8;
 output            TXBUFERR_OUT_LANE8;
 input    [3:0]    TXCHARISK_IN_LANE9; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [31:0]   TXDATA_IN_LANE9; 
 output            TXOUTCLK1_OUT_LANE9;
 output            TXOUTCLK2_OUT_LANE9;
 input             TXRESET_IN_LANE9;
 output            TXBUFERR_OUT_LANE9;
 input             TXUSRCLK_IN;
 input             TXUSRCLK2_IN;
//------------- Transmit Ports - TX Driver and OOB signalling --------------
 output            TX1N_OUT;
 output            TX1P_OUT;
 output            TX1N_OUT_LANE1;
 output            TX1P_OUT_LANE1;
 output            TX1N_OUT_LANE2;
 output            TX1P_OUT_LANE2;
 output            TX1N_OUT_LANE3;
 output            TX1P_OUT_LANE3;
 output            TX1N_OUT_LANE4;
 output            TX1P_OUT_LANE4;
 output            TX1N_OUT_LANE5;
 output            TX1P_OUT_LANE5;
 output            TX1N_OUT_LANE6;
 output            TX1P_OUT_LANE6;
 output            TX1N_OUT_LANE7;
 output            TX1P_OUT_LANE7;
 output            TX1N_OUT_LANE8;
 output            TX1P_OUT_LANE8;
 output            TX1N_OUT_LANE9;
 output            TX1P_OUT_LANE9;

 



 



 



 



 




//***************************** Wire Declarations *****************************
// Ground and VCC signals
 wire               tied_to_ground_i;
 wire    [63:0]     tied_to_ground_vec_i;
 wire               tied_to_vcc_i;
 wire    [63:0]     tied_to_vcc_vec_i;
// floating input port connection signals
 wire     [1:0]    open_rxbufstatus_i;
 wire              open_txbufstatus_i;
 wire     [1:0]    open_rxbufstatus_lane1_i;
 wire              open_txbufstatus_lane1_i;
 wire     [1:0]    open_rxbufstatus_lane2_i;
 wire              open_txbufstatus_lane2_i;
 wire     [1:0]    open_rxbufstatus_lane3_i;
 wire              open_txbufstatus_lane3_i;
 wire     [1:0]    open_rxbufstatus_lane4_i;
 wire              open_txbufstatus_lane4_i;
 wire     [1:0]    open_rxbufstatus_lane5_i;
 wire              open_txbufstatus_lane5_i;
 wire     [1:0]    open_rxbufstatus_lane6_i;
 wire              open_txbufstatus_lane6_i;
 wire     [1:0]    open_rxbufstatus_lane7_i;
 wire              open_txbufstatus_lane7_i;
 wire     [1:0]    open_rxbufstatus_lane8_i;
 wire              open_txbufstatus_lane8_i;
 wire     [1:0]    open_rxbufstatus_lane9_i;
 wire              open_txbufstatus_lane9_i;


// wire to output lock signal
 wire              plllkdet_i;
 wire              plllkdet_lane1_i;
 wire              plllkdet_lane2_i;
 wire              plllkdet_lane3_i;
 wire              plllkdet_lane4_i;

// Channel Bonding 3
 wire     [3:0]    chbondi;
 wire     [3:0]    chbondo;
 wire     [3:0]    chbondi_LANE1;
 wire     [3:0]    chbondo_LANE1;
 wire     [3:0]    chbondi_LANE2;
 wire     [3:0]    chbondo_LANE2;
 wire     [3:0]    chbondi_LANE3;
 wire     [3:0]    chbondo_LANE3;
 wire     [3:0]    chbondi_LANE4;
 wire     [3:0]    chbondo_LANE4;
 wire     [3:0]    chbondi_LANE5;
 wire     [3:0]    chbondo_LANE5;
 wire     [3:0]    chbondi_LANE6;
 wire     [3:0]    chbondo_LANE6;
 wire     [3:0]    chbondi_LANE7;
 wire     [3:0]    chbondo_LANE7;
 wire     [3:0]    chbondi_LANE8;
 wire     [3:0]    chbondo_LANE8;
 wire     [3:0]    chbondi_LANE9;
 wire     [3:0]    chbondo_LANE9;
   
 wire     [3:0]    chbondi_unused_i;

//********************************* Main Body of Code**************************
//-------------------------  Static signal Assigments ---------------------   
 assign tied_to_ground_i             = 1'b0;
 assign tied_to_ground_vec_i         = 64'h0000000000000000;
 assign tied_to_vcc_i                = 1'b1;
 assign tied_to_vcc_vec_i            = 64'hffffffffffffffff;

// Assign lock signals
 assign  PLLLKDET_OUT  =   plllkdet_i;
 assign  PLLLKDET_OUT_LANE1  =   plllkdet_lane1_i;
 assign  PLLLKDET_OUT_LANE2  =   plllkdet_lane2_i;
 assign  PLLLKDET_OUT_LANE3  =   plllkdet_lane3_i;
 assign  PLLLKDET_OUT_LANE4  =   plllkdet_lane4_i;


 assign chbondi_unused_i  = 4'b0000;

 assign  chbondi = chbondo_LANE1;
 assign  chbondi_LANE1 = chbondo_LANE2;
 assign  chbondi_LANE2 = chbondo_LANE3;
 assign  chbondi_LANE3 = chbondo_LANE4;
 assign  chbondi_LANE4 = chbondi_unused_i;
 assign  chbondi_LANE5 = chbondo_LANE4;
 assign  chbondi_LANE6 = chbondo_LANE5;
 assign  chbondi_LANE7 = chbondo_LANE6;
 assign  chbondi_LANE8 = chbondo_LANE7;
 assign  chbondi_LANE9 = chbondo_LANE8;

//------------------------- GTX/GTP Instantiations  --------------------------   
 



   
//*************************************************************************************************            
//-----------------------------------Both GTXs in a Tile-------------------------------------------
//*************************************************************************************************
aurora_GTX_TILE #
    (
        //_______________________ Simulation-Only Attributes __________________
	.TILE_SIM_MODE                (SIM_MODE),
        .TILE_SIM_GTXRESET_SPEEDUP     (SIM_GTXRESET_SPEEDUP),
        .TILE_SIM_PLL_PERDIV2              (SIM_PLL_PERDIV2),
        .TILE_CHAN_BOND_LEVEL_0            (1),
        .TILE_CHAN_BOND_LEVEL_1            (2),
         .TILE_CHAN_BOND_MODE_0           (CHAN_BOND_MODE_0),
         .TILE_CHAN_BOND_MODE_1           (CHAN_BOND_MODE_1_LANE1)
     ) 
GTX_TILE_INST (
         //---------------------- Loopback and Powerdown Ports ----------------------
         .LOOPBACK0_IN                  (LOOPBACK_IN),
         .LOOPBACK1_IN                  (LOOPBACK_IN),
         //--------------------- Receive Ports - 8b10b Decoder ----------------------
         .RXCHARISCOMMA0_OUT             (RXCHARISCOMMA_OUT ),
         .RXCHARISCOMMA1_OUT             (RXCHARISCOMMA_OUT_LANE1),
         .RXCHARISK0_OUT                 (RXCHARISK_OUT),
         .RXCHARISK1_OUT                 (RXCHARISK_OUT_LANE1),
         .RXDISPERR0_OUT                 (RXDISPERR_OUT),
         .RXDISPERR1_OUT                 (RXDISPERR_OUT_LANE1),
         .RXNOTINTABLE0_OUT              (RXNOTINTABLE_OUT),
         .RXNOTINTABLE1_OUT              (RXNOTINTABLE_OUT_LANE1),
         //----------------- Receive Ports - Channel Bonding Ports ------------------
         .RXCHANBONDSEQ0_OUT             ( ),
         .RXCHANBONDSEQ1_OUT             ( ),
         .RXCHBONDI0_IN                 (chbondi),
         .RXCHBONDI1_IN                 (chbondi_LANE1),
         .RXCHBONDO0_OUT                 (chbondo),
         .RXCHBONDO1_OUT                 (chbondo_LANE1),
         .RXENCHANSYNC0_IN              (ENCHANSYNC_IN),
         .RXENCHANSYNC1_IN              (ENCHANSYNC_IN_LANE1),
         //----------------- Receive Ports - Clock Correction Ports -----------------
         .RXCLKCORCNT0_OUT               (),
         .RXCLKCORCNT1_OUT               (),
         //------------- Receive Ports - Comma Detection and Alignment --------------
         .RXBYTEREALIGN0_OUT             (RXREALIGN_OUT ),
         .RXBYTEREALIGN1_OUT             (RXREALIGN_OUT_LANE1 ),
         .RXENMCOMMAALIGN0_IN           (ENMCOMMAALIGN_IN),
         .RXENMCOMMAALIGN1_IN           (ENMCOMMAALIGN_IN_LANE1),
         .RXENPCOMMAALIGN0_IN           (ENPCOMMAALIGN_IN),
         .RXENPCOMMAALIGN1_IN           (ENPCOMMAALIGN_IN_LANE1),
         //----------------- Receive Ports - RX Data Path interface -----------------
         .RXDATA0_OUT                    (RXDATA_OUT),
         .RXDATA1_OUT                    (RXDATA_OUT_LANE1),
         .RXRESET0_IN                   (RXRESET_IN ),
         .RXRESET1_IN                   (RXRESET_IN_LANE1),
         .RXUSRCLK0_IN                  (RXUSRCLK_IN),
         .RXUSRCLK1_IN                  (RXUSRCLK_IN),
         .RXUSRCLK20_IN                 (RXUSRCLK2_IN),
         .RXUSRCLK21_IN                 (RXUSRCLK2_IN),
         //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
         .RXCDRRESET0_IN                (tied_to_ground_i),
         .RXCDRRESET1_IN                (tied_to_ground_i),
         .RXN0_IN                       (RX1N_IN),
         .RXN1_IN                       (RX1N_IN_LANE1),
         .RXP0_IN                       (RX1P_IN),
         .RXP1_IN                       (RX1P_IN_LANE1),
         //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
         .RXBUFRESET0_IN                (tied_to_ground_i),
         .RXBUFRESET1_IN                (tied_to_ground_i),
         .RXBUFSTATUS0_OUT               ({RXBUFERR_OUT,open_rxbufstatus_i} ),
         .RXBUFSTATUS1_OUT               ({RXBUFERR_OUT_LANE1,open_rxbufstatus_lane1_i} ),
         .TXBUFSTATUS0_OUT               ({TXBUFERR_OUT,open_txbufstatus_i} ),
         .TXBUFSTATUS1_OUT               ({TXBUFERR_OUT_LANE1,open_txbufstatus_lane1_i} ),
         .RXCHANISALIGNED0_OUT           (CHBONDDONE_OUT),
         .RXCHANISALIGNED1_OUT           (CHBONDDONE_OUT_LANE1 ),
         .RXCHANREALIGN0_OUT             ( ),
         .RXCHANREALIGN1_OUT             ( ),
         //-------------------- Receive Ports - RX Oversampling ---------------------

         //--------------- Receive Ports - RX Polarity Control Ports ----------------
         .RXPOLARITY0_IN                (RXPOLARITY_IN),
         .RXPOLARITY1_IN                (RXPOLARITY_IN_LANE1),
         //------------------- Shared Ports - Tile and PLL Ports --------------------
         .CLKIN_IN                      (REFCLK),

         .GTXRESET_IN                   (GTXRESET_IN),
         .PLLLKDET_OUT                   (plllkdet_i),
         .REFCLKOUT_OUT                  (REFCLKOUT_OUT),
         .RESETDONE0_OUT                 (resetdone0_i),
         .RESETDONE1_OUT                 (resetdone1_i),
         .TXCHARISK0_IN                 (TXCHARISK_IN),
         .TXCHARISK1_IN                 (TXCHARISK_IN_LANE1),
         //---------------- Transmit Ports - TX Data Path interface -----------------
         .TXDATA0_IN                    (TXDATA_IN),
         .TXDATA1_IN                    (TXDATA_IN_LANE1),
         .TXOUTCLK0_OUT                  (TXOUTCLK1_OUT),
         .TXOUTCLK1_OUT                  (TXOUTCLK1_OUT_LANE1),
         .TXRESET0_IN                   (TXRESET_IN ),
         .TXRESET1_IN                   (TXRESET_IN_LANE1),
         .TXUSRCLK0_IN                  (TXUSRCLK_IN),
         .TXUSRCLK1_IN                  (TXUSRCLK_IN),
         .TXUSRCLK20_IN                 (TXUSRCLK2_IN),
         .TXUSRCLK21_IN                 (TXUSRCLK2_IN),
         //------------- Transmit Ports - TX Driver and OOB signalling --------------
         .TXN0_OUT                       (TX1N_OUT),
         .TXN1_OUT                       (TX1N_OUT_LANE1),
         .TXP0_OUT                       (TX1P_OUT),
         .TXP1_OUT                       (TX1P_OUT_LANE1)
 );
 
 



   
//*************************************************************************************************            
//-----------------------------------Both GTXs in a Tile-------------------------------------------
//*************************************************************************************************
aurora_GTX_TILE #
    (
        //_______________________ Simulation-Only Attributes __________________
	.TILE_SIM_MODE                (SIM_MODE),
        .TILE_SIM_GTXRESET_SPEEDUP     (SIM_GTXRESET_SPEEDUP),
        .TILE_SIM_PLL_PERDIV2              (SIM_PLL_PERDIV2),
        .TILE_CHAN_BOND_LEVEL_0            (3),
        .TILE_CHAN_BOND_LEVEL_1            (4),
         .TILE_CHAN_BOND_MODE_0           (CHAN_BOND_MODE_0_LANE2),
         .TILE_CHAN_BOND_MODE_1           (CHAN_BOND_MODE_1_LANE3)
     ) 
GTX_TILE_INST_LANE1 (
         //---------------------- Loopback and Powerdown Ports ----------------------
         .LOOPBACK0_IN                  (LOOPBACK_IN),
         .LOOPBACK1_IN                  (LOOPBACK_IN),
         //--------------------- Receive Ports - 8b10b Decoder ----------------------
         .RXCHARISCOMMA0_OUT             (RXCHARISCOMMA_OUT_LANE2 ),
         .RXCHARISCOMMA1_OUT             (RXCHARISCOMMA_OUT_LANE3),
         .RXCHARISK0_OUT                 (RXCHARISK_OUT_LANE2),
         .RXCHARISK1_OUT                 (RXCHARISK_OUT_LANE3),
         .RXDISPERR0_OUT                 (RXDISPERR_OUT_LANE2),
         .RXDISPERR1_OUT                 (RXDISPERR_OUT_LANE3),
         .RXNOTINTABLE0_OUT              (RXNOTINTABLE_OUT_LANE2),
         .RXNOTINTABLE1_OUT              (RXNOTINTABLE_OUT_LANE3),
         //----------------- Receive Ports - Channel Bonding Ports ------------------
         .RXCHANBONDSEQ0_OUT             ( ),
         .RXCHANBONDSEQ1_OUT             ( ),
         .RXCHBONDI0_IN                 (chbondi_LANE2),
         .RXCHBONDI1_IN                 (chbondi_LANE3),
         .RXCHBONDO0_OUT                 (chbondo_LANE2),
         .RXCHBONDO1_OUT                 (chbondo_LANE3),
         .RXENCHANSYNC0_IN              (ENCHANSYNC_IN_LANE2),
         .RXENCHANSYNC1_IN              (ENCHANSYNC_IN_LANE3),
         //----------------- Receive Ports - Clock Correction Ports -----------------
         .RXCLKCORCNT0_OUT               (),
         .RXCLKCORCNT1_OUT               (),
         //------------- Receive Ports - Comma Detection and Alignment --------------
         .RXBYTEREALIGN0_OUT             (RXREALIGN_OUT_LANE2 ),
         .RXBYTEREALIGN1_OUT             (RXREALIGN_OUT_LANE3 ),
         .RXENMCOMMAALIGN0_IN           (ENMCOMMAALIGN_IN_LANE2),
         .RXENMCOMMAALIGN1_IN           (ENMCOMMAALIGN_IN_LANE3),
         .RXENPCOMMAALIGN0_IN           (ENPCOMMAALIGN_IN_LANE2),
         .RXENPCOMMAALIGN1_IN           (ENPCOMMAALIGN_IN_LANE3),
         //----------------- Receive Ports - RX Data Path interface -----------------
         .RXDATA0_OUT                    (RXDATA_OUT_LANE2),
         .RXDATA1_OUT                    (RXDATA_OUT_LANE3),
         .RXRESET0_IN                   (RXRESET_IN_LANE2 ),
         .RXRESET1_IN                   (RXRESET_IN_LANE3),
         .RXUSRCLK0_IN                  (RXUSRCLK_IN),
         .RXUSRCLK1_IN                  (RXUSRCLK_IN),
         .RXUSRCLK20_IN                 (RXUSRCLK2_IN),
         .RXUSRCLK21_IN                 (RXUSRCLK2_IN),
         //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
         .RXCDRRESET0_IN                (tied_to_ground_i),
         .RXCDRRESET1_IN                (tied_to_ground_i),
         .RXN0_IN                       (RX1N_IN_LANE2),
         .RXN1_IN                       (RX1N_IN_LANE3),
         .RXP0_IN                       (RX1P_IN_LANE2),
         .RXP1_IN                       (RX1P_IN_LANE3),
         //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
         .RXBUFRESET0_IN                (tied_to_ground_i),
         .RXBUFRESET1_IN                (tied_to_ground_i),
         .RXBUFSTATUS0_OUT               ({RXBUFERR_OUT_LANE2,open_rxbufstatus_lane2_i} ),
         .RXBUFSTATUS1_OUT               ({RXBUFERR_OUT_LANE3,open_rxbufstatus_lane3_i} ),
         .TXBUFSTATUS0_OUT               ({TXBUFERR_OUT_LANE2,open_txbufstatus_lane2_i} ),
         .TXBUFSTATUS1_OUT               ({TXBUFERR_OUT_LANE3,open_txbufstatus_lane3_i} ),
         .RXCHANISALIGNED0_OUT           (CHBONDDONE_OUT_LANE2),
         .RXCHANISALIGNED1_OUT           (CHBONDDONE_OUT_LANE3 ),
         .RXCHANREALIGN0_OUT             ( ),
         .RXCHANREALIGN1_OUT             ( ),
         //-------------------- Receive Ports - RX Oversampling ---------------------

         //--------------- Receive Ports - RX Polarity Control Ports ----------------
         .RXPOLARITY0_IN                (RXPOLARITY_IN_LANE2),
         .RXPOLARITY1_IN                (RXPOLARITY_IN_LANE3),
         //------------------- Shared Ports - Tile and PLL Ports --------------------
         .CLKIN_IN                      (REFCLK),

         .GTXRESET_IN                   (GTXRESET_IN),
         .PLLLKDET_OUT                   (plllkdet_lane1_i),
         .REFCLKOUT_OUT                  (REFCLKOUT_OUT_LANE1),
         .RESETDONE0_OUT                 (resetdone0_lane1_i),
         .RESETDONE1_OUT                 (resetdone1_lane1_i),
         .TXCHARISK0_IN                 (TXCHARISK_IN_LANE2),
         .TXCHARISK1_IN                 (TXCHARISK_IN_LANE3),
         //---------------- Transmit Ports - TX Data Path interface -----------------
         .TXDATA0_IN                    (TXDATA_IN_LANE2),
         .TXDATA1_IN                    (TXDATA_IN_LANE3),
         .TXOUTCLK0_OUT                  (TXOUTCLK1_OUT_LANE2),
         .TXOUTCLK1_OUT                  (TXOUTCLK1_OUT_LANE3),
         .TXRESET0_IN                   (TXRESET_IN_LANE2 ),
         .TXRESET1_IN                   (TXRESET_IN_LANE3),
         .TXUSRCLK0_IN                  (TXUSRCLK_IN),
         .TXUSRCLK1_IN                  (TXUSRCLK_IN),
         .TXUSRCLK20_IN                 (TXUSRCLK2_IN),
         .TXUSRCLK21_IN                 (TXUSRCLK2_IN),
         //------------- Transmit Ports - TX Driver and OOB signalling --------------
         .TXN0_OUT                       (TX1N_OUT_LANE2),
         .TXN1_OUT                       (TX1N_OUT_LANE3),
         .TXP0_OUT                       (TX1P_OUT_LANE2),
         .TXP1_OUT                       (TX1P_OUT_LANE3)
 );
 
 



   
//*************************************************************************************************            
//-----------------------------------Both GTXs in a Tile-------------------------------------------
//*************************************************************************************************
aurora_GTX_TILE #
    (
        //_______________________ Simulation-Only Attributes __________________
	.TILE_SIM_MODE                (SIM_MODE),
        .TILE_SIM_GTXRESET_SPEEDUP     (SIM_GTXRESET_SPEEDUP),
        .TILE_SIM_PLL_PERDIV2              (SIM_PLL_PERDIV2),
        .TILE_CHAN_BOND_LEVEL_0            (5),
        .TILE_CHAN_BOND_LEVEL_1            (4),
         .TILE_CHAN_BOND_MODE_0           (CHAN_BOND_MODE_0_LANE4),
         .TILE_CHAN_BOND_MODE_1           (CHAN_BOND_MODE_1_LANE5)
     ) 
GTX_TILE_INST_LANE2 (
         //---------------------- Loopback and Powerdown Ports ----------------------
         .LOOPBACK0_IN                  (LOOPBACK_IN),
         .LOOPBACK1_IN                  (LOOPBACK_IN),
         //--------------------- Receive Ports - 8b10b Decoder ----------------------
         .RXCHARISCOMMA0_OUT             (RXCHARISCOMMA_OUT_LANE4 ),
         .RXCHARISCOMMA1_OUT             (RXCHARISCOMMA_OUT_LANE5),
         .RXCHARISK0_OUT                 (RXCHARISK_OUT_LANE4),
         .RXCHARISK1_OUT                 (RXCHARISK_OUT_LANE5),
         .RXDISPERR0_OUT                 (RXDISPERR_OUT_LANE4),
         .RXDISPERR1_OUT                 (RXDISPERR_OUT_LANE5),
         .RXNOTINTABLE0_OUT              (RXNOTINTABLE_OUT_LANE4),
         .RXNOTINTABLE1_OUT              (RXNOTINTABLE_OUT_LANE5),
         //----------------- Receive Ports - Channel Bonding Ports ------------------
         .RXCHANBONDSEQ0_OUT             ( ),
         .RXCHANBONDSEQ1_OUT             ( ),
         .RXCHBONDI0_IN                 (chbondi_LANE4),
         .RXCHBONDI1_IN                 (chbondi_LANE5),
         .RXCHBONDO0_OUT                 (chbondo_LANE4),
         .RXCHBONDO1_OUT                 (chbondo_LANE5),
         .RXENCHANSYNC0_IN              (ENCHANSYNC_IN_LANE4),
         .RXENCHANSYNC1_IN              (ENCHANSYNC_IN_LANE5),
         //----------------- Receive Ports - Clock Correction Ports -----------------
         .RXCLKCORCNT0_OUT               (),
         .RXCLKCORCNT1_OUT               (),
         //------------- Receive Ports - Comma Detection and Alignment --------------
         .RXBYTEREALIGN0_OUT             (RXREALIGN_OUT_LANE4 ),
         .RXBYTEREALIGN1_OUT             (RXREALIGN_OUT_LANE5 ),
         .RXENMCOMMAALIGN0_IN           (ENMCOMMAALIGN_IN_LANE4),
         .RXENMCOMMAALIGN1_IN           (ENMCOMMAALIGN_IN_LANE5),
         .RXENPCOMMAALIGN0_IN           (ENPCOMMAALIGN_IN_LANE4),
         .RXENPCOMMAALIGN1_IN           (ENPCOMMAALIGN_IN_LANE5),
         //----------------- Receive Ports - RX Data Path interface -----------------
         .RXDATA0_OUT                    (RXDATA_OUT_LANE4),
         .RXDATA1_OUT                    (RXDATA_OUT_LANE5),
         .RXRESET0_IN                   (RXRESET_IN_LANE4 ),
         .RXRESET1_IN                   (RXRESET_IN_LANE5),
         .RXUSRCLK0_IN                  (RXUSRCLK_IN),
         .RXUSRCLK1_IN                  (RXUSRCLK_IN),
         .RXUSRCLK20_IN                 (RXUSRCLK2_IN),
         .RXUSRCLK21_IN                 (RXUSRCLK2_IN),
         //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
         .RXCDRRESET0_IN                (tied_to_ground_i),
         .RXCDRRESET1_IN                (tied_to_ground_i),
         .RXN0_IN                       (RX1N_IN_LANE4),
         .RXN1_IN                       (RX1N_IN_LANE5),
         .RXP0_IN                       (RX1P_IN_LANE4),
         .RXP1_IN                       (RX1P_IN_LANE5),
         //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
         .RXBUFRESET0_IN                (tied_to_ground_i),
         .RXBUFRESET1_IN                (tied_to_ground_i),
         .RXBUFSTATUS0_OUT               ({RXBUFERR_OUT_LANE4,open_rxbufstatus_lane4_i} ),
         .RXBUFSTATUS1_OUT               ({RXBUFERR_OUT_LANE5,open_rxbufstatus_lane5_i} ),
         .TXBUFSTATUS0_OUT               ({TXBUFERR_OUT_LANE4,open_txbufstatus_lane4_i} ),
         .TXBUFSTATUS1_OUT               ({TXBUFERR_OUT_LANE5,open_txbufstatus_lane5_i} ),
         .RXCHANISALIGNED0_OUT           (CHBONDDONE_OUT_LANE4),
         .RXCHANISALIGNED1_OUT           (CHBONDDONE_OUT_LANE5 ),
         .RXCHANREALIGN0_OUT             ( ),
         .RXCHANREALIGN1_OUT             ( ),
         //-------------------- Receive Ports - RX Oversampling ---------------------

         //--------------- Receive Ports - RX Polarity Control Ports ----------------
         .RXPOLARITY0_IN                (RXPOLARITY_IN_LANE4),
         .RXPOLARITY1_IN                (RXPOLARITY_IN_LANE5),
         //------------------- Shared Ports - Tile and PLL Ports --------------------
         .CLKIN_IN                      (REFCLK),

         .GTXRESET_IN                   (GTXRESET_IN),
         .PLLLKDET_OUT                   (plllkdet_lane2_i),
         .REFCLKOUT_OUT                  (REFCLKOUT_OUT_LANE2),
         .RESETDONE0_OUT                 (resetdone0_lane2_i),
         .RESETDONE1_OUT                 (resetdone1_lane2_i),
         .TXCHARISK0_IN                 (TXCHARISK_IN_LANE4),
         .TXCHARISK1_IN                 (TXCHARISK_IN_LANE5),
         //---------------- Transmit Ports - TX Data Path interface -----------------
         .TXDATA0_IN                    (TXDATA_IN_LANE4),
         .TXDATA1_IN                    (TXDATA_IN_LANE5),
         .TXOUTCLK0_OUT                  (TXOUTCLK1_OUT_LANE4),
         .TXOUTCLK1_OUT                  (TXOUTCLK1_OUT_LANE5),
         .TXRESET0_IN                   (TXRESET_IN_LANE4 ),
         .TXRESET1_IN                   (TXRESET_IN_LANE5),
         .TXUSRCLK0_IN                  (TXUSRCLK_IN),
         .TXUSRCLK1_IN                  (TXUSRCLK_IN),
         .TXUSRCLK20_IN                 (TXUSRCLK2_IN),
         .TXUSRCLK21_IN                 (TXUSRCLK2_IN),
         //------------- Transmit Ports - TX Driver and OOB signalling --------------
         .TXN0_OUT                       (TX1N_OUT_LANE4),
         .TXN1_OUT                       (TX1N_OUT_LANE5),
         .TXP0_OUT                       (TX1P_OUT_LANE4),
         .TXP1_OUT                       (TX1P_OUT_LANE5)
 );
 
 



   
//*************************************************************************************************            
//-----------------------------------Both GTXs in a Tile-------------------------------------------
//*************************************************************************************************
aurora_GTX_TILE #
    (
        //_______________________ Simulation-Only Attributes __________________
	.TILE_SIM_MODE                (SIM_MODE),
        .TILE_SIM_GTXRESET_SPEEDUP     (SIM_GTXRESET_SPEEDUP),
        .TILE_SIM_PLL_PERDIV2              (SIM_PLL_PERDIV2),
        .TILE_CHAN_BOND_LEVEL_0            (3),
        .TILE_CHAN_BOND_LEVEL_1            (2),
         .TILE_CHAN_BOND_MODE_0           (CHAN_BOND_MODE_0_LANE6),
         .TILE_CHAN_BOND_MODE_1           (CHAN_BOND_MODE_1_LANE7)
     ) 
GTX_TILE_INST_LANE3 (
         //---------------------- Loopback and Powerdown Ports ----------------------
         .LOOPBACK0_IN                  (LOOPBACK_IN),
         .LOOPBACK1_IN                  (LOOPBACK_IN),
         //--------------------- Receive Ports - 8b10b Decoder ----------------------
         .RXCHARISCOMMA0_OUT             (RXCHARISCOMMA_OUT_LANE6 ),
         .RXCHARISCOMMA1_OUT             (RXCHARISCOMMA_OUT_LANE7),
         .RXCHARISK0_OUT                 (RXCHARISK_OUT_LANE6),
         .RXCHARISK1_OUT                 (RXCHARISK_OUT_LANE7),
         .RXDISPERR0_OUT                 (RXDISPERR_OUT_LANE6),
         .RXDISPERR1_OUT                 (RXDISPERR_OUT_LANE7),
         .RXNOTINTABLE0_OUT              (RXNOTINTABLE_OUT_LANE6),
         .RXNOTINTABLE1_OUT              (RXNOTINTABLE_OUT_LANE7),
         //----------------- Receive Ports - Channel Bonding Ports ------------------
         .RXCHANBONDSEQ0_OUT             ( ),
         .RXCHANBONDSEQ1_OUT             ( ),
         .RXCHBONDI0_IN                 (chbondi_LANE6),
         .RXCHBONDI1_IN                 (chbondi_LANE7),
         .RXCHBONDO0_OUT                 (chbondo_LANE6),
         .RXCHBONDO1_OUT                 (chbondo_LANE7),
         .RXENCHANSYNC0_IN              (ENCHANSYNC_IN_LANE6),
         .RXENCHANSYNC1_IN              (ENCHANSYNC_IN_LANE7),
         //----------------- Receive Ports - Clock Correction Ports -----------------
         .RXCLKCORCNT0_OUT               (),
         .RXCLKCORCNT1_OUT               (),
         //------------- Receive Ports - Comma Detection and Alignment --------------
         .RXBYTEREALIGN0_OUT             (RXREALIGN_OUT_LANE6 ),
         .RXBYTEREALIGN1_OUT             (RXREALIGN_OUT_LANE7 ),
         .RXENMCOMMAALIGN0_IN           (ENMCOMMAALIGN_IN_LANE6),
         .RXENMCOMMAALIGN1_IN           (ENMCOMMAALIGN_IN_LANE7),
         .RXENPCOMMAALIGN0_IN           (ENPCOMMAALIGN_IN_LANE6),
         .RXENPCOMMAALIGN1_IN           (ENPCOMMAALIGN_IN_LANE7),
         //----------------- Receive Ports - RX Data Path interface -----------------
         .RXDATA0_OUT                    (RXDATA_OUT_LANE6),
         .RXDATA1_OUT                    (RXDATA_OUT_LANE7),
         .RXRESET0_IN                   (RXRESET_IN_LANE6 ),
         .RXRESET1_IN                   (RXRESET_IN_LANE7),
         .RXUSRCLK0_IN                  (RXUSRCLK_IN),
         .RXUSRCLK1_IN                  (RXUSRCLK_IN),
         .RXUSRCLK20_IN                 (RXUSRCLK2_IN),
         .RXUSRCLK21_IN                 (RXUSRCLK2_IN),
         //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
         .RXCDRRESET0_IN                (tied_to_ground_i),
         .RXCDRRESET1_IN                (tied_to_ground_i),
         .RXN0_IN                       (RX1N_IN_LANE6),
         .RXN1_IN                       (RX1N_IN_LANE7),
         .RXP0_IN                       (RX1P_IN_LANE6),
         .RXP1_IN                       (RX1P_IN_LANE7),
         //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
         .RXBUFRESET0_IN                (tied_to_ground_i),
         .RXBUFRESET1_IN                (tied_to_ground_i),
         .RXBUFSTATUS0_OUT               ({RXBUFERR_OUT_LANE6,open_rxbufstatus_lane6_i} ),
         .RXBUFSTATUS1_OUT               ({RXBUFERR_OUT_LANE7,open_rxbufstatus_lane7_i} ),
         .TXBUFSTATUS0_OUT               ({TXBUFERR_OUT_LANE6,open_txbufstatus_lane6_i} ),
         .TXBUFSTATUS1_OUT               ({TXBUFERR_OUT_LANE7,open_txbufstatus_lane7_i} ),
         .RXCHANISALIGNED0_OUT           (CHBONDDONE_OUT_LANE6),
         .RXCHANISALIGNED1_OUT           (CHBONDDONE_OUT_LANE7 ),
         .RXCHANREALIGN0_OUT             ( ),
         .RXCHANREALIGN1_OUT             ( ),
         //-------------------- Receive Ports - RX Oversampling ---------------------

         //--------------- Receive Ports - RX Polarity Control Ports ----------------
         .RXPOLARITY0_IN                (RXPOLARITY_IN_LANE6),
         .RXPOLARITY1_IN                (RXPOLARITY_IN_LANE7),
         //------------------- Shared Ports - Tile and PLL Ports --------------------
         .CLKIN_IN                      (REFCLK),

         .GTXRESET_IN                   (GTXRESET_IN),
         .PLLLKDET_OUT                   (plllkdet_lane3_i),
         .REFCLKOUT_OUT                  (REFCLKOUT_OUT_LANE3),
         .RESETDONE0_OUT                 (resetdone0_lane3_i),
         .RESETDONE1_OUT                 (resetdone1_lane3_i),
         .TXCHARISK0_IN                 (TXCHARISK_IN_LANE6),
         .TXCHARISK1_IN                 (TXCHARISK_IN_LANE7),
         //---------------- Transmit Ports - TX Data Path interface -----------------
         .TXDATA0_IN                    (TXDATA_IN_LANE6),
         .TXDATA1_IN                    (TXDATA_IN_LANE7),
         .TXOUTCLK0_OUT                  (TXOUTCLK1_OUT_LANE6),
         .TXOUTCLK1_OUT                  (TXOUTCLK1_OUT_LANE7),
         .TXRESET0_IN                   (TXRESET_IN_LANE6 ),
         .TXRESET1_IN                   (TXRESET_IN_LANE7),
         .TXUSRCLK0_IN                  (TXUSRCLK_IN),
         .TXUSRCLK1_IN                  (TXUSRCLK_IN),
         .TXUSRCLK20_IN                 (TXUSRCLK2_IN),
         .TXUSRCLK21_IN                 (TXUSRCLK2_IN),
         //------------- Transmit Ports - TX Driver and OOB signalling --------------
         .TXN0_OUT                       (TX1N_OUT_LANE6),
         .TXN1_OUT                       (TX1N_OUT_LANE7),
         .TXP0_OUT                       (TX1P_OUT_LANE6),
         .TXP1_OUT                       (TX1P_OUT_LANE7)
 );
 
 



   
//*************************************************************************************************            
//-----------------------------------Both GTXs in a Tile-------------------------------------------
//*************************************************************************************************
aurora_GTX_TILE #
    (
        //_______________________ Simulation-Only Attributes __________________
	.TILE_SIM_MODE                (SIM_MODE),
        .TILE_SIM_GTXRESET_SPEEDUP     (SIM_GTXRESET_SPEEDUP),
        .TILE_SIM_PLL_PERDIV2              (SIM_PLL_PERDIV2),
        .TILE_CHAN_BOND_LEVEL_0            (1),
        .TILE_CHAN_BOND_LEVEL_1            (0),
         .TILE_CHAN_BOND_MODE_0           (CHAN_BOND_MODE_0_LANE8),
         .TILE_CHAN_BOND_MODE_1           (CHAN_BOND_MODE_1_LANE9)
     ) 
GTX_TILE_INST_LANE4 (
         //---------------------- Loopback and Powerdown Ports ----------------------
         .LOOPBACK0_IN                  (LOOPBACK_IN),
         .LOOPBACK1_IN                  (LOOPBACK_IN),
         //--------------------- Receive Ports - 8b10b Decoder ----------------------
         .RXCHARISCOMMA0_OUT             (RXCHARISCOMMA_OUT_LANE8 ),
         .RXCHARISCOMMA1_OUT             (RXCHARISCOMMA_OUT_LANE9),
         .RXCHARISK0_OUT                 (RXCHARISK_OUT_LANE8),
         .RXCHARISK1_OUT                 (RXCHARISK_OUT_LANE9),
         .RXDISPERR0_OUT                 (RXDISPERR_OUT_LANE8),
         .RXDISPERR1_OUT                 (RXDISPERR_OUT_LANE9),
         .RXNOTINTABLE0_OUT              (RXNOTINTABLE_OUT_LANE8),
         .RXNOTINTABLE1_OUT              (RXNOTINTABLE_OUT_LANE9),
         //----------------- Receive Ports - Channel Bonding Ports ------------------
         .RXCHANBONDSEQ0_OUT             ( ),
         .RXCHANBONDSEQ1_OUT             ( ),
         .RXCHBONDI0_IN                 (chbondi_LANE8),
         .RXCHBONDI1_IN                 (chbondi_LANE9),
         .RXCHBONDO0_OUT                 (chbondo_LANE8),
         .RXCHBONDO1_OUT                 (chbondo_LANE9),
         .RXENCHANSYNC0_IN              (ENCHANSYNC_IN_LANE8),
         .RXENCHANSYNC1_IN              (ENCHANSYNC_IN_LANE9),
         //----------------- Receive Ports - Clock Correction Ports -----------------
         .RXCLKCORCNT0_OUT               (),
         .RXCLKCORCNT1_OUT               (),
         //------------- Receive Ports - Comma Detection and Alignment --------------
         .RXBYTEREALIGN0_OUT             (RXREALIGN_OUT_LANE8 ),
         .RXBYTEREALIGN1_OUT             (RXREALIGN_OUT_LANE9 ),
         .RXENMCOMMAALIGN0_IN           (ENMCOMMAALIGN_IN_LANE8),
         .RXENMCOMMAALIGN1_IN           (ENMCOMMAALIGN_IN_LANE9),
         .RXENPCOMMAALIGN0_IN           (ENPCOMMAALIGN_IN_LANE8),
         .RXENPCOMMAALIGN1_IN           (ENPCOMMAALIGN_IN_LANE9),
         //----------------- Receive Ports - RX Data Path interface -----------------
         .RXDATA0_OUT                    (RXDATA_OUT_LANE8),
         .RXDATA1_OUT                    (RXDATA_OUT_LANE9),
         .RXRESET0_IN                   (RXRESET_IN_LANE8 ),
         .RXRESET1_IN                   (RXRESET_IN_LANE9),
         .RXUSRCLK0_IN                  (RXUSRCLK_IN),
         .RXUSRCLK1_IN                  (RXUSRCLK_IN),
         .RXUSRCLK20_IN                 (RXUSRCLK2_IN),
         .RXUSRCLK21_IN                 (RXUSRCLK2_IN),
         //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
         .RXCDRRESET0_IN                (tied_to_ground_i),
         .RXCDRRESET1_IN                (tied_to_ground_i),
         .RXN0_IN                       (RX1N_IN_LANE8),
         .RXN1_IN                       (RX1N_IN_LANE9),
         .RXP0_IN                       (RX1P_IN_LANE8),
         .RXP1_IN                       (RX1P_IN_LANE9),
         //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
         .RXBUFRESET0_IN                (tied_to_ground_i),
         .RXBUFRESET1_IN                (tied_to_ground_i),
         .RXBUFSTATUS0_OUT               ({RXBUFERR_OUT_LANE8,open_rxbufstatus_lane8_i} ),
         .RXBUFSTATUS1_OUT               ({RXBUFERR_OUT_LANE9,open_rxbufstatus_lane9_i} ),
         .TXBUFSTATUS0_OUT               ({TXBUFERR_OUT_LANE8,open_txbufstatus_lane8_i} ),
         .TXBUFSTATUS1_OUT               ({TXBUFERR_OUT_LANE9,open_txbufstatus_lane9_i} ),
         .RXCHANISALIGNED0_OUT           (CHBONDDONE_OUT_LANE8),
         .RXCHANISALIGNED1_OUT           (CHBONDDONE_OUT_LANE9 ),
         .RXCHANREALIGN0_OUT             ( ),
         .RXCHANREALIGN1_OUT             ( ),
         //-------------------- Receive Ports - RX Oversampling ---------------------

         //--------------- Receive Ports - RX Polarity Control Ports ----------------
         .RXPOLARITY0_IN                (RXPOLARITY_IN_LANE8),
         .RXPOLARITY1_IN                (RXPOLARITY_IN_LANE9),
         //------------------- Shared Ports - Tile and PLL Ports --------------------
         .CLKIN_IN                      (REFCLK),

         .GTXRESET_IN                   (GTXRESET_IN),
         .PLLLKDET_OUT                   (plllkdet_lane4_i),
         .REFCLKOUT_OUT                  (REFCLKOUT_OUT_LANE4),
         .RESETDONE0_OUT                 (resetdone0_lane4_i),
         .RESETDONE1_OUT                 (resetdone1_lane4_i),
         .TXCHARISK0_IN                 (TXCHARISK_IN_LANE8),
         .TXCHARISK1_IN                 (TXCHARISK_IN_LANE9),
         //---------------- Transmit Ports - TX Data Path interface -----------------
         .TXDATA0_IN                    (TXDATA_IN_LANE8),
         .TXDATA1_IN                    (TXDATA_IN_LANE9),
         .TXOUTCLK0_OUT                  (TXOUTCLK1_OUT_LANE8),
         .TXOUTCLK1_OUT                  (TXOUTCLK1_OUT_LANE9),
         .TXRESET0_IN                   (TXRESET_IN_LANE8 ),
         .TXRESET1_IN                   (TXRESET_IN_LANE9),
         .TXUSRCLK0_IN                  (TXUSRCLK_IN),
         .TXUSRCLK1_IN                  (TXUSRCLK_IN),
         .TXUSRCLK20_IN                 (TXUSRCLK2_IN),
         .TXUSRCLK21_IN                 (TXUSRCLK2_IN),
         //------------- Transmit Ports - TX Driver and OOB signalling --------------
         .TXN0_OUT                       (TX1N_OUT_LANE8),
         .TXN1_OUT                       (TX1N_OUT_LANE9),
         .TXP0_OUT                       (TX1P_OUT_LANE8),
         .TXP1_OUT                       (TX1P_OUT_LANE9)
 );
 
endmodule
