
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.1 EDK_O.40d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xemaclite.h"

/*
* The configuration table for devices
*/

XEmacLite_Config XEmacLite_ConfigTable[] =
{
	{
		XPAR_NF10_MDIO_0_DEVICE_ID,
		XPAR_NF10_MDIO_0_BASEADDR,
		XPAR_NF10_MDIO_0_TX_PING_PONG,
		XPAR_NF10_MDIO_0_RX_PING_PONG,
		XPAR_NF10_MDIO_0_INCLUDE_MDIO,
		XPAR_NF10_MDIO_0_INCLUDE_INTERNAL_LOOPBACK
	}
};


